### ISSUE TITLE
Modules are all loaded upfront, without execution of the interjected javascript.

### ISSUE THREAD

**Issue by WillAvudim** [swc-project/swc#4548] opened 2022-05-06 11:31 UTC
### Describe the bug

When running ts-node with --swc, it appears that all modules are loaded upfront, ignoring the javascript code preceding or following the import declaration for that module.

For example, if the entry for a server application contains code that installs and initializes segfault crash handles and configuration values, it will not execute the code prior to loading the subsequent SQL modules, which result in an application crash not logged to the cloud storage facility correctly:

```
// Will be loaded as step 1.
import * as segfault_handler from 'segfault-handler'

// SWC ignores this till step 4. Normal javascript executes this as step 2.
segfault_handler.registerHandler(...)

// SWC loads this as step 2. Javascript, as step 3.
import * as config from 'cloud-config-settings'

// SWC ignores this till step 4. Javascript executes as step 4.
config.Apply()

// SWC executes this as step 3 leading to unreported failure in prod. Javascript executes this as step 5, with steps 1-4 fully completed (segfault and config installed).
import * as mysql from 'mysql'
```

### Input code

```typescript
---- ./a.ts ------
console.log(`Module A`)

export function FA(): void {
  console.log(`FA`)
}


---- ./b.ts ------
console.log(`Module B`)

export function FB(): void {
  console.log(`FB`)
}


---- ./main.ts ------
console.log(`Before A`)

import * as a from "./a"
a.FA()

console.log(`After FA`)

import * as b from "./b"
b.FB()

console.log(`After FB`)
```

### Config

```json
(all settings are default, .swcrc is not present)
```

### Expected behavior

The correct sequence of execution, when run without --swc:

```
Before A
Module A
FA
After FA
Module B
FB
After FB
```

### Actual behavior

The printout with tsnode --swc:

```
Module A
Module B
Before A
FA
After FA
FB
After FB
```

### Version

@swc/core 1.2.177

**Comment by Austaras** [comment] 2022-05-06 23:20
This behavior aligns to babel and native ESM semantics -- that import is hoisted and all imported modules are executed before current module.

**Comment by kwonoj** [comment] 2022-05-06 23:38
@ Austaras is correct, this is intended design to preserve ecma semantics. Static import syntax is always hoisted above any other expr evaluation. Dupe of https://github.com/swc-project/swc/discussions/2729 .

**Closed by kwonoj** 2022-05-06 23:38 UTC
Labels: C-bug
