### ISSUE TITLE
exclude is not working when there are multiple entries 

### ISSUE THREAD

**Issue by samrat41** [swc-project/swc#7413] opened 2023-05-18 17:31 UTC
### Describe the bug

test.jsx and test.tsx files are not being excluded 

### Config

```json
[{
exclude: [".*test.jsx?$"],
test: ".*\\.jsx?$",
"jsc": {
"parser": {
"syntax": "ecmasript",
"jsx": true
},
"externalHelpers": true
}
},
{
exclude: [".*test.tsx?$"],
test: ".*\\.tsx?$",
"jsc": {
"parser": {
"syntax": "typescript",
"jsx": true
},
"externalHelpers": true
}
}



]
```

### Expected behavior

It should exclude *.test.tsx and *.test.jsx files.

### Version

0.1.62

**Comment by kwonoj** [comment] 2023-05-18 19:09
This is dupe of https://github.com/swc-project/swc/issues/5726, there are some non-intuitive behavior with multiple configs with array and we'll going to deprecate array for those reason.

**Closed by kwonoj** 2023-05-18 19:09 UTC
Labels: C-bug
