### ISSUE TITLE
transform optional chaining for array expression error

### ISSUE THREAD

**Issue by GiveMe-A-Name** [swc-project/swc#7469] opened 2023-05-30 06:55 UTC
### Describe the bug

After swc transform, the result of run is different  between source code and output code.
```js
// input code 
const getMaxId = () => {
  const nodeList = [];
  const ids = nodeList?.map?.((item) => item.id).map?.(Number);
  console.log(ids, `len: {ids.length}`);
};
getMaxId(); // [], len: 0
```

but after transform:
```js
var getMaxId = function() {
    var _nodeList_map, _nodeList_map_map, _nodeList_map1;
    var nodeList = [];
    var ids = (_nodeList_map_map = _nodeList_map = nodeList === null || nodeList === void 0 ? void 0 : (_nodeList_map1 = nodeList.map) === null || _nodeList_map1 === void 0 ? void 0 : _nodeList_map1.call(nodeList, function(item) {
        return item.id;
    }).map) === null || _nodeList_map_map === void 0 ? void 0 : _nodeList_map_map.call(_nodeList_map, Number);
    console.log(ids, "len: ".concat(ids.length)); 
};

getMaxId(); // [ <1 empty item> ], len: 1
```

### Input code

```typescript
const getMaxId = () => {
  const nodeList = [];
  const ids = nodeList?.map?.((item) => item.id).map?.(Number);
  console.log(ids, `len: {ids.length}`);
};

getMaxId();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "minify": {
      "compress": false,
      "mangle": false,
      "module": true
    },
    "externalHelpers": true,
    "target": "es5"
  },
  "minify": false,
  "isModule": true,
  "module": {
    "type": "es6"
  },
}
```

### Playground link

https://play.swc.rs/?version=1.3.60&code=H4sIAAAAAAAAA0vOzysuUUhPLfFNrPBMUbBV0NBUsLVTqOZSUEgGS%2BXlp6T6ZAIZtgrRsdZw4cyUYqAITNJeLzexwF5PQyOzJDUXbACIoZeZogmV8CvNTUot0oTpz89J1cvJT9cAmqKjkJCTmmeloFIN5OgBmeklGbUJQJW11gACaCAQnAAAAA%3D%3D&config=H4sIAAAAAAAAA2WPMQ7DIAxF954CMWdth56gSw9hUSeiAoJsRwqKcvdCIGmqbvb7%2Fvb3clFKv9nou1pymZsIxEhHnwmnIDBnoiVFZEM2it7Etaseb4Pt09ljRh8JmTPrwTF2u%2BAhDA7%2F8fiaNiw04c9unAUpgHugi0jcRpooQANKiYZ8LZk21zfPcURbfp5P1LGdtNfLe3XXre1aP%2BUCj3UgAQAA

### Expected behavior

The code results remain the same as the original

### Version

1.3.61

**Comment by jridgewell** [comment] 2023-05-30 16:20
I believe this is a duplicate of https://github.com/swc-project/swc/issues/7003

**Comment by kdy1** [comment] 2023-05-31 03:47
Closing as duplicate

**Closed by kdy1** 2023-05-31 03:47 UTC
Labels: C-bug
