### ISSUE TITLE
Why there are<anon> files in source map?

### ISSUE THREAD

**Issue by jecfish** [swc-project/swc#7851] opened 2023-08-24 12:15 UTC
### Describe the bug

`swc` geneate source map with `<anon>` file. View the sources in Chrome DevTools. Chrome DevTools used the source map files to generate the output. Here is the output:

![sm](https://github.com/parcel-bundler/parcel/assets/5917927/b3f02e7f-5d00-4aa1-8bf5-f039489b34bb)

These files are:

- `index...js` is the minifed js file
- `src/script.ts` is the file mapped from source map with the `inde..js.map` file.
- `<anon>` is the file mapped from source map with the `inde..js.map` file.

This issue make Chrome DevTools display `<anon>` files in the Sources. Developers are confuse about what the file is about. What is the purpose of the <anon> output? From the file, I guess it is the intermediary (unminified) javascript output. Does swc dev use that for debugging?

Code line in swc that generate anon: https://github.com/swc-project/swc/blob/662f236aa5c1375ea4b175dbb6d85ad974503b84/crates/swc_common/src/syntax_pos.rs#L258
Code sample in the screenshot: https://github.com/jecfish/consistent-source-map-demo
Downstream issue reported in Parceljs: https://github.com/parcel-bundler/parcel/issues/9208

### Expected behavior

- Expect to see `src/script.ts`. 
- Do not expect to see `<anon>` file. 
- Expect the `index...js.map` source map file to have only `"sources": ["src/script.ts"]`

### Actual behavior

- See `<anon>` file in Chrome DevTools
- The `index...js.map` source map file have  2 items in`"sources": ["<anon>", "src/script.ts"]`

### Version

1.3.78

### Additional context

The possible solution is to remove `<anon>` from the source map. Or give it a better name (e.g. index ...unminified.js)?

**Comment by kdy1** [comment] 2023-08-24 12:43
I cannot reproduce. 
<img width="1840" alt="image" src="https://github.com/swc-project/swc/assets/29931815/8873a324-c77f-4f57-a640-06a7d6368bd4">

What's the command you used?

**Comment by kdy1** [comment] 2023-08-29 03:36
Closing as not reproducible

**Closed by kdy1** 2023-08-29 03:36 UTC
Labels: C-bug
