### ISSUE TITLE
Function Length Error beacuse of Simply Adding Parameters

### ISSUE THREAD

**Issue by clhiker** [swc-project/swc#2825] opened 2021-11-21 06:44 UTC
### Describe the bug

When printing the length of a function, the number of formal parameters of the function should be printed. The number of formal parameters does not include the number of remaining parameters, but only "**the number of parameters before the first one with default value**"
However, after SWC conversion, the length of the function is redundant, and the number of default value parameters is calculated.

### Input code

```typescript
function sum(x, y = 0) {
}

console.log(sum.length); // 1
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.111&code=H4sIAAAAAAAAA0srzUsuyczPUyguzdWo0FGoVLBVMNBUqOaq5eJKzs8rzs9J1cvJT9cASuvlpOall2RoWivo6ysYAgCtZO0SOQAAAA%3D%3D&config=H4sIAAAAAAAAA0VOOw6DMAy9i2fWLtygA4ewgkFBSRzZRmqKuHsTNcBkv4%2Ff8wGbOhgPyChK0jYtyfADI5CLqE58NhiqrVILBqVzAENZyZpFX1ULzEpdHSD65JfSkhzHLKT6SJjWcDnPGhR53htxgJVcZzuJnDatqWrind23fzjx%2FDQF%2FJYbJH4nI%2BH8vHl90h1ep15nstP5A1SlDpf7AAAA

### Expected behavior

SWC should not simply add parameters, here is a solution
```js
function sum(x) {
  var y = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 0;
}
console.log(sum.length); // 1
```

### Version

1.2.111

### Additional context

I run swc use cmd as follows
```bash
npx swc --config-file=.swcrc poc.js -o poc.js
```
The environment is ubuntu 20.04 amd64.

**Comment by daflyinbed** [comment] 2021-11-21 13:45
duplicate of #2800

**Comment by Austaras** [comment] 2021-11-26 15:23
I somehow missed this one in #2611

**Comment by Austaras** [comment] 2021-11-26 17:02
Also for chrome 47 48 swc will generate invalid code

**Comment by Austaras** [comment] 2021-11-28 15:01
> Also for chrome 47 48 swc will generate invalid code

The conclusion is `parameter` and `destructing` shouldn't rely on each other

**Comment by kdy1** [comment] 2021-11-29 09:38
Ah... I see, thanks!

**Closed** 2021-12-02 01:04 UTC
Labels: C-bug
