### ISSUE TITLE
How to compile all the files in a directory

### ISSUE THREAD

**Issue by ShivamJoker** [swc-project/swc#2092] opened 2021-08-16 20:55 UTC
I am using tsc in AWS CDK and it's really slow, it compiles all the TS files into JS in the same directory from the root folder so Is there any way we can compile multiple files in the same directory ?

If I can get some configuration for that, it would be great to move from tsc compiler.

**Comment by tmpfs** [comment] 2021-08-17 00:15
I believe `swc src -d lib` will do what you want, you can configure `.swcrc` too for various compiler options.

**Comment by ShivamJoker** [comment] 2021-08-21 12:19
@tmpfs I think I tried but it didn't do anything

I tried looking into the docs, but not sure what would be the config to compile all the ts files into commonjs

**Comment by tmpfs** [comment] 2021-08-24 07:07
You should add this file: https://github.com/swc-project/cli/blob/master/.swcrc to your project and then install `@swc/core` and `@swc/cli` into your project, afterwards you can use `npx` to run `spack` like I mentioned (or without `npx` if it is a `package.json` script):

```
npx spack . -d .
```

Hope that works :+1:

**Comment by HKalbasi** [comment] 2021-09-05 22:23
Same issue.

@tmpfs I think you mean `npx swc . -d .`, yes? because spack doesn't have `-d`. And `swc` works with subdirectories but it has problem with `.` and do nothing.

**Comment by tmpfs** [comment] 2021-09-06 00:29
@HKalbasi , yes sorry I meant `swc` not `spack`.

If there is a bug with handling `.` in `swc` please raise an issue for that, a workaround could be to use `$PWD` (assuming your shell sets it):

```
npx swc $PWD -d $PWD
```

**Comment by HKalbasi** [comment] 2021-09-06 07:20
@tmpfs Thanks, it works with `$PWD`. Is it possible to ignore `node_modules` folder?

**Comment by tmpfs** [comment] 2021-09-06 07:31
@HKalbasi, I think the `--ignore` option is what you want:

```
  --ignore [list]                             list of glob paths to **not** compile
```

**Comment by HKalbasi** [comment] 2021-09-06 10:39
`--ignore` doesn't work (I tried with `node_modules/**/*`, `node_modules/*`, `node_modules`, `"node_modules/**/*"`) but `exclude` from #466 works. From that issue, seems that `node_modules` should already being ignored. After some more problems, I gave up using `swc` and return to `tsc`. I think compiling whole root folder needs an special flag and swc isn't happy with passing `$PWD` (and it do nothing with `.`, maybe it is intentional)

**Comment by tmpfs** [comment] 2021-09-07 00:55
Thanks for the heads up @HKalbasi, if you are able to put together an MVP reproducing the issue it would be helpful :pray: 

@kdy1, this sounds like a bug to me, I think `swc` should support both `.` and `--ignore node_modules` for this use case.

**Comment by reslear** [comment] 2022-02-21 15:10
@HKalbasi any news?

**Comment by ben-biddington** [comment] 2022-02-28 03:45
I am confused by behaviour related to this where, when using `-d`, some directories are omitted from the resultant output.

See example here: https://github.com/ben-biddington/topaz#the--d-option-omits-directories

What am I doing wrong?

**Comment by ShivamJoker** [comment] 2022-03-03 09:12
The `.` isn't getting handled

but this works `npx swc **/**/*.ts -d $PWD/dist`

**Comment by ben-biddington** [comment] 2022-03-04 07:04
Okay, I'll open another issue as this is different

**Comment by ShivamJoker** [comment] 2022-03-04 07:10
Thanks 

@ben-biddington also one more issue is that if the directory is only one level the compiler doesn't keep it in the directory, it puts them in root.

Input

```
|- dir
    |- file.ts
```

Output

```
|- file.js
```

**Comment by kimhongsu** [comment] 2022-03-06 15:45
> Thanks
> 
> @ben-biddington also one more issue is that if the directory is only one level the compiler doesn't keep it in the directory, it puts them in root.
> 
> Input
> 
> ```
> |- dir
>     |- file.ts
> ```
> 
> Output
> 
> ```
> |- file.js
> ```

I have the same issue.

**Comment by kdy1** [comment] 2022-03-12 02:47
Closing as this is not an issue

**Closed by kdy1** 2022-03-12 02:47 UTC
