### ISSUE TITLE
commonjs transformation not working via JS API

### ISSUE THREAD

**Issue by cspotcode** [swc-project/swc#151] opened 2019-02-11 01:57 UTC
swc does not transform ES6 import syntax into a `require()` call when invoked via the JS API. (node bindings)

## Reproduction

`npm install swc` and then:

```javascript
console.log(
  require('swc').transformSync(`
    import {lodash} from 'lodash'
  `, {
    module: {
      type: 'commonjs'
    }
  }).code
);
```

Outputs:

```
import { lodash }from 'lodash';
```

**Comment by cspotcode** [comment] 2019-02-11 02:15
It appears that "module" transformation options can be specified via a ".swcrc" file but not programmatically via the API.

**Comment by stefanpenner** [comment] 2019-02-11 04:24
Ya, ran into this one as well. Passing options via the JS API appears to be MIA.

**Comment by kdy1** [comment] 2019-02-11 08:51
Fixed with swc@1.0.5

**Closed by kdy1** 2019-02-11 08:51 UTC

**Comment by stefanpenner** [comment] 2019-02-12 00:36
I verified that the problem is resolved, thank you!
