### ISSUE TITLE
v1.5.20 exploded. Please fix version to 1.5.7 for now

### ISSUE THREAD

**Issue by mateussaggin** [swc-project/swc#8988] opened 2024-05-28 07:13 UTC
https://github.com/swc-project/swc/blob/b4799f7e88acf322acc860b20386ebd7c4dba225/packages/core/package.json#L94

**Comment by kdy1** [comment] 2024-05-28 07:18
https://github.com/swc-project/swc/commit/76b4de1b66eeedf3740e2f1e363810b90476dbc2 would fix it, but I'll close this issue after verifying that it works.

**Comment by cope** [comment] 2024-05-28 07:35
I'm guessing that is the cause for https://github.com/pnpm/pnpm/issues/6603#issuecomment-2134535217 ?

**Comment by hakimassouane2** [comment] 2024-05-28 07:37
> I'm guessing that is the cause for [pnpm/pnpm#6603 (comment)](https://github.com/pnpm/pnpm/issues/6603#issuecomment-2134535217) ?
> 
> > `ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@swc/types@workspace:^" is in the dependencies but no package named "@swc/types" is present in the workspace`

Most likely, I'm having the same issue

**Comment by lifeiscontent** [comment] 2024-05-28 07:40
looks like the way publishing worked in swc changed maybe some hooks are no longer running as expected? https://github.com/swc-project/swc/compare/v1.5.11...main

**Comment by kdy1** [comment] 2024-05-28 07:49
@Aarebecca Yeap, exactly. I changed it to use `yarn npm publish` and triggered a new release

**Comment by lifeiscontent** [comment] 2024-05-28 07:53
@kdy1 any thoughts on using `pnpm` I've found using it for monorepo management to be a lot easier especially around publishing

**Comment by leezCtt** [comment] 2024-05-28 07:59
![image](https://github.com/swc-project/swc/assets/53547371/199b6629-3c66-4345-8c0d-e706b2c04dbf)
![Uploading screenshot-20240528-155901.png…]()

**Comment by leezCtt** [comment] 2024-05-28 07:59
![screenshot-20240528-155901](https://github.com/swc-project/swc/assets/53547371/5980b86e-a3d0-4be0-b984-06c8fd30be41)

**Comment by maoxiaoke** [comment] 2024-05-28 08:00
Same here 
<img width="897" alt="image" src="https://github.com/swc-project/swc/assets/13417006/13fb2e9f-990a-4dc9-9fc2-fbaeca7bf9c6">

**Comment by cckn** [comment] 2024-05-28 08:02
To resolve this, fix the version of `"@swc/core"` to 1.5.7.

```json
"dependencies": {
  "@swc/core": "1.5.7"
}
```

**Comment by xqin** [comment] 2024-05-28 08:28
PLEASE UNPUBLISH `@swc/core@1.5.11` FIRST!!!

**Comment by heozeop** [comment] 2024-05-29 02:57
It will be resolved soon ? Or I'll just do update using `"resolutions": {"@swc/core":"1.5.7"}`

**Comment by kdy1** [comment] 2024-05-29 04:27
![image](https://github.com/swc-project/swc/assets/29931815/329115fe-112c-4fd5-bc9e-a00d9c5e8762)

I'm trying my best. And normally, you don't need overriding because the `latest` tag of npm is 1.5.7

**Comment by valentinpalkovic** [comment] 2024-05-29 11:56
@kdy1 Overriding is still necessary if `@swc/core` is a transitive dependency and the package requiring `@swc/core` defines its version as a version range. Then, it doesn't matter which version is tagged with `latest,` but at least the package manager yarn (v4) will install the latest available stable version that is published (as of now 1.5.20 - which is borked as well)

**Comment by kdy1** [comment] 2024-05-30 06:27
Finally it's fixed.

**Closed by kdy1** 2024-05-30 06:27 UTC
