### ISSUE TITLE
Wrong behavior for loop with finally statement.

### ISSUE THREAD

**Issue by dudubs** [swc-project/swc#7211] opened 2023-04-04 17:11 UTC
### Describe the bug

When I run the code:
`
 (async () => {
    let x = true;
    let c = 0;
    try {
      while (x) {
        x = false;
        await Promise.resolve();
      }
    } finally {
      console.log("Count" + ++c);
    }
  })();
`
The expected output is:
`
Count1
`
What I got:
`
Count1
Count2
`.

From some reason the 'finally' called two times after end of loop.

link: https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAA02NTQrCMBCF94J3eHSVECjdS914Aa8QwlQDYwJJalskdze2xvpWMx%2FvB0LHxRkIif6M1%2FGAIqaEGT1SGOm0I1NQ9%2F1TWKobmO6WCWKWO8JaMGiOteEjPWmbcA3%2BYSO1gaLnJwn5c%2BTtyBis08x%2FE8a7YqaW%2FU00Fz%2B61EBBKVPDazTLUvYGez%2FLGdMAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

thanks.

### Input code

```typescript
(async () => {
    let x = true;
    let c = 0;
    try {
      while (x) {
        x = false;
        await Promise.resolve();
      }
    } finally {
      console.log("Count" + ++c);
    }
  })();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAA02NTQrCMBCF94J3eHSVECjdS914Aa8QwlQDYwJJalskdze2xvpWMx%2FvB0LHxRkIif6M1%2FGAIqaEGT1SGOm0I1NQ9%2F1TWKobmO6WCWKWO8JaMGiOteEjPWmbcA3%2BYSO1gaLnJwn5c%2BTtyBis08x%2FE8a7YqaW%2FU00Fz%2B61EBBKVPDazTLUvYGez%2FLGdMAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

To execute finally statement once after loop

### Version

1.3.44

**Comment by kdy1** [comment] 2023-04-05 01:14
Closing as dullicate

**Comment by kdy1** [comment] 2023-04-05 01:14
There's an issue related to `yield`. (I'm on mobile now)

**Closed** 2023-04-05 01:14 UTC
Labels: C-bug

**Comment by kdy1** [comment] 2023-04-05 04:24
Duplicate of https://github.com/swc-project/swc/issues/5913
