### ISSUE TITLE
Inherits missing the props 

### ISSUE THREAD

**Issue by Chastrlove** [swc-project/swc#3569] opened 2022-02-15 03:21 UTC
### Describe the bug

if the env targets includes "last 1 safari version" and the arrow function has some default props , the compile code will miss the inherits props

### Input code

```typescript
export class TableView extends React.Component {
  
  constructor(props) {
    super(props);
  }

  public getProps= ()=>{

  }
  
  public getSearchForm = (innerWidth = 0) => {
   this.getProps();
  }





  
}
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "tsx": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": false
    },
    "target": "es2016",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "targets": "last 1 safari version"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.139&code=H4sIAAAAAAAAA0WNQQuDMAyF7%2F0VOepFdh96Gew8tuHOtYZZ0KYkKRPE%2F77qkIUQyHuP7%2BEciRXcaEXgabsRW48fwFkx9AJ3tE6rC02RAgaFxQDkdRREOTklLiJTlHJ3ACRFPKRzVlaTT0zd6B28UW%2BbUUNR1s1idnvH%2FQMPtOyGK%2FEEOeZDQH75Xof8nUqom1%2BNDl6qA1ccRdtk3Gq%2BIOmccNQAAAA%3D&config=H4sIAAAAAAAAA0WQMQ6DMAxFr4I8M5QOHZg7dOEQVjAoVUgi261AKHdvCFA2K3n%2F%2BcsrvMVAuwLNSuzRvchFYoFW%2BUM1RGQh3gBZvOIMLegSSQzbqFBDTyYwargSKvM%2BpjwzehkCT5vA0YhmeZ6Bk%2F8bOlLsURHaAZ2UOPJImleS3G%2FNI69zIQgdQA2T9XZYNrcJU2QSub7Qj%2B4kU3ZNof9sD2vpX5wPSJfjyFnpDnBvR%2F5bMqVJ1oND0aqpBAdkW33zqWzwkNIPL3xF9UkBAAA%3D

### Expected behavior

```javascript 
export class TableView extends React.Component {
    constructor(props){
        var _this;
        super(props), _this = this;
        this.getProps = ()=>{};
        this.getSearchForm = function() {
            let innerWidth = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : 0;
            _this.getProps();
        };
    }
}
```

### Actual behavior

```javascript 
export class TableView extends React.Component {
    constructor(props){
        var _this;
        super(), _this = this;
        this.getProps = ()=>{};
        this.getSearchForm = function() {
            let innerWidth = arguments.length > 0 && arguments[0] !== void 0 ? arguments[0] : 0;
            _this.getProps();
        };
    }
}
```
### Version

1.2.139

**Comment by Austaras** [comment] 2022-02-15 03:58
The generates same output as babel, do you mean to use javascript instead of typescript? If so, it's a duplicate of #3471

**Comment by Chastrlove** [comment] 2022-02-15 04:31
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/17813559/153992458-c27f0be5-187b-4903-9f05-82a2e5d0f0e9.png">
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/17813559/153992801-3c8a44b0-ce92-4900-b2c9-4a306b97de25.png">


I mean the "super" syntax miss the params  , it's different from babel ,and it will cause some errors

**Comment by Austaras** [comment] 2022-02-15 04:33
Wow, that's bad. As a temporary fix, you could enable `bugfixes` in `env`

**Comment by Chastrlove** [comment] 2022-02-15 04:38
It works. Thank you

**Closed** 2022-02-15 06:42 UTC
Labels: C-bug
