### ISSUE TITLE
Incorrect parsing of <> generics 

### ISSUE THREAD

**Issue by July-ing** [swc-project/swc#7493] opened 2023-06-05 13:35 UTC
### Describe the bug

<img width="1125" alt="image" src="https://github.com/swc-project/swc/assets/26430264/7db9e46b-6a8b-4a5c-af14-612a3517a66b">

### Input code

```typescript
import { transform } from '@swc/core';

function doTransform(opts: { code: string }) {
  return transform(opts.code, {
    filename: 'foo.tsx',
    module: {
      type: 'es6',
      ignoreDynamic: true,
    },
    jsc: {
      parser: {
        syntax: 'typescript',
        tsx: true,
        dynamicImport: true,
      },
      target: 'es2015',
      transform: {
        react: {
          runtime: 'automatic',
          pragma: 'React.createElement',
          pragmaFrag: 'React.Fragment',
          throwIfNamespace: true,
          development: true,
          useBuiltins: true,
        },
      },
    },
  });
}

test('', async () => {
  const a = await doTransform({
    code: `const onChange = useCallback<<T extends keyof typeof initialState>(key: T, value: typeof initialState[T]) => void>(
          (key, value) => {
            setState((preState) => {
              preState[key] = value;
            });
          },
          [setState],
        );`,
  });
  console.log(a);
});
```

### Config

```json
{
    filename: 'foo.tsx',
    module: {
      type: 'es6',
      ignoreDynamic: true,
    },
    jsc: {
      parser: {
        syntax: 'typescript',
        tsx: false,
        dynamicImport: true,
      },
      target: 'es2015',
      transform: {
        react: {
          runtime: 'automatic',
          pragma: 'React.createElement',
          pragmaFrag: 'React.Fragment',
          throwIfNamespace: true,
          development: true,
          useBuiltins: true,
        },
      },
    },
  }
```

### Expected behavior

JavaScript is output.

### Version

1.3.60

**Comment by kdy1** [comment] 2023-06-07 03:46
Duplicate of https://github.com/swc-project/swc/issues/7187

**Closed by kdy1** 2023-06-07 03:46 UTC
Labels: C-bug
