### ISSUE TITLE
use @swc/core with webpack5, run build failed

### ISSUE THREAD

**Issue by 513205785Xie** [swc-project/swc#9307] opened 2024-07-21 09:03 UTC
### Describe the bug

use @swc/core version 1.3.95, run build failed, The build stops with the error message `Module build failed: Error: Cannot find module '@swc/types'`, This error suddenly appeared today, When I installed @swc/types@0.1.9, the error disappeared.

### Input code

```typescript
"devDependencies": {
    "@swc/core": "1.3.95",
    "swc-loader": "0.2.3",
    "typescript": "5.2.2",
    "typescript-plugin-css-modules": "5.0.1",
    "webpack": "5.88.2",
    "webpack-cli": "5.1.4",Ï
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "refresh": true
      }
    }
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/

### Expected behavior

Packing should succeed

### Version

1.3.95

**Comment by afc163** [comment] 2024-07-21 12:24
+1

https://github.com/ant-design/ant-design/actions/runs/10026631634/job/27714907775

```
Run ant-design/size-limit-action@master
/home/runner/.bun/bin/bun install
bun install v1.1.20 (ae194892)
Resolving dependencies
Resolved, downloaded and extracted [11590]
warn: incorrect peer dependency "stylelint@13.13.1"

warn: incorrect peer dependency "stylelint@13.13.1"
Saved lockfile

$ is-ci || husky && dumi setup
info  - dumi v2.4.6
fatal - Error: Register plugin /home/runner/work/ant-design/ant-design/node_modules/dumi/dist/features/compile/index.js failed, since Unexpected token 'export'
    at Plugin.apply (/home/runner/work/ant-design/ant-design/node_modules/@umijs/core/dist/service/plugin.js:76:15)
    at DumiService.initPlugin (/home/runner/work/ant-design/ant-design/node_modules/@umijs/core/dist/service/service.js:463:33)
    at DumiService.run (/home/runner/work/ant-design/ant-design/node_modules/@umijs/core/dist/service/service.js:259:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DumiService.run2 (/home/runner/work/ant-design/ant-design/node_modules/umi/dist/service/service.js:65:12)
    at async run (/home/runner/work/ant-design/ant-design/node_modules/dumi/dist/service/cli.js:57:7)
    at async /home/runner/work/ant-design/ant-design/node_modules/dumi/dist/cli.js:30:5 {
  [cause]: /home/runner/work/ant-design/ant-design/node_modules/@swc/types/index.ts:1
  export interface Plugin {
  ^^^^^^
  
  SyntaxError: Unexpected token 'export'
      at internalCompileFunction (node:internal/vm:76:18)
      at wrapSafe (node:internal/modules/cjs/loader:1283:20)
      at Module._compile (node:internal/modules/cjs/loader:1328:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
      at Object.newLoader [as .ts] (/home/runner/work/ant-design/ant-design/node_modules/@umijs/utils/compiled/pirates/index.js:1:1684)
      at Module.load (node:internal/modules/cjs/loader:1203:32)
      at Module._load (node:internal/modules/cjs/loader:1019:12)
      at Module.require (node:internal/modules/cjs/loader:1231:19)
      at require (node:internal/modules/helpers:177:18)
      at Object.<anonymous> (/home/runner/work/ant-design/ant-design/node_modules/@swc/core/index.js:51:14)
}
fatal - A complete log of this run can be found in:
fatal - /home/runner/work/ant-design/ant-design/node_modules/.cache/logger/umi.log
fatal - Consider reporting a GitHub issue on [https://github.com/umijs/dumi/issues](https://github.com/umijs/dumi/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen)
error: prepare script from "antd" exited with 1
Error: The process '/home/runner/.bun/bin/bun' failed with exit code 1
```

**Comment by y779102260** [comment] 2024-07-21 13:31
![image](https://github.com/user-attachments/assets/c8b150fc-c714-42f2-bfe9-dfe2077aba72)

Forget build CJS?

**Comment by kdy1** [comment] 2024-07-21 14:07
Duplicate of https://github.com/swc-project/swc/issues/9306

**Closed by kdy1** 2024-07-21 14:07 UTC
Labels: C-bug
