### ISSUE TITLE
swc typescript parser includes commented out code leading to malformed output

### ISSUE THREAD

**Issue by Nimelrian** [swc-project/swc#197] opened 2019-02-13 08:01 UTC
Input:
```ts
// type Foo = "Oops";
const Link = "Boo";
```

Output:
```js
var Link = 'Boo';ps";
```

**Comment by kdy1** [comment] 2019-02-14 04:27
Closing as I can't reproduce this with master branch of swc, and test about comment passes.

https://github.com/swc-project/swc/blob/631eff9e8cd33c51700609ccd709a7d68d132e9d/ecmascript/codegen/src/stmt.rs#L110-L118

I also verified that `npx swc` emits valid file. See https://github.com/kdy1/swc-example/blob/master/inputs/issue-197/issue-197.ts

It results in
```js
// type Foo = "Oops";
var Link = 'Boo';

//# sourceMappingURL=issue-197.js.map
```

**Closed by kdy1** 2019-02-14 04:27 UTC
