### ISSUE TITLE
CancelablePromise (by openapi-typescript-codegen) never settles since version 1.3.66

### ISSUE THREAD

**Issue by brunouber** [swc-project/swc#7658] opened 2023-07-13 07:52 UTC
### Describe the bug

We're using openapi-typescript-codegen to build our own api sdk from the backend openapi.json.
openapi-typescript-codegen produces a number of methods, eg. client.postCreateUser, tha returns a CancelablePromise - it extends built-in Promise.

When transpiled using `swc`the promise created this way never settles (neither fulfill, nor reject).

I can start reproducing the issue using

```
"@swc/cli": "^0.1.62",
"@swc/core": "1.3.66"
``` 

Everything was fine until `@swc/core@1.3.65`

### Input code

```typescript
/**
 * Most of this code is CancelablePromise implementation.
 * Scroll at the bottom, and look at the `Main` function.
 */

class CancelError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CancelError";
  }

  public get isCancelled(): boolean {
    return true;
  }
}

interface OnCancel {
  readonly isResolved: boolean;
  readonly isRejected: boolean;
  readonly isCancelled: boolean;

  (cancelHandler: () => void): void;
}

class CancelablePromise<T> implements Promise<T> {
  #isResolved: boolean;
  #isRejected: boolean;
  #isCancelled: boolean;
  readonly #cancelHandlers: (() => void)[];
  readonly #promise: Promise<T>;
  #resolve?: (value: T | PromiseLike<T>) => void;
  #reject?: (reason?: any) => void;

  constructor(
    executor: (
      resolve: (value: T | PromiseLike<T>) => void,
      reject: (reason?: any) => void,
      onCancel: OnCancel
    ) => void
  ) {
    this.#isResolved = false;
    this.#isRejected = false;
    this.#isCancelled = false;
    this.#cancelHandlers = [];
    this.#promise = new Promise<T>((resolve, reject) => {
      this.#resolve = resolve;
      this.#reject = reject;

      const onResolve = (value: T | PromiseLike<T>): void => {
        if (this.#isResolved || this.#isRejected || this.#isCancelled) {
          return;
        }
        this.#isResolved = true;
        this.#resolve?.(value);
      };

      const onReject = (reason?: any): void => {
        if (this.#isResolved || this.#isRejected || this.#isCancelled) {
          return;
        }
        this.#isRejected = true;
        this.#reject?.(reason);
      };

      const onCancel = (cancelHandler: () => void): void => {
        if (this.#isResolved || this.#isRejected || this.#isCancelled) {
          return;
        }
        this.#cancelHandlers.push(cancelHandler);
      };

      Object.defineProperty(onCancel, "isResolved", {
        get: (): boolean => this.#isResolved,
      });

      Object.defineProperty(onCancel, "isRejected", {
        get: (): boolean => this.#isRejected,
      });

      Object.defineProperty(onCancel, "isCancelled", {
        get: (): boolean => this.#isCancelled,
      });

      return executor(onResolve, onReject, onCancel as OnCancel);
    });
  }

  get [Symbol.toStringTag]() {
    return "Cancellable Promise";
  }

  public then<TResult1 = T, TResult2 = never>(
    onFulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | null,
    onRejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null
  ): Promise<TResult1 | TResult2> {
    return this.#promise.then(onFulfilled, onRejected);
  }

  public catch<TResult = never>(
    onRejected?: ((reason: any) => TResult | PromiseLike<TResult>) | null
  ): Promise<T | TResult> {
    return this.#promise.catch(onRejected);
  }

  public finally(onFinally?: (() => void) | null): Promise<T> {
    return this.#promise.finally(onFinally);
  }

  public cancel(): void {
    if (this.#isResolved || this.#isRejected || this.#isCancelled) {
      return;
    }
    this.#isCancelled = true;
    if (this.#cancelHandlers.length) {
      try {
        for (const cancelHandler of this.#cancelHandlers) {
          cancelHandler();
        }
      } catch (error) {
        console.warn("Cancellation threw an error", error);
        return;
      }
    }
    this.#cancelHandlers.length = 0;
    this.#reject?.(new CancelError("Request aborted"));
  }

  public get isCancelled(): boolean {
    return this.#isCancelled;
  }
}

const MAIN = async () => {
  console.log("Running test");

  const p = new CancelablePromise((r) => {
    setTimeout(r, 1000, 42);
  });

  await p;

  console.log("Promise value is", p);
};

MAIN();
```

### Config

```json
npx swc ./index.ts
```

### Playground link

[Playground link](https://play.swc.rs/?version=1.3.66&code=H4sIAAAAAAAAA81XSW8TMRS%2B91dY6cUjjaJScUpoK4SoQGJTyQ1xcCYvyYBjB9vTErX57zwv4%2FEsCS1Cgh7SGfst31v8PU%2FBmdbkFRMF8NdKSUXgpwGx0MS%2F3Z8QUkihjaoKIxXdgNZsBROCK6VYZU6AEF1tIW5mU7dm1qUeC7YBckFGiYeR3d6f4M%2B2mvOyICswpNRegsOCZhMyl5IDE8G6AlMpQRADeF3ULoUBtWQFkI%2FCqzphBWwhBd%2BhwRvQkt%2FCIlqbdve%2FQWEO70dAiQBK0MKtv2FiwUFNCM3IxSW5leUCcdt%2FUwuvSPLK5hw%2BKbkpNbyYXZJys%2BWwAWE0SVYt%2BNMDoE8PgD0dBplEcdoCqxFtAvfL17bs1qOZJLCcF%2BUxXaH2LeMVCszIQy30rvxuBaPVoGHRWgW0rqXAJyZ2iUynq1yV4ScUFb6hlnu30JzjR%2FnNo451fchzLSVDz0xi97iNKHdin%2B%2BbNk4qg928ZFzDtLPr6zO8G6s0tN0uEUr4utTboSq4LuAuKQ2lIT15iNmBvw8Bet0ggbrhadrZtnpu1z64stg%2FVxrM0U1UP1IA3%2FSpb0LKJaG9vD089LOVrMUcZYmh%2BuxP48o%2BPg0UpmaIgRxcjX0MWb2%2FHwg3pKPdO%2F9BgLG3hgN0h20cUB8JMPDkxe857J9F2z4M422l122wA%2BF9nFv34wUsS2GJFkeR2dE63JyMGtSjPEGDc8eG3kwbDLobZk0Y%2B%2Bxp7nxCnuDOK%2FyZu5jrR%2FuLGgMOw7St6ZhGHsjjGcmbZmI6UmgozT6LA95O9i%2Bfd5u55GMjP7srw4ytvtKsPdnD9cBNyppfetcEswbxYoZYKm6eYRPPchLezh053oK69JNDiuuKL0sbn51Bkbxcl0cLHSYLyzhRHoioOM%2BDqbo0zpI%2FYs1MiQAGjZ1HY3aeJHO1gRAlO1edlPrHNnKaBJUnsLJumgpminXtopeYx0QzHMyhWJogjsbgYNEjuLG9Gee2s6%2F901X7thK8p66POuzZG8iUbTpaU5639Ze4LuW5%2FcG7QEPnjdsOA3IQK7NuDBu1S874Eq%2Fo1NN7S4%2FI5SChtsm4tUezPivvfTcRCvbinipbn8gq4zumBI3H15TSlkHhRQX5xikhJXnlxnp7Bux7ORrMAGbrLL0Wxalnb0XJ1wUd3cCPCjAhbC6V5eCsV%2FhHf3B0Sxa%2FPnzK3798%2BwFxMb0TRZih9feSzQ2XK0RTCYGsRwxCGmXNzZdsw42u942A5zK5ymkws3IDsjJU5eTZ2dlZTp6f%2B5C8OXbHSjQXTUfXwR5x9IcBYym2qGIHp0VuC%2F4LDcnsSf8NAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BCIOhERP9mOVBTl7oUE0maH3xszsA5KwcwGnmotxzIkTYx0ziXhHER%2FSgKSE7IhmwRuvRWu1agd4x5tRwOiaUKpW8j3hoOLkbHjLfM22DH%2FC030iZD5ClZUh8nhVTc0Jfj4XvayfaQ%2B9tA%2F4Ad12XkxWH71TaEFh%2B0LYuVI0xQBAAA%3D)

### Expected behavior

Promise is fulfilled.

### Actual behavior

Promise never settles.

### Version

1.3.66

### Additional context

This was initially reported as an issue on ferdikoomen/openapi-typescript-codegen's repository.
https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1626

**Comment by kdy1** [comment] 2023-07-13 09:39
I think this is duplicate of https://github.com/swc-project/swc/issues/7561, but need to check

**Comment by kdy1** [comment] 2023-07-19 05:56
Okay, this is a duplicate of #7561. @komyg Are you still willing to work on #7561?

**Closed by kdy1** 2023-07-19 05:56 UTC
Labels: C-bug

**Comment by komyg** [comment] 2023-07-19 11:41
> Okay, this is a duplicate of #7561. @komyg Are you still willing to work on #7561?

Yes, @kdy1. But I need help I think I found the source of the problem, but I am having trouble changing the visitor. Could you help me out?
