### ISSUE TITLE
minifier should inline a simple function with a throw statement

### ISSUE THREAD

**Issue by kdy1** [swc-project/swc#5685] opened 2022-08-31 04:29 UTC
### Describe the feature

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/29931815/187592988-91452183-924f-4a1c-a5ee-13f0f64bca0a.png">

swc vs terser

**Comment by Austaras** [comment] 2022-08-31 13:11
Where does this case came from? Seems likely to be fixed by #5607

**Comment by Austaras** [comment] 2022-08-31 13:26
I cannot reproduce this result in terser playground, and this contradicts to my knowledge of terser inline pass -- it has basically no support for inlining functions with multiple usage.

**Comment by kdy1** [comment] 2022-08-31 13:32
Oh, my bad.
It was https://github.com/vercel/styled-jsx/blob/41443ab141fb2f2382ceaf8d8896d0e1b7644987/src/stylesheet-registry.js and it was inlined as a single-usage

**Comment by Austaras** [comment] 2022-08-31 13:41
This is still a valid issue though -- and would indeed be fixed by #5607

**Closed** 2022-09-01 10:36 UTC
Labels: enhancement, A: ES minifier
