### ISSUE TITLE
Redeclaration of block scoped variables when bundling

### ISSUE THREAD

**Issue by kitsonk** [swc-project/swc#1912] opened 2021-07-12 10:26 UTC
**Describe the bug**

Block scope variables being incorrectly re-declared when bundling in Deno. (see: denoland/deno#11354)

**Input code**

https://github.com/vovacodes/try-deno-bundler

**Expected behavior**

To know have top level variable being declared with the same name.

**Version**

- Deno 1.11.5
- swc_bundler 0.45.0
- swc_common 0.10.23
- swc_ecmascript 0.45.0

**Comment by kdy1** [comment] 2021-07-15 11:17
Cannot reproduce using react / react-dom from npm.

Generated output is https://github.com/swc-project/swc/blob/c574303cc4cc1159cf08ad8172d207c1eeef0d44/bundler/tests/fixture/issue-1912/case1/output/entry.inlined.tsx

**Comment by vovacodes** [comment] 2021-07-19 07:40
@kdy1 The problem is `react` from npm is slightly different than the one served from jspm, as the latter converts it from commonjs to esm. That conversion is verifiable to be correct as you can easily import it in the browser (I tried, it works). So I can totally imagine that the repro doesn't work in your case.

Let me know if you would like me to submit a failing test to swc that mimics the exact setup I have in my Deno repro repository

**Comment by kdy1** [comment] 2021-07-19 07:42
It would be very helpful :)
Thank you!

**Comment by kdy1** [comment] 2022-03-12 08:29
I think this is fixed by https://github.com/swc-project/swc/pull/3824

**Closed by kdy1** 2022-03-12 08:29 UTC
Labels: C-bug
