### ISSUE TITLE
Import assertions are skipped when transpiled from TS to JS

### ISSUE THREAD

**Issue by andreubotella** [swc-project/swc#3110] opened 2021-12-24 12:05 UTC
### Describe the bug

Import assertions affect whether a module is valid in the module graph, depending on the JS runtime, and so should not be stripped when transpiling.

### Input code

```typescript
import data from "./test.json" assert { type: "json" };

console.log(data);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.122&code=H4sIAAAAAAAAA8vMLcgvKlFISSxJVEgrys9VUNLTL0ktLtHLKs7PU1JILC5OBUpXK5RUFqRaKShBRGutubiS8%2FOK83NS9XLy0zVAujWtAVSAl05LAAAA&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FsWLLnKHHsK4SnDxD40CDcZ3rx1cspNmnp4qfeBorVSsgGVMOJPaL62kZ2E48UVpIUWPNhvArS9WdtaOMMzDmF6HnMETWCj65LdzyFyORRi4K5v28Cdbd8X8PkZQr3%2BX80ntdsw7j9cEVQ5uPx%2Bqcl%2B4AAAA

### Expected behavior

```js
import data from "./test.json" assert { type: "json" };
console.log(data);
```

### Actual behavior

```js
import data from "./test.json";
console.log(data);
```

### Version

1.2.122

**Comment by kdy1** [comment] 2021-12-25 09:56
Closing as duplicate of https://github.com/swc-project/swc/issues/2802

**Closed by kdy1** 2021-12-25 09:56 UTC
Labels: C-bug

**Comment by wycats** [comment] 2022-05-29 18:42
@kdy1 It seems like the solution in #2802 involved a new flag that only applies to the ECMAScript parser.

Also, maybe I'm doing something wrong, but when I attempted to add the flag to the example in the playground in the JSON editor (after updating the version to the latest available version and switching to ECMAScript), it still seems to strip it out.

**Comment by kdy1** [comment] 2022-05-30 06:00
@wycats TypeScript supports it unconditionally. https://github.com/swc-project/swc/blob/7407f218f8b294d3d7998334bdd908abc519ecb0/crates/swc_ecma_parser/src/lib.rs#L167-L174

**Comment by kdy1** [comment] 2022-05-30 06:03
Also, I tested and import is stripped out because imported identifier isn't used.
See https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA8vMLcgvKlFQ19NPy8xJ1csqzs9TV0gsLk4FClYrlFQWpFopKIFElRRqAUUfytcsAAAA&config=H4sIAAAAAAAAA02PsW7DMAxE%2F4VzhjZDB28FOiRDPkJQz4YaSRRIprBh%2BN9LOQbSTRTvHu9W%2BtFIw0otiEL6S5dqYaaBbGnQKKkZncjUv8aQFZsPQSaYS6Dnt%2FO7rzOzggaTB05UUk3j0lmRSxOoHlZfhTpl%2FCNJqDqylK7OmEJcvhBZgrE8cS7CbJAa8gW5QV4wzD6mAs%2Bbu%2F8OtGtpLPapXsYSVz0gTin8%2Fein173YHv6DtlfaA5r0dgifZVB%2Fd89e2XFE2%2FYHgsdGZDYBAAA%3D


This is related to preserving imports not used as value

**Comment by wycats** [comment] 2022-06-21 16:56
Great! Consider this solved.

I'm not sure why it was causing me trouble in my real app (it wasn't this problem), but I can dig in if I reproduce it again.
