### ISSUE TITLE
CLI install on MacOS with Apple Silicon

### ISSUE THREAD

**Issue by OskarLebuda** [swc-project/swc#9018] opened 2024-06-03 22:35 UTC
### Describe the bug

Hello,
While installing the cli using https://swc.rs/docs/plugin/ecmascript/getting-started got an error:
```
error[E0599]: no method named `atom` found for reference `&swc_ecma_ast::ModuleExportName` in the current scope
   --> /Users/USER_NAME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_ext_transforms-0.114.2/src/jest.rs:110:68
    |
110 | ...                   if HOIST_METHODS.contains(exported.atom()) {
    |                                                          ^^^^ method not found in `&ModuleExportName`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `swc_ecma_ext_transforms` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `swc_cli v0.91.267`, intermediate artifacts can be found at `/var/folders/h5/2jkfqhw915ggtj52qf5l3n9w0m_69t/T/cargo-installHZTIM9`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

#### rustc

```
$ rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)
```

#### rustup

```
$ rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```

#### cargo

```
$ cargo --version
cargo 1.78.0 (54d8815d0 2024-03-26)
```

### System profile:
```
Software:
      System Version: macOS 14.5 (23F79)
      Kernel Version: Darwin 23.5.0

Hardware:
      Model Name: MacBook Pro
      Chip: Apple M2 Pro
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 32 GB
      System Firmware Version: 10151.121.1
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.5.24&code=H4sIAAAAAAAAA1WNMQ7CMAxFd5%2FCY3OFdqlgYmPgAk7qSiATR7ErFVW9eyMEQvzxf73%2Fxkt%2BcHKKwl0AXotWxyRkhjc2P%2BuzaObsyKtzngxPZPxrNwBsGa9VS7fhxDMt4j3OJMa4h%2Fdalij3hN7%2BeoyqwpQHgB2%2Bvg%2FWqORaX92fOQxwAFAhVQmlAAAA&config=H4sIAAAAAAAAA2WPSw7CMAxE9z1F5TULYIEEd%2BAQUepWQc1HtisRVb17kzYNIHbxvHjGMzdtCy%2FW8Gjn9ExDUMRIdU4KRyfqnRSQGJA1mSBwOqhwRr0aGavWofakxBMnJDThBpadgygaULIf8vV8uRcvGL1n%2FPUCa5zp4%2Fc12ttAyPwXapUbxrq%2FJzYlFazvpg2WlrnJfsENPp%2BOsGoMhp%2FH5tZjWQEa0ouIMQEAAA%3D%3D

### Expected behavior

fix the code

### Version

newest

**Comment by kdy1** [comment] 2024-06-04 00:09
Should be fixed by https://github.com/swc-project/swc/commit/2fb890cf2019039d3881ddb9c4ce12ca9b1239b7

**Comment by OskarLebuda** [comment] 2024-06-04 04:59
> Should be fixed by [2fb890c](https://github.com/swc-project/swc/commit/2fb890cf2019039d3881ddb9c4ce12ca9b1239b7)

@kdy1 
What you mean "should". I'm new in the "rust world". This requires some kind of release or something?

**Comment by OskarLebuda** [comment] 2024-06-04 05:15
After cleaning some caches got another error
```
35.46 error[E0599]: no method named `is_reserved_in_any` found for struct `swc_ecma_ast::Ident` in the current scope
35.46    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_compat_es2022-0.5.2/src/class_properties/private_field.rs:592:21
35.46     |
35.46 592 |             if n.id.is_reserved_in_any() {
35.46     |                     ^^^^^^^^^^^^^^^^^^
35.46     |
35.46 help: there is a method `is_reserved` with a similar name
35.46     |
35.46 592 |             if n.id.is_reserved() {
35.46     |                     ~~~~~~~~~~~
35.46 
35.71 error[E0599]: no method named `is_reserved_in_any` found for struct `swc_ecma_ast::Ident` in the current scope
35.71    --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_compat_es2022-0.5.2/src/class_properties/mod.rs:806:50
35.71     |
35.71 806 | ...                   if method.key.id.is_reserved_in_any() {
35.71     |                                        ^^^^^^^^^^^^^^^^^^
35.71     |
35.71 help: there is a method `is_reserved` with a similar name
35.71     |
35.71 806 |                                 if method.key.id.is_reserved() {
35.71     |                                                  ~~~~~~~~~~~
35.71 
35.72    Compiling swc_ecma_transforms_optimization v0.199.2
35.86 For more information about this error, try `rustc --explain E0599`.
35.86 error: could not compile `swc_ecma_compat_es2022` (lib) due to 2 previous errors
35.87 warning: build failed, waiting for other jobs to finish...
59.85 error: failed to compile `swc_cli v0.91.269`, intermediate artifacts can be found at `/tmp/cargo-installEbFi2I`.
59.85 To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by LukasGerm** [comment] 2024-06-07 11:53
I can also reproduce this exact error on windows. What shall we do to go past this error?

**Comment by kdy1** [comment] 2024-06-07 12:13
Fixed
<img width="1840" alt="image" src="https://github.com/swc-project/swc/assets/29931815/517b69a0-1d9c-42bb-b393-a99244482b35">

**Closed by kdy1** 2024-06-07 12:13 UTC
Labels: C-bug

**Comment by LukasGerm** [comment] 2024-06-07 12:23
Do we need to use a newer version of swc_cli then? Or how does it work now? Because I can still reproduce? @kdy1

**Comment by LukasGerm** [comment] 2024-06-07 12:38
Can confirm it works now with the new version.
