### ISSUE TITLE
jsc.paths didnt work when file is not on root 

### ISSUE THREAD

**Issue by aelbore** [swc-project/swc#2126] opened 2021-08-21 07:04 UTC
**Describe the bug**
jsc.paths didnt work when file is not on root folder

**Input code**
File => `packages/a/src/index.ts`
code => 
```typescript
export function displayA() {
  return 'Display A'
}
```

File => `src/index.ts`
```typescript
import { displayA } from '@print/a'

console.log(
  `${displayA()}`
)
```

File => `package.json` 
```json
{
  "name": "swc-tsconfig-paths",
  "main": "index.ts",
  "scripts": {
    "swc": "swc-node ./src/index.ts",
  },
  "devDependencies": {
    "@swc/core": "^1.2.80",
    "@swc/register": "^0.1.7"
  }
}
```

Error
![image](https://user-images.githubusercontent.com/18069807/130313711-f1052416-f753-46fe-a77c-c59a2778eb83.png)

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "paths": {
      "@print/a": [ "packages/a/src/index.ts" ],
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Expected behavior**
Should work properly and recognise the paths

**Version**
The version of @swc/core: 1.2.80

**Additional context**

**Comment by kdy1** [comment] 2021-08-21 07:05
Seems like duplicate of https://github.com/swc-project/swc/issues/2050

**Comment by aelbore** [comment] 2021-08-21 07:08
@kdy1 sure thanks apologies i didnt see it,
by the way if you put the `src/index.ts` to root folder `index.ts` in your package.json `swc-node index.ts` >>> it works as expected

**Comment by aelbore** [comment] 2021-09-18 14:16
@kdy1 this works if you set `baseUrl` to `src` then adjust the paths 
Maybe its a matter of adjusting the `baseUrl`

This does not work
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "baseUrl": ".",
    "paths": {
      "@print/a": [ "./packages/a/src/index.ts" ]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

This will works 
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "baseUrl": "./src",
    "paths": {
      "@print/a": [ "../packages/a/src/index.ts" ]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

**Comment by aelbore** [comment] 2021-09-18 14:20
@kdy1 another thing is if you set the `type` to `module` in the `package.json`  it will not work

**Comment by aelbore** [comment] 2021-09-18 15:51
@kdy1 I know now, the `baseUrl` should be where the code will use, then the `paths` should adjust to the baseUrl <strong>`dynamically`</strong>

for example
if i add a folder in the `src/folder-b` the `baseUrl` should be `src/folder-b`

**Comment by kdy1** [comment] 2021-09-19 11:46
@aelbore Current implementation uses `baseUrl`, and `paths` is adjusted based on it.
It sounds like the current implementation is correct, but I don't think it's the case.

**Closed** 2021-11-11 07:57 UTC
Labels: C-bug
