### ISSUE TITLE
parse ts error when use <type>xxx()

### ISSUE THREAD

**Issue by konicyQWQ** [swc-project/swc#5461] opened 2022-08-12 09:14 UTC
### Describe the bug

https://www.typescriptlang.org/play?jsx=0&ts=4.8.0-beta#code/MYewdgzgLgBArgJwDYEU4FMEE8IwLwwA80CAlmAOYB8F6UamWAFAJQDcQA

ts playground is ok.
swc error.

### Input code

```typescript
const urlQuerys = <string>getQuery();
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.225&code=H4sIAAAAAAAAA0vOzysuUSgtygksTS2qLFawVbApLinKzEu3S08tAYtpaFoDADYIoGwlAAAA&config=H4sIAAAAAAAAA0WNQQrDMAwE%2F6JzDiFH%2F6GPEI4SXBzbaBWICf577dKS27Iz7N70hid3U2GF6EioyfgiR1aLwGsoRhMZemV6SuuZdRfrhmCZl7nTmDOE3MYRMtERUtjq2PL5KCrAgzjt8W%2B29rg%2FHvDK6zmM79cH6XoiTp8AAAA%3D

### Expected behavior

parse correct

### Version

1.2.225

**Comment by kdy1** [comment] 2022-08-12 09:15
Closing as this is not a bug
https://www.typescriptlang.org/play?ts=4.8.0-beta#code/MYewdgzgLgBArgJwDYEU4FMEE8IwLwwA80CAlmAOYB8F6UamWAFAJQDcQA

**Closed by kdy1** 2022-08-12 09:15 UTC
Labels: C-bug
