### ISSUE TITLE
SWC transpiles optional chaining even tho it shouldn't

### ISSUE THREAD

**Issue by danieltroger** [swc-project/swc#1922] opened 2021-07-15 10:09 UTC
**Describe the bug**

Possible regression of https://github.com/swc-project/swc/issues/1704 ?
SWC transpiles optional chaining for node, even when setting target to latest node which supports optional chaining.

**Input code**

```
globalThis?.hello?.world?.("sup?");
```

Current output code:
```
var ref, ref1;
globalThis === null || globalThis === void 0 ? void 0 : (ref = globalThis.hello) === null || ref === void 0 ? void 0 : (ref1 = ref.world) === null || ref1 === void 0 ? void 0 : ref1.call(ref, "sup?");

```

**Config**

```json
{
  "env": {
    "shippedProposals": true
  }
}
```

```
"browserslist": "node >=16.4.2",
```

**Expected behavior**

```
globalThis?.hello?.world?.("sup?");
```
**Version**
The version of @swc/core:
```
@swc/cli: 0.1.46
@swc/core: 1.2.64
```
**Additional context**
Idk but it feels like not transpiling it might be faster at runtime

Repro .zip:
[swc-optional-chaining.zip](https://github.com/swc-project/swc/files/6822259/swc-optional-chaining.zip)

**Comment by kdy1** [comment] 2021-08-09 18:38
It's caused by https://github.com/babel/babel/blob/main/packages/babel-compat-data/data/plugins.json not containing proper node version of `proposal-optional-chaining`.
I'm not sure where should I get the compat data.

**Comment by danieltroger** [comment] 2021-08-28 13:33
> I'm not sure where should I get the compat data.

@kdy1 from here: https://github.com/mdn/browser-compat-data/blob/main/javascript/operators/optional_chaining.json#L68>

**Comment by Austaras** [comment] 2021-12-08 07:28
[It does now](https://github.com/babel/babel/pull/13949)

**Comment by kdy1** [comment] 2021-12-20 01:44
Closing as fixed by https://github.com/swc-project/swc/pull/3072

**Closed by kdy1** 2021-12-20 01:44 UTC
Labels: C-bug
