### ISSUE TITLE
Cannot serialize the AST with serde_json::to_string

### ISSUE THREAD

**Issue by cllu** [swc-project/swc#8065] opened 2023-10-05 02:29 UTC
### Describe the bug

First thanks for the amazing project! I'm working on a Python wrapper for swc to parse a Javascript code and output AST into JSON format. However, I'm having issues with the serialization `serde_json::to_string` at [here](https://github.com/cllu/pyswc/blob/6cc5e63d1d0c75c4dfabc488b8e4911f92b6b495/src/lib.rs#L69). Rust keeps complaining that `serde::ser::Serialize` is not implemented for `swc_ecma_ast::Program`, but from my understanding we should be able to use serde and there is test cases in the code base. I'm new to Rust so there might be some easy things I'm missing. The code is in https://github.com/cllu/pyswc/blob/main/src/lib.rs.

```
error[E0277]: the trait bound `swc_ecma_ast::Program: serde::ser::Serialize` is not satisfied
    --> src/lib.rs:69:48
     |
69   |         let serialized = serde_json::to_string(&program.unwrap());
     |                          --------------------- ^^^^^^^^^^^^^^^^^ the trait `serde::ser::Serialize` is not implemented for `swc_ecma_ast::Program`
     |                          |
     |                          required by a bound introduced by this call
     |
     = help: the following other types implement trait `serde::ser::Serialize`:
               bool
               char
               isize
               i8
               i16
               i32
               i64
               i128
             and 238 others
note: required by a bound in `serde_json::to_string`
```

### Playground link (or link to the minimal reproduction)

https://github.com/cllu/pyswc/blob/main/src/lib.rs

### Expected behavior

I'd like to use `serde` to serialized AST into JSON string.

### Version

latest

**Comment by kdy1** [comment] 2023-10-05 02:43
Closing as this is not a bug of SWC and rather it's about not understanding cargo.

**Closed** 2023-10-05 02:42 UTC
Labels: C-bug

**Comment by cllu** [comment] 2023-10-05 03:15
Thanks for pointing that out. I was missing the `features=["serde-impl"]` for the `swc_ecma_ast` package.

```toml
swc_ecma_ast = {version = "0.109.1", features=["serde-impl"]}
```
