### ISSUE TITLE
Eval breaks imports

### ISSUE THREAD

**Issue by Smrtnyk** [swc-project/swc#6070] opened 2022-10-06 09:30 UTC
### Describe the bug

Seems like eval used in a function, even if the function is never used, breaks imports in the file.
Here is the repro repository
https://github.com/Smrtnyk/swc-modules-import-repro

clone it, run `npm install` and then `npm run transpile`

I have put a break point and seems like only one import is considered

if you remove the `evaluatedCodeWrapper` function from the code, then it works again
seeems like problem is the `eval.call` line

This is blocking our upgrade of swc 1.197 to 1.3.4

### Expected behavior

eval.call in unused function should not break imports

### Version

1.3.4

**Comment by kdy1** [comment] 2022-10-06 09:37
Please fill the input forms. Also, please provide a repro case which does not involve 3rd-party library

**Comment by Smrtnyk** [comment] 2022-10-06 09:50
@kdy1 I have updated the repro
you just need to clone, npm install and do npm run transpile
it uses @swc/cli
you can see in transpiled output two same variables called `_config`

for the inputs forms, you want me to put in the code content from the repro?

**Comment by kdy1** [comment] 2022-10-06 10:07
Closing as duplicate of https://github.com/swc-project/swc/issues/5068

**Closed by kdy1** 2022-10-06 10:07 UTC
Labels: C-bug, Need more info
