### ISSUE TITLE
Comments on types are stripped

### ISSUE THREAD

**Issue by cdaringe** [swc-project/swc#2964] opened 2021-12-04 00:05 UTC
### Describe the bug

Comments are stripped due to unknown reasons, against expectation.

### Input code

```typescript
// FILE bad.ts:

/* istanbul ignore next */
type Z = number;
x = 1;


// FILE good.ts
/* istanbul ignore next */
x = 1;
```

### Config

```json
{
  "jsc": {
    "transform": {}
  },
  "swcrc": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.117&code=H4sIAAAAAAAAAzXMOwrAIBBF0d5VvFoCklqykXQahjigY4hjPruPTdpz4ToLbhok9gzepZ4EoUdhnXEO%2Bh6EFQukl0inx7AuWy2FRKGJGzILTbiDbmkA4Y8h1otwBeGWzDMWszcfPlBa620AAAA%3D&config=H4sIAAAAAAAAA6tWys3My0yrVLJKS8wpTtVRyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpRqa2sBrzFAMDkAAAA%3D

### Expected behavior

`bad.ts` should emit:

```
/* istanbul ignore next */
x = 1;
```

but does emit:

```
x = 1;
```

dropping the istanbul comment

### Version

1.2.117

**Comment by kdy1** [comment] 2021-12-04 02:01
Seems like the comment is on type alias and the type node is removed.

**Comment by kdy1** [comment] 2021-12-04 02:02
@kwonoj Any thoughts? Do you think we should preserve the comment on type nodes?

**Comment by kwonoj** [comment] 2021-12-04 02:06
In my opinion this is somewhat undefined behavior, there's no clear expectation. 

i.e tsc stiprs comment out 
![image](https://user-images.githubusercontent.com/1210596/144693053-239fa37e-efa7-4e4e-96bf-bb1ac60d66b4.png)

while babel preserves it. If we're aiming for babel's model probably better to mimic babel's behavior but even in that case I'd consider this is improvement, not a bug.

**Comment by cdaringe** [comment] 2021-12-04 03:27
TS has a compiler flag, removeComments, to  control the behavior

**Comment by kdy1** [comment] 2021-12-04 03:34
I think removal of comment is expected, because the comment is on type definition.

**Comment by kwonoj** [comment] 2021-12-04 03:40
@cdaringe That doesn't apply for this case, what @kdy1 says is correct. Even if you set `removeComments: false`, tsc strips comments along with type definition: https://www.typescriptlang.org/play?removeComments=false#code/PQKgBAlgzgLghgOwEYFcA2kDmCD2AnAUzAQIA8YwRgAoGATwAciAtMAXmJQFskC8BuamgIVS7MAEZ+QA

Locally verified it as well.

My take is still same, I'd consider this as improvement if we want to support.

**Comment by dpchamps** [comment] 2021-12-06 17:37
It's worth mentioning that currently the behavior is not 1:1, take a look at @kwonoj's example but with a newline: https://www.typescriptlang.org/play?&removeComments=false#code/PQKgBAlgzgLghgOwEYFcA2kDmCD2AnAUzAQIA8YwRgAoamATwAciAtMAXmJQFskC8A3NTQEKpDmACMAoA

This emits the comment as expected.

**Comment by kwonoj** [comment] 2021-12-06 18:29
Yes, that's known - while issue is different, this comments explains it:

https://github.com/microsoft/TypeScript/issues/26079#issuecomment-409294656

> Comments at the beginning of a line followed by a new line are considered "unattached", and these are preserved,

While SWC doesn't do strictly distinguish comment attachment in this case. 

But also, if desire is let comment directive to work for given statement for this specific case, since actual line's already strippted not sure what those comment supposed to do here.

**Comment by DawChihLiou** [comment] 2021-12-09 06:39
Just to provide a visual to @kwonoj 's comment. Please see [this TS Playground](https://www.typescriptlang.org/play?&removeComments=false#code/DYUwLgBAnhELywMwG4BQqD0AqCBLAzmAIYB2ARgK7B4DmJA9gE4gQkgAekWG6YUADiwBa8VhQC2ZEIzShI7UQEZkQA).

```ts
let y  =  3;

/* istanbul ignore next */

type Z = number;
let x = 1;
```
is compiled into:

```ts
"use strict";
let y = 3;
let x = 1;
```

The comment above the type statement is stripped.

**Comment by joshyudeep** [comment] 2021-12-15 21:46
Has anyone found a workaround for this? Is there a setting on .swcrc config or .tsconfig that can prevent `/* instabul ignore next*/` type comments from being stripped? 

We're trying to migrate from ts-jest to @swc/jest and we have 100% coverage requirement... 🙏  Any help much appreciated.

**Comment by cdaringe** [comment] 2021-12-15 21:54
@dpchamps wrote a jest plugin that tests for the comment, calls into this swc/jest, then reinjects the comment before handing off jest. it's imperfect, but gets us most of the way there

**Comment by joshyudeep** [comment] 2021-12-15 22:08
> @dpchamps wrote a jest plugin that tests for the comment, calls into this swc/jest, then reinjects the comment before handing off jest. it's imperfect, but gets us most of the way there

Can you link me to the plugin? 🙏

**Comment by dpchamps** [comment] 2021-12-16 01:33
@joshyudeep the project is unfortunately closed source. However, the idea is easily communicated:

```javascript
const wrapTransformer = (swcOptions) => {
  const swcTransformer = createSwcTransformer(swcOptions);
  return {
    ...swcTransformer,
    process: (src, filename, jestOptions) => {
      const result = swcTransformer.process(src, filename, jestOptions);

      /**
        * search the contents of the file for a file-level istanbul-ignore
        * e.g. `istanbul ignore file`
        * if found, append the ignore text to the bottom of the file
        **/
      if(containsFileLevelIstanbulDirective(src, result)){
           return appendIstanbulIgnoreFile(result)  
      }

     return result;
    },
  };
};

module.exports = {
  createTransformer: wrapTransformer
}
```

Basically just a heuristic based on the observation that this bug only impacts comments attached to type nodes. 

Assuming that`/* istanbul ignore <token> */` should never precede types, and if they do can always be moved to the appropriate position so that they're not stripped without an impact to coverage. Therefore, the only ignore valid comments that can be stripped are file-level directives. In which case, we can put them at the bottom of the file after the transformation.

**Comment by kdy1** [comment] 2021-12-16 06:21
Special handling of `istanbul ignore` is out of scope while preserving comments is in the scope of the project.
I think handling tool-specific comments is a hack and I'll reject such patches.

**Comment by joshyudeep** [comment] 2021-12-16 11:46
> Special handling of `istanbul ignore` is out of scope while preserving comments is in the scope of the project. I think handling tool-specific comments is a hack and I'll reject such patches.

Thanks for the quick response. I think as long as comments can be preserved then there's a workaround for this type of situation.

**Comment by dpchamps** [comment] 2021-12-16 16:21
@kdy1 yep thats fair. It's a total hack, but this will help you @joshyudeep in the interim

**Comment by joshyudeep** [comment] 2021-12-16 16:33
> @kdy1 yep thats fair. It's a total hack, but this will help you @joshyudeep in the interim

Thanks for the suggestion.. Look like your suggested wrapper only deals with `/* istanbul ignore file */` comments, how did you go about handling `/* istanbul ignore next/else/if */` comments? Looks like .swcrc compiler strips all kinds of comments during transformation.

**Comment by joshyudeep** [comment] 2021-12-16 17:54
@kdy1 I'm assuming there's currently not a config option as a workaround for this (disabling removing of comments). Do you have a rough estimate as to when this functionality would be worked on / released? Trying to see whether it'd be worth the time to come up with my own custom solution in the interim. 

Thanks! Also, much appreciate all that you (swc contributors) have put into this project, our test suites are running 5x faster with @swc/jest.

**Comment by kwonoj** [comment] 2021-12-16 18:02
I'd suggest to go with workaround. We'll eventually have this but there's no promised timeline or eta to provide.

**Comment by dpchamps** [comment] 2021-12-16 18:59
@joshyudeep, sorry my explanation probably wasn't clear 😅 : 

This case only practically affects comments that are dropped when they precede types and import statements. Types and import statements don't impact coverage, therefore`/* istanbul ignore <token> */` comments _shouldn't ever_ precede a type or an import statement (afaik). If they are, they can be adjusted to precede the particular code block you're actually trying to omit from coverage.

That leaves you with one remaining case: file-level istanbul directives. That's what this workaround solves.

**Comment by joshyudeep** [comment] 2021-12-16 19:55
> Comments are only dropped when they precede types and import statements. 

@dpchamps thanks for the follow up -- I don't think I completely follow cause I don't think the above assumption is true. Check out [this playground](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA3XMQQqAIBBG4f2c4t%2BVLhLX0mEqJhEGpVQQortn%2B9p%2F7xmNkMsS1yoIPqaTEbkVaENbirmgYYZ1ROYXgsKOsbu5S4WLgDdNwpMkPw4NfNRFMuygHN2fqz0I99UDHqA1fo4AAAA%3D&config=H4sIAAAAAAAAA0WNSw7DIAxE7zJrFm2lbrhDD4GoExHxE3akIMTdC1Xa7GzPvOeG4KJbKvRiPJPCxha6IZvCVObENYo5oCE1E9viskBB%2BDiRruBTYvobfsIGm0IuxHxFJq6eLlBMWUmGm%2Fhxuz8xTo5f6b3PkpR9IufWvv9HdUhDihuj9w9ukbgKvQAAAA%3D%3D) where all comments are stripped out except the last comment that's at the EOF.

**Comment by dpchamps** [comment] 2021-12-16 20:38
@joshyudeep 

> Is there something I'm missing?

[note the negative look ahead :)](https://regex101.com/r/y1GGIA/1)

also, [compiler settings matter](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA3XMQQqAIBBG4f2c4t%2BVLhLX0mEqJhEGpVQQortn%2B9p%2F7xmNkMsS1yoIPqaTEbkVaENbirmgYYZ1ROYXgsKOsbu5S4WLgDdNwpMkPw4NfNRFMuygHN2fqz0I99UDHqA1fo4AAAA%3D&config=H4sIAAAAAAAAA6tWys3My0yrVLJKS8wpTtVRyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpRqa2sBrzFAMDkAAAA%3D)

**Comment by kdy1** [comment] 2021-12-16 20:47
Comments are not removed. Those are simply not printed because the node which the comments are for is not printed as it's removed.

**Comment by kdy1** [comment] 2021-12-16 20:47
Also, I don't have any estimate and I don't think I will work on this.

**Comment by dpchamps** [comment] 2021-12-16 20:55
@kdy1 , yes -- it's clear to me why the comments are not emitting from the final output. Which I'll summarize here. Please correct me if I'm wrong:

- Preserving comments is not part of the ECMA spec, they don't get AST nodes
- SWC associates comments with ast nodes in order to preserve them through the compilation process
- In the event where the AST node is dropped during compilation, the comment is also dropped.

I actually have some interest in working on a holistic solution for this. Would you be open to a patch? I have some PTO coming up, and am already pretty familiar with the SWC codebase.

**Comment by kdy1** [comment] 2021-12-16 21:00
I'm open to patch, but please add a flag to enable moving of comments.

I think preserving comments of dropped nodes is counter-intuitive

**Comment by dpchamps** [comment] 2021-12-16 22:31
@joshyudeep I realized that my partial pseudo-code demonstrating the workaround may have been confusing. Here's a working example: https://github.com/dpchamps/swc-jest-wrapper-example

**Comment by joshyudeep** [comment] 2021-12-16 23:18
> @joshyudeep I realized that my partial pseudo-code demonstrating the workaround may have been confusing. Here's a working example: https://github.com/dpchamps/swc-jest-wrapper-example
> 
> Feel free to play around with it, lmk if it works for you.

Thanks for the example. much appreciated. I found that these uses of `istanbul ignore next` are failing as well 😢; 
[Here's the config for the example below](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA23OzQqCQBRA4f08xd35Q80QEUFiqzbu2vQAo3OTgetccUYTxHcvwaDA%2FQfnCKXA%2BqBd2RPY2nGH4HAMAseWuwAVOx%2Bg1Kb4ohzigD4kkF9hErCKCQZNPe5AStnaEemuO914mD9%2B4dkqmVAS13H01JaiJBNzJoRKNx8u8Cj2p8PxDKn6%2FzH8csTa3LjqG3RhmUouMLA1v1sbsTcOsRGo8AAAAA%3D%3D&config=H4sIAAAAAAAAA02QzU7DMBCE32XPEQIkOPQIAtEDHHiDlTNpU%2Fyn3U2bqMq7Y6dt4OKf2dF8Y59J0yAOn5yVNiYDGgqpHTxocyabctkJ%2BkxzQwd1VcwsCqknnaLxWAzVp076bNSQ6XhLaqfIoXfbkJPYKsIlYUtSgB17RYk24ahdklBjBexsIQnvApf876rcuTIwvHkExAq6jN%2FLulrq5Tq1vaTTtvviAM3s8Ic%2Fwqe8uC78hgbFy9B76%2BO%2FTvu%2BbRFrjwP02n6uXVl2sOVbHu8fngrKp6RYwzAaJLL%2FgM9YH9nQD5BfPasulW6c%2BRfio4FQggEAAA%3D%3D)

```typescript
// istanbul ignore next
export const badIstanbul = (test) => {
  const { value, ...pixelParams } = test;
  console.log('fail');
};

/* istanbul ignore next: UI-5137 */
export const downloadDocument = (): void => {
  console.log('fail');
};
```

**Comment by dpchamps** [comment] 2021-12-16 23:33
@joshyudeep [Those examples work fine](https://github.com/dpchamps/swc-jest-wrapper-example/blob/main/src/example.ts). See coverage:
![Screen Shot 2021-12-16 at 3 30 24 PM](https://user-images.githubusercontent.com/2519820/146464219-763eb617-ca98-453c-8cd3-06c3e1ee6517.png)

However, it might be a bit off topic to go back and forth in this thread with specific examples.

**Comment by joshyudeep** [comment] 2021-12-17 03:03
> However, it might be a bit off topic to go back and forth in this thread with specific examples.

@dpchamps good point -- I've created a separate issue in the example repo you posted. 🙏 👍 
https://github.com/dpchamps/swc-jest-wrapper-example/issues/1#issue-1082833066

**Comment by joshyudeep** [comment] 2021-12-18 18:32
> Comments are not removed. Those are simply not printed because the node which the comments are for is not printed as it's removed.

@kdy1 just wanted to double check that this is intended functionality. @swc/jest defaults to exporting to module `type: commonjs` so for the following chunk of code, all of the comments outside of function declarations are removed. But when you export with module `type: 'es6'` the comments remain. Is that in line with your quoted comment above? 

cc: @dpchamps @kwonoj

**Original source code**
```js
/* istanbul ignore file */

export const badIstanbul = () => {
    return 1;
};

// istanbul ignore next
export const downloadDocument = () => {
    return 2;
};

/* istanbul ignore next */
export const downloadDocumentTwo = () => {
    /* istanbul ignore next */
    return 3;
};
```

**commonjs conversion** [playground link](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA33OsQrCQBAE0H6%2FYkpNc6hliJWNvT9wya0SOHflskcC4r9rREGNZOrhzZAr0Hbmpc4R7Uk0MY5tZBSOiIeLJkOj0hlqH%2FbvYoXFEtUWV8IjiS0nwaqkW0nk3AQUHuwbC9pLVB922uQzi%2F0X1y9xenEUx4uz6KHXH3dG%2BpjdPGfv2sFdjxoBAAA%3D&config=H4sIAAAAAAAAAy2NwQ7DMAhD%2F4Vzr7vkH%2FoRKKNTqyZEmEirqv77QNrNz8bmJui0KisPUHGbstCBSuWmwQaxVLi685cK%2BTUE1fbhtJAjrI1PyBNg3LGptbhPZPuIR0PwouCm73lKbuVE%2BFVb034gwx3rP87%2Fzw9gRirakwAAAA%3D%3D)
```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.downloadDocumentTwo = exports.downloadDocument = exports.badIstanbul = void 0;
var badIstanbul = function() {
    return 1;
};
exports.badIstanbul = badIstanbul;
var downloadDocument = function() {
    return 2;
};
exports.downloadDocument = downloadDocument;
var downloadDocumentTwo = function() {
    /* istanbul ignore next */ return 3;
};
exports.downloadDocumentTwo = downloadDocumentTwo;
```

**ESM conversion (`type: 'es6'`)** [playground link](https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA33OsQrCQBAE0H6%2FYkpNc6hliJWNvT9wya0SOHflskcC4r9rREGNZOrhzZAr0Hbmpc4R7Uk0MY5tZBSOiIeLJkOj0hlqH%2FbvYoXFEtUWV8IjiS0nwaqkW0nk3AQUHuwbC9pLVB922uQzi%2F0X1y9xenEUx4uz6KHXH3dG%2BpjdPGfv2sFdjxoBAAA%3D&config=H4sIAAAAAAAAAy2NQQ6DMAwE%2F7Jnru0hf%2BARVmoQFZDI60ggxN8bV9w8s%2Fb6AkuzrKNUIrk1HfBlRrpQxagWE8%2Fd5UCCn1WZbamOAc6uJlmpdweTnVOxre8His3q%2FUL5QuetfNqq0RUVf%2F8Ov3B8knh9%2FwAniElljgAAAA%3D%3D)
```js
/* istanbul ignore file */ export var badIstanbul = function() {
    return 1;
};
// istanbul ignore next
export var downloadDocument = function() {
    return 2;
};
/* istanbul ignore next */ export var downloadDocumentTwo = function() {
    /* istanbul ignore next */ return 3;
};
```

**Comment by kdy1** [comment] 2021-12-18 18:33
Yeah I think so

**Comment by longlho** [comment] 2021-12-22 16:52
would it be possible to just capture comments as a list of `CommentLine` nodes as babel does it?

**Comment by kdy1** [comment] 2021-12-22 16:57
@longlho No

**Comment by longlho** [comment] 2021-12-22 17:00
is that a technical limitation or resourcing limitation?

**Comment by kdy1** [comment] 2021-12-22 17:04
What's resourcing limitation?

**Comment by kdy1** [comment] 2021-12-22 17:05
It's technical,

**Comment by longlho** [comment] 2021-12-22 17:12
To be clear I'm not specifically asking for emitting/preserving comment nodes, but rather parsing them into AST so plugins can use them for static analysis/directives.

**Comment by kdy1** [comment] 2021-12-22 17:18
It's not possible and I'll reject PRs doing so

**Comment by longlho** [comment] 2021-12-22 17:30
Can you elaborate? I'm reading through the thread and wasn't able to see the technical limitations other than lack of spec

**Comment by kdy1** [comment] 2021-12-22 17:52
Adding a field for comment to all node is simply not acceptable.

**Comment by longlho** [comment] 2021-12-22 18:08
hmm no that's not what I meant. I meant like https://astexplorer.net/#/gist/5523e56fe73439101ec0d38e43734dd7/9d2d9e5dea8587085ada67d1a731785783eb7cd4 where `comments` is a field on `File` node that has a list of `CommentLine`s

**Comment by kdy1** [comment] 2021-12-22 18:27
It will make writing transforms much harder, so it's no anyway.

**Comment by longlho** [comment] 2021-12-22 18:29
Can you explain that point? Assuming comment transformation/emit is still unsupported what's the complexity in just parsing?

**Comment by kdy1** [comment] 2021-12-22 18:32
I mean lifetime will be headachr if comments are stored in Module type.

**Comment by longlho** [comment] 2021-12-22 18:49
Can you clarify that? That's how babel does it so there is 1 reference implementation. 
I think the bottom line is that comments need to be captured so the decision is whether you wanna attach to a node the same way TS does it or just combining all of them and store it at a top level like babel.
The former has a lot of complexity and the latter seems like a good stepping stone. Right now your AST is also technically a private API so there's no compatibility SLA here. Therefore I'm not sure what "lifetime" means here.

**Comment by coderaiser** [comment] 2022-02-05 14:14
Would be amazing to have comments in `AST` tree. I'm working on [swc-to-babel](https://github.com/coderaiser/swc-to-babel), and want to use it in  🐊`Putout` linter, and if some file in source tree has comments, they need to be preserved 🤷‍♂️. Someone put comments there for a reason.

Here is example of `Babel`:

```json
{
  "type": "File",
  "start": 0,
  "end": 29,
  "loc": {
    "start": {
      "line": 1,
      "column": 0
    },
    "end": {
      "line": 3,
      "column": 1
    }
  },
  "errors": [],
  "program": {
    "type": "Program",
    "start": 0,
    "end": 29,
    "loc": {
      "start": {
        "line": 1,
        "column": 0
      },
      "end": {
        "line": 3,
        "column": 1
      }
    },
    "sourceType": "module",
    "interpreter": null,
    "body": [
      {
        "type": "FunctionDeclaration",
        "start": 9,
        "end": 29,
        "loc": {
          "start": {
            "line": 2,
            "column": 0
          },
          "end": {
            "line": 3,
            "column": 1
          }
        },
        "id": {
          "type": "Identifier",
          "start": 18,
          "end": 23,
          "loc": {
            "start": {
              "line": 2,
              "column": 9
            },
            "end": {
              "line": 2,
              "column": 14
            },
            "identifierName": "world"
          },
          "name": "world"
        },
        "generator": false,
        "async": false,
        "params": [],
        "body": {
          "type": "BlockStatement",
          "start": 26,
          "end": 29,
          "loc": {
            "start": {
              "line": 2,
              "column": 17
            },
            "end": {
              "line": 3,
              "column": 1
            }
          },
          "body": [],
          "directives": []
        },
        "leadingComments": [
          {
            "type": "CommentLine",
            "value": " hello",
            "start": 0,
            "end": 8,
            "loc": {
              "start": {
                "line": 1,
                "column": 0
              },
              "end": {
                "line": 1,
                "column": 8
              }
            }
          }
        ]
      }
    ],
    "directives": []
  },
  "comments": [
    {
      "type": "CommentLine",
      "value": " hello",
      "start": 0,
      "end": 8,
      "loc": {
        "start": {
          "line": 1,
          "column": 0
        },
        "end": {
          "line": 1,
          "column": 8
        }
      }
    }
  ]
}
```

And `swc`:

```json
{
  "type": "Module",
  "span": {
    "start": 0,
    "end": 25,
    "ctxt": 0
  },
  "body": [
    {
      "type": "FunctionDeclaration",
      "identifier": {
        "type": "Identifier",
        "span": {
          "start": 9,
          "end": 14,
          "ctxt": 0
        },
        "value": "world",
        "optional": false
      },
      "declare": false,
      "params": [],
      "decorators": [],
      "span": {
        "start": 0,
        "end": 25,
        "ctxt": 0
      },
      "body": {
        "type": "BlockStatement",
        "span": {
          "start": 17,
          "end": 25,
          "ctxt": 0
        },
        "stmts": []
      },
      "generator": false,
      "async": false,
      "typeParameters": null,
      "returnType": null
    }
  ],
  "interpreter": null
}
```

Almost everything can be converted, but where should I get `comments` from 🤷‍♂️?

**Comment by kdy1** [comment] 2022-02-05 14:19
@coderaiser 

swc to babel already exists.
See https://github.com/swc-project/swc/tree/bfada04b338a70323eb205ee147a2157d328ad46/crates/swc_estree_compat

**Comment by kdy1** [comment] 2022-02-05 14:20
Currently there's no js api to get comment

**Comment by coderaiser** [comment] 2022-02-05 14:21
> swc to babel already exists.
> See https://github.com/swc-project/swc/tree/bfada04b338a70323eb205ee147a2157d328ad46/crates/swc_estree_compat

Nice :)! How can I use it from `js`?

**Comment by coderaiser** [comment] 2022-02-06 13:06
> Currently there's no js api to get comments

OK, but is it possible to use it from `@swc/core`, for example, with a method `parseSync`:

```js
const {parseSync} = require('@swc/core');
const ast = parseSync(`const hello = 'world'`);
const babelAst = swcToBabel(ast);
```

Or even:

```js
const {parseSync, swcToBabel} = require('@swc/core');
const ast = parseSync(`const hello = 'world'`, {
    babel: true,
});
```

> swc to babel already exists.
See https://github.com/swc-project/swc/tree/bfada04b338a70323eb205ee147a2157d328ad46/crates/swc_estree_compat

Why does it called `swc_estree_compat`? Is it related to [Babel AST](https://github.com/babel/babel/blob/main/packages/babel-parser/ast/spec.md) or [ESTree AST](https://github.com/estree/estree#the-estree-spec) or both :)?

The thing is they are [quite different](https://babeljs.io/docs/en/babel-parser#output) and that's why [`estree-to-babel`](https://github.com/coderaiser/estree-to-babel) exist.

**Comment by kdy1** [comment] 2022-02-06 14:44
It can emit acorn ast/babel ast

**Comment by coderaiser** [comment] 2022-02-06 18:50
> It can emit acorn ast/babel ast

That’s awesome :)!
Could you please show me an example of 
- ✅parsing source to SWC AST;
- ✅converting SWC AST to acorn and Babel;

**Closed** 2022-03-11 07:26 UTC
Labels: enhancement
