### ISSUE TITLE
'parse' in @swc/core does not have idempotent span information

### ISSUE THREAD

**Issue by marcins** [swc-project/swc#5562] opened 2022-08-19 06:08 UTC
### Describe the bug

If you call `parse` in `@swc/core` twice with code as strings, the `span` information does not get reset between invocations resulting in incorrect values.

### Input code

```typescript
import { parse } from '@swc/core';

async function main() {
    const code = "'Hello world';";
    const { span } = await parse(code);
    console.log(span);
    const { span: span2 } = await parse(code);
    console.log(span2);
}

main();
```

### Expected behavior

Expected output:
```
{ start: 1, end: 15, ctxt: 0 }
{ start: 1, end: 15, ctxt: 0 }
```

### Actual behavior

Actual output:
```
{ start: 1, end: 15, ctxt: 0 }
{ start: 16, end: 30, ctxt: 0 }
```

### Version

1.2.239

**Comment by kwonoj** [comment] 2022-08-19 06:14
I believe this is dupe of https://github.com/swc-project/swc/issues/1366.

**Comment by kdy1** [comment] 2022-08-19 06:15
Closing as duplicate

**Closed by kdy1** 2022-08-19 06:15 UTC
Labels: C-bug

**Comment by marcins** [comment] 2022-08-19 06:27
Ah, yes, so it is.. I did search but I wasn't using the right keywords to find it. Thanks.
