### ISSUE TITLE
Replacing babel with SWC in Webpack 5 giving internal error `Error: missing field 'name' at line 1 column 51`

### ISSUE THREAD

**Issue by jainChetan81** [swc-project/swc#8014] opened 2023-09-27 06:08 UTC
### Describe the bug

SWC in unable to start the build process in webpack 5, instead throwing internal error
<img width="639" alt="Screenshot 2023-09-26 at 11 42 16 PM" src="https://github.com/swc-project/swc/assets/38555207/0ce2e566-746b-41e2-8cb8-45daf1c36a80">

I have followed [Antony Budianto's blog](https://antonybudianto.com/blog/migrating-babel-to-swc) and had no success in the starter template from react-cool-starter that we use in our organization.
I have also prepared a github repo [here](https://github.com/jainChetan81/react-starter) with the same issue, for replicating, just clone the repo and run `yarn && yarn build`

### Input code

```typescript
optimization: {
		minimizer: [
			new TerserPlugin({
				// @ts-ignore
				minify: TerserPlugin.swcMinify,
				terserOptions: { compress: { drop_console: true } }
			})
		]
	},
	plugins: getPlugins(isWeb) as WebpackPluginInstance[],
	module: {
		rules: [
			{
				test: /\.[tj]sx?$/,
				exclude: /node_modules/,
				use: {
					loader: "swc-loader",
					options: {
						module: {
							type: "es6"
						},
						caller: { target: isWeb ? "web" : "node" },
						cacheDirectory: isDev,
						minify: !isDev,
						isModule: true,
						jsc: {
							minify: {
								compress: true,
								mangle: true,
								format: {
									asciiOnly: true,
									comments: /^ webpack/
								}
							},
							target: "es2016",
							parser: {
								syntax: "typescript",
								tsx: true
							},
							transform: {
								react: {
									runtime: "automatic"
								}
							}
						}
					}
				}
			},
                 ]
             }
```

### Config

```json
There is no .swcrc config here, I have the config in the code given above
```

### SWC Info output

  Operating System:
        Platform: darwin
        Arch: x64
        Machine Type: x86_64
        Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64
        CPU: (8 cores)
            Models: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

    Binaries:
        Node: 16.20.2
        npm: 8.19.4
        Yarn: 1.22.19
        pnpm: 8.5.1

    Relevant Packages:
        @swc/core: 1.3.89
        @swc/helpers: N/A
        @swc/types: 0.1.5
        typescript: 4.3.5

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

SWC should start the build process

### Actual behavior

Unknown error  ` Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: missing field 'name' at line 1 column 51`
<img width="639" alt="Screenshot 2023-09-26 at 11 42 16 PM" src="https://github.com/swc-project/swc/assets/38555207/b00ce5ac-74ca-44b2-b329-8ad2750faef0">

### Version

0.2.3

### Additional context

I am trying to replace babel by swc 
I have installed `  "swc-loader": "^0.2.3",`    `"@swc/core": "^1.3.89"` `"@swc/plugin-loadable-components": "^0.3.87"`

**Comment by jainChetan81** [comment] 2023-10-12 09:18
Hey, is this issue part of planned milestone? or is this being worked upon or will be worked upon in the future?

**Comment by kdy1** [comment] 2023-10-12 09:24
Closing as not actionable, as there's no way to reproduce it. Please file another issue with a minimal reproduction.

**Comment by kdy1** [comment] 2023-10-12 09:24
Oops

**Comment by kdy1** [comment] 2023-10-12 09:25
I'll work on it. I ignored it because I missed the link to the reproduction.

**Comment by jainChetan81** [comment] 2023-10-12 09:37
Thanks, will be monitoring this

**Comment by kdy1** [comment] 2023-10-16 08:05
Unassigning myself as the provided repro case is not a minimal reproduction

**Comment by jainChetan81** [comment] 2023-10-18 06:30
Hey, can you please give more details as what should I give for minimal repro? I thouht this was good enough as I am this has the same problem as described above https://github.com/jainChetan81/react-starter

**Comment by kdy1** [comment] 2023-10-18 06:34
It has too many deps and too many command that are not related to swc

**Closed** 2024-03-12 01:21 UTC
Labels: C-bug
