### ISSUE TITLE
optional chain 

### ISSUE THREAD

**Issue by JunweiAi** [swc-project/swc#7199] opened 2023-04-04 01:39 UTC
### Describe the bug

There is a bug, when use optional chain like a?.b.map?.(item => item)

### Input code

```typescript
const data = {content: [{name:'test', age: 18}]};
const names = data?.content.map?.(item => item.name);
```

### Config

```json
[
    {
        "test": ".tsx?$",
        "jsc": {
            "parser": {
                "syntax": "typescript",
                "tsx": true,
                "decorators": true,
                "dynamicImport": true,
                "decoratorsBeforeExport": true,
                "exportDefaultFrom": true
            },
            "loose": false,
            "transform": {
                "legacyDecorator": true,
                "decoratorMetadata": true,
                "useDefineForClassFields": false
            }
        },
        "module": {
            "type": "commonjs"
        }
    },
    {
        "test": ".jsx?$",
        "jsc": {
            "parser": {
                "syntax": "ecmascript",
                "jsx": true,
                "decorators": true,
                "dynamicImport": true,
                "decoratorsBeforeExport": true,
                "exportDefaultFrom": true
            },
            "loose": false,
            "transform": {
                "legacyDecorator": true,
                "decoratorMetadata": true,
                "useDefineForClassFields": false
            }
        },
        "module": {
            "type": "commonjs"
        }
    }
]
```

### Playground link

https://play.swc.rs/?version=1.3.44&code=H4sIAAAAAAAAAytLLFJIVLBVqE7OzytJzSuxUoiuzkvMTbVSL0ktLlGvja3lSrTXg0rq5SYW2OtpZJak5irY2imAaD2QYk0AUZ4fXUYAAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAwF9zkF8rrbdtE79BAWdSIifrKJVBTl7iUE0maH3xsz8jooBbNoeKq1PMsQkYX4nEsi2Sf8lARIOxTNJia49XaWvRrRCtVoOxpIyBOluiX3hoMNQajjLXPGmzH%2FC3VwkUnkCu4o%2BsnSVTc0JbjwXmrZDkk50qF%2FwA%2FqsvNjMPLqm4kXGrYvhlQioBQBAAA%3D

### Expected behavior

names is ['test']

### Actual behavior

names is []

### Version

1.3.44

### Additional context

The result is right when used 1.3.31.

**Comment by kdy1** [comment] 2023-04-04 01:44
Closing as duplicate

**Closed by kdy1** 2023-04-04 01:44 UTC
Labels: C-bug

**Comment by jridgewell** [comment] 2023-04-04 02:12
Duplicate of https://github.com/swc-project/swc/issues/7003
