### ISSUE TITLE
`Array.prototype.at()` and `String.prototype.at()` polyfills are not being imported

### ISSUE THREAD

**Issue by shanesc** [swc-project/swc#6761] opened 2023-01-06 20:46 UTC
### Describe the bug

Polyfills of `Array.prototype.at()` and `String.prototype.at()` are not working.

The modules exist in `core-js` at [https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.at.js](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.array.at.js) / [https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.string.at-alternative.js](https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/es.string.at-alternative.js) but don't appear to be importing correctly.

### Playground link

https://play.swc.rs/?version=1.3.25&code=H4sIAAAAAAAAA0vOzysuUahQsFVQSsvPT0osUtJLLNHQNdLkSgbLVAJlog11jHSMY0EShpoApmilAjEAAAA%3D&config=H4sIAAAAAAAAA0WPTWrDQAyFr2IE3Q2hNKQLL3qAQs4QlIlspswfkhxijO9ezZCQ3Ru9T09vNvgTD%2BMGFVmIm5I1Kz5gBF0riedQFRyo2Eh5od008kxqBMnJrFiKEIwTRiEHKeQwrS3Il1SZRN4W5jm%2ByJbDmGUqnBrNhF6buNGdYqmJsr7Q3eBUbktb3nqvfvwbbB7k%2FHRaOweU7x3qHe02%2FHwevk4fbshFh1Ivrd%2BAMUKPbEGL4Ez29IXp1zaODq7LPIUHyfPL%2Bz9M%2Ft7LJwEAAA%3D%3D

### Expected behavior

Import the correct polyfills for `.at()` array and string methods from `core-js`.

### Actual behavior

No imports present.

### Version

1.3.25

**Comment by magic-akari** [comment] 2023-01-08 06:29
Duplicate of #6460

**Comment by kdy1** [comment] 2023-01-08 06:39
Thanks!

**Closed by kdy1** 2023-01-08 06:39 UTC
Labels: C-bug

**Comment by gu-stav** [comment] 2023-01-08 12:28
Another reference: https://github.com/swc-project/jest/issues/132 This seems to break in 1.3.21.
