### ISSUE TITLE
Keyword as method name with generic not working for TSX

### ISSUE THREAD

**Issue by donaldpipowitch** [swc-project/swc#2099] opened 2021-08-18 07:07 UTC
**Describe the bug**

It looks like using keywords as method names with a generic does not work with TSX.

**Input code**

```tsx
const test = {
  default<T>(t: T) {
    return t;
  },
};

Error: error: Expected a semicolon
  --> /test.ts:2:10
   |
2  |   default<T>(t: T) {
   |          ^

error: Expected ,, got < (jsx tag start)
  --> /test.ts:2:10
   |
2  |   default<T>(t: T) {
   |          ^
```

**Config**

```js
        parser: {
          syntax: 'typescript',
          tsx: true,
        },
        transform: {
          react: {
            refresh: true,
          },
        },
```

**Expected behavior**
Should parse without errors.

**Version**
The version of @swc/core: 1.2.78

**Additional context**
Tested via swc-loader.

Thank you for this project!

**Comment by kdy1** [comment] 2021-08-19 12:37
Closing as duplicate of #968.

**Closed by kdy1** 2021-08-19 12:37 UTC
Labels: C-bug
