### ISSUE TITLE
swc paths aren't compiled correctly for sources outside of the root folder

### ISSUE THREAD

**Issue by johnny-fuse** [swc-project/swc#7074] opened 2023-03-13 08:27 UTC
### Describe the bug

Created a small project that has **main** apps directory and a **shared** folder.

When trying to use path aliasing to the outer shared folder the compiled code doesn't include the shared code at all.

(When using build using **tsc**, and the same paths everything works fine)

Below is a playground that demonstrates the issue.

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2017",
    "parser": {
      "syntax": "typescript",
    },
    "baseUrl": "src",
    "paths": {
        "shared/*": ["../../../shared/*"]
    },
  },
  "minify": false
}
```

### Playground link

https://github.com/johnny-fuse/SwcPlayground

### Expected behavior

The compiled code **structure** should be the same when using tsc.

### Version

1.3.40

**Comment by MrSharpp** [comment] 2023-04-05 12:26
any fix?

**Comment by dorsharonfuse** [comment] 2023-04-13 11:48
Hi, any update on this issue?

**Comment by Doomann** [comment] 2023-09-22 12:03
any fix now maybe?

**Comment by kdy1** [comment] 2023-10-02 05:20
Closing as this is not a bug.

`npx swc src --out-dir dist` is the command for compiling `src`, **not your project**.
TypeScript compiler has a project mode, and that's why depdendencies are compiled along with the input files you specified.

**Closed by kdy1** 2023-10-02 05:20 UTC
Labels: C-bug
