### ISSUE TITLE
swc helpers name collision

### ISSUE THREAD

**Issue by shredor** [swc-project/swc#8451] opened 2023-12-22 10:12 UTC
### Describe the bug

Naming collision with swc _define_property helper if there's _define_property variable and eval in source code

### Input code

```typescript
const a = () => {
  const _define_property = 1;
  const fn = () => console.log({ [prop]: 'test' });
};

const b = () => eval('console.log()');
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true,
      "tsx": true,
      "jsx": true
    },
    "loose": false,
    "externalHelpers": true
  },
  "env": {
    "targets": "> 0.25%, not dead, Safari >=8",
    "mode": "entry",
    "coreJs": "3.27",
    "loose": false,
    "bugfixes": true
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.101&code=H4sIAAAAAAAAA0vOzysuUUhUsFXQ0FSwtVOo5lJQSAaLxaekpmXmpcYXFOUXpBaVVAKVGFrDZdPy4FpAAvk5qXo5%2Beka1QrRIPWxVgrqJanFJeoKtZrWXLXWXFwQXUlwTalliTka6shaNdWBSgGW9y1FjwAAAA%3D%3D&config=H4sIAAAAAAAAA32OzQ6CQAyE7z7Fpok3YgzGaEzkrF59ggrFQGB30y0GQnh3F%2BTHePDW%2BWbaTrtSCnIXw0m1fvTCIjviWXviGi1YewLSWHIxZ1YgmNyk0Vhm8bW0hsWHhCuaTXH1L8pnNJDuY0BhjCNvpFi4MQxUC7HG4kKFJXbL2rAEpF9LbUF%2BkvQZiNR2E%2B7XgdJGVEKYBOqOKXKmovNxLA6lSfp3%2FohwM8HYMN2GG7tNeIA%2F1R7VM81q%2Bu606t71QI0DTQEAAA%3D%3D

### Expected behavior

```javascript
import { _ as _define_property } from "@swc/helpers/_/_define_property";
var a = function() {
    var _define_property1 = 1;
    var fn = function() {
        return console.log(_define_property({}, prop, "test"));
    };
};

var b = function() {
    return eval("console.log()");
};

```

### Actual behavior

```javascript
import { _ as _define_property1 } from "@swc/helpers/_/_define_property";
var a = function() {
    var _define_property1 = 1;
    var fn1 = function() {
        return console.log(_define_property1({}, prop, "test"));
    };
};
var b = function() {
    return eval("console.log()");
};

```

### Version

1.3.101

**Comment by Austaras** [comment] 2023-12-23 10:26
Duplicate of #8185?

**Comment by Austaras** [comment] 2023-12-28 22:24
No. It's different.

**Closed** 2023-12-28 23:56 UTC
Labels: C-bug
