### ISSUE TITLE
Reference to exported function in namespace are not handled properly

### ISSUE THREAD

**Issue by julienfouilhe** [swc-project/swc#2582] opened 2021-10-29 13:08 UTC
Hi!

I have a namespace in which I export functions.
One of those functions references another one of those.

```
import * as ReadonlyArray from 'fp-ts/ReadonlyArray';
import { flow, pipe } from 'fp-ts/function';

export namespace DomainEvents {
  export const appendEvent = <T extends string>(event: DomainEvent<T>) => (
    events: DomainEvents<T>,
  ) => pipe(events, ReadonlyArray.append(event));
  export const appendEventFromType = flow(DomainEvent.fromType, appendEvent);
}
```

tsc compiles this properly, but with swc I get this!

```
webpack://./src/domain/DomainEvents/DomainEvents.ts?:47
    DomainEvents.appendEventFromType = (0, _function).flow(DomainEvent1.fromType, appendEvent);

ReferenceError: appendEvent is not defined
    at eval (webpack://./src/domain/DomainEvents/DomainEvents.ts?:47:83)
    at eval (webpack://./src/domain/DomainEvents/DomainEvents.ts?:50:3)
    at Object../src/domain/DomainEvents/DomainEvents.ts
```

Generating output when using swc cli is:

```
(function(DomainEvents) {
    DomainEvents.appendEvent = (event)=>(events)=>ReadonlyArray.append(event)(events)
    ;
    DomainEvents.appendEventFromType = (0, _function).flow(DomainEvent1.fromType, appendEvent);
})(DomainEvents1 || (exports.DomainEvents = DomainEvents1 = {
}));
``` 

So it uses `appendEvent` instead of using `DomainEvents.appendEvent`

@swc/cli: 0.1.51
@swc/core: 1.2.105

**Comment by vramana** [comment] 2021-10-31 06:58
Duplicate of #2423

**Closed** 2021-11-19 11:38 UTC
