### ISSUE TITLE
TypeScript `module` compile issue 

### ISSUE THREAD

**Issue by xiluo58** [swc-project/swc#2636] opened 2021-11-03 07:38 UTC
### Describe the bug

When a variable defined in a module is referenced inside the module, the variable name is not prefixed with module name, causing undefined error in browser.

### Input code

```typescript
export module RuleInterpreterHelper {
    export const fieldNameMap: [string, string][] = [];

    export const fieldNameHashMap: Map<string, string> = new Map(fieldNameMap);
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA0utKMgvKlHIzU8pzUlVCAISnnklqUUFRalA0iM1pyC1SKGal0sBCFIhSpPz84pLFNIyU3NS%2FBJzU30TC6wUootLijLz0nUUIHRsdKyCrUJ0rDUvFz6tHonFGWDtQMIG1QQ7oP681HKQjAayVZpAI2sBwjVmjrQAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1ts0id%2BghjKsEF%2F%2FQKBBjfPfawSU7aebpqdIXlrZK2QhYxoQS1Vy0kZbMsOKy0kKKHu3Gg1tfjBysHWG8eudTAs92oeCi28sw2RSyMPBUJh7%2BT7YuCulzjqDez27hSu1xzDuH9wRVTm4%2FOkwQUrUAAAA%3D

### Expected behavior

` RuleInterpreterHelper.fieldNameHashMap = new Map(fieldNameMap);` should be `RuleInterpreterHelper.fieldNameHashMap = new Map(RuleInterpreterHelper.fieldNameMap);`

### Version

1.2.106

### Additional context

TS Playground:
https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAWwgEwK4BthwEoeASQDsZgowpgSoAJYdMUuAbwCg525RJY4BjCQgGd4AMwCWdZADkAhgmABZGWABccANrCoYwgHMANHC07dAXXWm4AXg2mA3CzYcu0ePyGiJ6aXODUZggAWSqpwIQA8xnqGUboAfNZwhMAA7mHKABTikrLyIQCUDgC+QA

**Comment by such0624** [comment] 2021-11-30 07:59
Duplicate of #2423

**Closed** 2022-03-05 21:56 UTC
Labels: C-bug
