### ISSUE TITLE
Panic when specifying an invalid ident in `@jsx` pragma

### ISSUE THREAD

**Issue by lucacasonato** [swc-project/swc#8572] opened 2024-01-29 18:25 UTC
### Describe the bug

When specifying a string in the JSX pragma that is not a valid identifier, SWC panics.

### Input code

```typescript
/** @jsx a- */
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "react": {
        "importSource": "npm:react",
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA9PX0lJwyCquUEjUVdDSBwBouw4QDgAAAA%3D%3D&config=H4sIAAAAAAAAA1WQPQ7CMAyFd05ReWZAHRi4AxMnsIJbBTU%2Fsh2JCvXuJOn%2FEiXfe8%2BO%2Fbs0DXzEwKP55Wt%2BRGQh3t6ZyOgVv5mAjpHEsI0K11VVKZJyokqmWQBF7klLiKS9te0SgCEEoYw7HIQW5qy33XhsaYKLTCJnY7Gi74ctf%2B7I6KUL7I6FmNDoAWRkXQysr5DYlELgo3vMtutu4uTVuqpj0uBQrYFFni7rWVuDC%2B9U%2F7RssGxpHvwOu2mdcZsHrDzXZF3f9Ae8XWptjQEAAA%3D%3D

### Expected behavior

No panic, ignore pragma, and emit diagnostic.

### Version

1.3.100

**Comment by kdy1** [comment] 2024-01-30 06:57
Closing as duplicate of https://github.com/swc-project/swc/issues/7938

**Closed by kdy1** 2024-01-30 06:57 UTC
Labels: C-bug
