### ISSUE TITLE
redeclaration of `var` variables is not supported

### ISSUE THREAD

**Issue by raon0211** [swc-project/swc#4589] opened 2022-05-09 14:53 UTC
### Describe the bug

After updating our `@swc/core` version to the latest version (`1.2.179`), we have encountered the following error.

```
../../../.yarn/cache/pdfmake-npm-0.2.4-33697a8572-0f20435f30.zip/node_modules/pdfmake/build/pdfmake.js
Error: 
  × the name `fn` is defined multiple times
       ╭─[/Users/raon0211/dev/toss-frontend/.yarn/cache/pdfmake-npm-0.2.4-33697a8572-0f20435f30.zip/node_modules/pdfmake/build/pdfmake.js:72020:5]
 72020 │ var fn = original[kCustomPromisifiedSymbol];
       ·     ─┬
       ·      ╰── previous definition of `fn` here
 72021 │     if (typeof fn !== 'function') {
 72022 │       throw new TypeError('The "util.promisify.custom" argument must be of type Function');
 72023 │     }
 72024 │     Object.defineProperty(fn, kCustomPromisifiedSymbol, {
 72025 │       value: fn, enumerable: false, writable: false, configurable: true
 72026 │     });
 72027 │     return fn;
 72028 │   }
 72029 │ 
 72030 │   function fn() {
       ·            ─┬
       ·             ╰── `fn` redefined here
       ╰────
```

We did not have the error until `@swc/core@1.2.150`.

Although redeclaring variables declared with `var` is valid JavaScript, it seems that SWC is finding it wrong.

### Input code

```typescript
// https://github.com/bpampuch/pdfmake/blob/master/build/pdfmake.js
exports.promisify = function promisify(original) {
  if (typeof original !== 'function')
    throw new TypeError('The "original" argument must be of type Function');

  if (kCustomPromisifiedSymbol && original[kCustomPromisifiedSymbol]) {
    var fn = original[kCustomPromisifiedSymbol];
    if (typeof fn !== 'function') {
      throw new TypeError('The "util.promisify.custom" argument must be of type Function');
    }
    Object.defineProperty(fn, kCustomPromisifiedSymbol, {
      value: fn, enumerable: false, writable: false, configurable: true
    });
    return fn;
  }

  function fn() {
    /* ... some code ... */
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.179&code=H4sIAAAAAAAAA41Sy07DMBC89yuGHpq0itI7VU8IriDRG%2BKQxzo1OHa0sRsilH%2FHSZPwkApcLO16ZnZmbXqrDNs6rtiUspaixR7C6cxKozE3Q8OykDpRa7wvACkQ2rYiIzBd4Gq%2FRzAxg7VHAfbIpoGmBgePvmU2HAaHI2E50ZZIuHAlaYvS1RYpwYv22ribtXaLcebrjceY8mG0JSl%2FbMvUKKxWs5GnS6Dns3fglDCE9jn%2FpuwGwpe4nvcj6Cj6W1hnpfpccJwNw%2F6ZvFfuhvM%2BfaHMxjkJqclbrYhtGwod4ZL9aPZ2SpSja%2FRg0n4oJ6nq60TVFKFhab81MqOFLNyIsuzo7GP0w2Qda6%2FWl13%2FOPOPETqcNrLdII5j1KYkL5jTUG22A6X7ADh9gtl3AgAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

SWC should not throw an error.

### Actual behavior

SWC throws an error.

### Version

1.2.179

**Comment by raon0211** [comment] 2022-05-09 15:02
I think this is due to this PR, which supports module/script mode: https://github.com/swc-project/swc/pull/3880

After changing the source type to `script`, we don't have an error.

However, the same code does not have an error in babel (when using `sourceType: 'module'`)

[Babel REPL](https://babeljs.io/repl/#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgzgOjFCBbAlndAzAngAgF59sBXAOwGMZ0Jz9k1MdcAKadAc3XIEMAbAJT4A3gCh8-HPlYxcYYBGz4O3Pv3wBCQsQDkZKjTq7BEyfhgALFAHd85YHYAq84AFEoKKK11PLwfAAiVR4BQPxeKE5SVGByGHxUUjgEgCMApQtXfAAxCmpachMAbjEzaVYAawBhZJg0AAUUDCxsdGAAEwBlXFRUiA0AMkGVKC5Q_gBtGrrG5uY2zp6-gYBdYXFzfAA3SJJ6YhD1adqUuaZW9u7e_v5V0q2KuQVM7HptPQMC4w2zLatbPZHPgXAoPF4fH4AoFSDR-Eh5q1cAhKLNUOFItFYvFEnV8OkVMpngE8oZCiU_vgAL6UgDyqQAVsBqAgOsA2g4mhAFLA2G8ADT4GZnVBclo4K7LW6CzZbHYCUjAABc-0FcRiwCgvFS_GVJAEcGAgpsYxg2t1KuwBqN-EodDa0S1Or1MCgispVMED3MUGAMFIUHob29NLMXyMQfIrF-WwA9AAqfAIZP4OBoAJ2tlJlPx2NmGlUoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.17.11&externalPlugins=&assumptions=%7B%7D)

**Comment by raon0211** [comment] 2022-05-09 15:17
It seems that it is in fact an error to redeclare `var` variables when the source type is module  👀 

```html
<!-- In firefox -->
<script type="module">
var foo;

function foo() {}
</script>
```

```
Uncaught SyntaxError: redeclaration of var foo
note: Previously declared at line 2, column 4
```

**Comment by kdy1** [comment] 2022-05-09 15:18
Closing as it's not a bug

**Closed** 2022-05-09 15:18 UTC
Labels: C-bug
