### ISSUE TITLE
Path aliases don't seem to respect nested folder structure

### ISSUE THREAD

**Issue by JanJakes** [swc-project/swc#2050] opened 2021-08-10 12:14 UTC
**Describe the bug**
After https://github.com/swc-project/swc/issues/1934 and https://github.com/swc-project/swc/issues/1935 were resolved in `1.2.76`, I gave it a quick try and run into another issue.

It seems to me that `paths` simply rewrites the path prefix but doesn't respect the location of given file. I also tried using `baseUrl` but no luck. Am I missing some configuration?

**Input code**
Using `~` as an alias for `src` and having a file `src/subfolder/A.ts` with an `import { B } from '~/subfolder/B.ts';` (and considering the `src/subfolder/B.ts` exists and exports `B`), we'll run into `Error: Cannot find module './subfolder/B'`.

This is because the import was rewritten to `./subfolder/B` instead of just `./B` or `../subfolder/B` (that should be correct as these files are in the same subfolder indeed).

The command I'm running is: `yarn swc src -s -d ./dist`

**Config**
Note that `baseUrl` probably has no effect but I tried to add it to conform with `tsconfig.json`.

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
    },
    "target": "es2020",
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

Also note that in TypeScript the correct path in the config would be `"~/*": ["./src/*"]` in this case (including the `src` portion) since `baseUrl` is `.`. With SWC, however, I need to use just `./*`, probably because I'm passing `src` dir to the `swc` command. 

**Expected behavior**
Paths should be rewritten using current file location (not just using a static prefix).
In the given example the import from `'~/subfolder/B.ts` was rewritten to `./subfolder/B` instead of just `./B` (or `../subfolder/B`).

**Version**
The version of @swc/core: 1.2.76

**Additional context**
TypeScript also uses `baseUrl` to set the base path relative to which imports are rewritten.

**Comment by schmod** [comment] 2021-08-24 21:46
Also worth noting that SWC currently only appears to transform ES-style `import`s.  

Paths are not resolved for CJS imports with `require('~/file.ts')`

**Comment by JanJakes** [comment] 2021-08-25 06:39
@schmod I don't think that's related to this issue, you may want to create a new one, I guess. There is also https://github.com/swc-project/swc/issues/1943 but that's about emitting to ES-style imports so I guess it's not related either.

**Comment by JanJakes** [comment] 2021-09-07 08:58
@kdy1 This has no specific estimate or priority, right? Are the paths-related issues small fixes or large issues? Since decorators are fixed now I can't wait to test SWC on our backend codebase but unfortunately it's all path-aliased.

**Comment by kdy1** [comment] 2021-09-07 10:31
@JanJakes 
> This has no specific estimate or priority, right
It has higher priority than issues without milestone.

> Are the paths-related issues small fixes or large issues?
I don't expect it to be a large task.

**Comment by kfirba** [comment] 2021-09-09 11:11
Eagerly waiting for this to be resolved :)

**Comment by kdy1** [comment] 2021-09-09 11:19
I'll fix this with the next version.

**Comment by stefee** [comment] 2021-09-12 18:18
I am still able to reproduce this issue or a similar issue using the latest commit in this repo and building locally (since it is not published yet to npm).

---

I am building using `@swc/cli` with the following:

```bash
swc server --config-file server/.swcrc --out-dir dist/server --copy-files
```

`server/.swcrc` contains this:

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "paths": {
      "server/*": [
        "./*"
      ]
    }
  },
  "module": {
    "type": "commonjs"
  }
}
```

`server/index.ts` contains this:

```ts
import 'server/datadog/tracing/init';
```

`server/datadog/tracing/init.ts` contains this:

```ts
import absolutePathsTest from 'server/mod';
console.log(absolutePathsTest);
```

---

The output:

`dist/server/index.js` contains:

```js
require("./datadog/tracing/init");
```

`dist/server/datadog/tracing/init.js` contains:

```js
var _mod = _interopRequireDefault(require("./mod"));
```

The expected output in `dist/server/datadog/tracing/init.js` should be:

```js
var _mod = _interopRequireDefault(require("../../mod"));
```

**Comment by stefee** [comment] 2021-09-12 22:18
I've provided a better text fixture in https://github.com/swc-project/swc/pull/2241 - I might not be able to work on the fix though, I'm a bit rusty when it comes to rust!

**Comment by stefee** [comment] 2021-09-14 14:02
I am doing some more testing around the issue we are experiencing - the bug seems to be more nuanced than it initially appears, and it seems to be at least tangentially related to `<file ...>` and `--out-dir` on the CLI.

We have the following file structure:

```
package.json
tsconfig.json
...
server
├── absolutePathTest.ts
├── datadog
│   └── tracing
│       └── init.ts
├── index.ts
└── logger.ts
```

If I run the following from the root dir:

```bash
swc server --config-file server/.swcrc  --out-dir dist/server --copy-files
```

Then the resultant file tree is this: ✅ 

```
dist
└── server
    ├── absolutePathTest.js
    ├── datadog
    │   └── tracing
    │       └── init.js
    ├── index.js
    └── logger.js
```

However, if I set cd to server and run this:

```bash
swc $PWD --config-file .swcrc --out-dir ../dist/server --copy-files  # --config-file flag is optional here
```

Then the result file tree is incorrect: ❌ 

```
dist
└── server
    ├── absolutePathTest.js
    ├── index.js
    ├── logger.js
    └── tracing
        └── init.js
```

I'm not sure if this is actually the same bug, or an unrelated bug, perhaps related to #2210.

**Comment by stefee** [comment] 2021-09-14 17:55
Just to confirm, we are still experiencing the issue(s) on v1.2.87 - I will create a GH repo with a minimal reproduction soon to share.

**Comment by stefee** [comment] 2021-09-14 18:02
Here's our repro: https://github.com/stefee/swc-issue-repro-2050

**Comment by vjpr** [comment] 2021-09-14 19:17
> Here's our repro: stefee/swc-issue-repro-2050

Repo not accessible.

**Comment by stefee** [comment] 2021-09-14 19:19
@vjpr Woops! Try again now.

**Comment by stefee** [comment] 2021-09-15 10:15
I have had a revelation - our `.swcrc` was missing the `baseUrl` property and only using `paths`. With the fix introduced in 1.2.87 this works as expected if we add the `baseUrl`. 🎉 

I have updated my repro repository to include repro-3 and repro-4 which are identical to repro-1 and repro-2 but include the `baseUrl` - you can see that this resolves the issue and now `dist` has the correct import path.

However, the issue described in my comment about file trees is still present, even with `baseUrl`. I think this should be addressed as a separate issue.

**Comment by kdy1** [comment] 2021-09-16 03:22
@JanJakes Can we close the issue?

**Comment by stefee** [comment] 2021-09-16 08:07
I think the baseUrl prop is missing from the docs - shall we fix that before closing this?

**Comment by kdy1** [comment] 2021-09-16 08:28
@stefee I added it to the documentation.

**Comment by stefee** [comment] 2021-09-16 08:29
👍🏻

**Comment by vjpr** [comment] 2021-09-16 09:57
This didn't seem to fix my issue.

```
swc src -d lib -s
```

```
    "baseUrl": "src",
    "paths": {
      "@src/*": [
        "*"
      ]
    }
```

```
- src
  - foo/index.ts = `import '@src/index'` 
  - index.ts
```

_lib/foo/index.js_

```diff
- ... require("./index") ...
+ ... require("../index") ... 
```

Actual: -
Expected: +

---

`@src/index` resolves to `<base_url>/index.js` = `src/index.js`

`src/index.js` relative from `src/foo/index.ts` = `../index.js`

I also use `rootDir: '.'` in tsconfig. Maybe this is a setting that is missing in swc.

**Comment by stefee** [comment] 2021-09-16 10:25
You could try and see if either of these work:

```json
    "baseUrl": "./src",
    "paths": {
      "@src/*": [
        "*"
      ]
    }
```

```json
    "baseUrl": ".",
    "paths": {
      "@src/*": [
        "./src/*"
      ]
    }
```

**Comment by vjpr** [comment] 2021-09-16 12:09
This works:

```
 "baseUrl": ".",
    "paths": {
      "@src/*": [
        "./src/*"
      ]
    }
```

I think the missing config option is `rootDir` if you want to have parity with `tsconfig`.

**Comment by vjpr** [comment] 2021-09-16 12:12
Also, if I use es6 modules, the aliases don't work.

```
  "module": {
    "type": "es6"
  }
```

**Comment by JanJakes** [comment] 2021-09-16 13:18
@vjpr That's https://github.com/swc-project/swc/issues/1943.

> Can we close the issue?

@kdy1 From a quick try it seems to work for me! Thanks! I'm not 100% sure if it behaves exactly as TypeScript does (i.e. in cases like https://github.com/swc-project/swc/issues/2050#issuecomment-920845548) but that can be covered by other issues, I guess.

**Closed** 2021-09-16 13:19 UTC
Labels: C-bug

**Comment by vjpr** [comment] 2021-09-16 13:22
Is there an issue to track making it behave the same as tsconfig?

**Comment by JanJakes** [comment] 2021-09-16 13:42
@vjpr I don't think so as we don't know if/how the behavior differs at the moment. If you have a reproduction of some differences between SWC and Typescript path handling, it would be great to describe them in a new issue, I guess.

**Comment by aelbore** [comment] 2021-09-18 14:22
you check this also #2126

**Comment by matthew-dean** [comment] 2021-11-03 22:30
@JanJakes It doesn't seem to match TSC at all, at the moment. Does `swc` try `index` files when it resolves a path?

For example:
```
import { Button } from '@ui/Button'
```
```
baseUrl: './src',
paths: { 
  "@ui/*": ["ui/*"]
}
```
This does not resolve to `./src/ui/Button/index.ts' (which is TypeScript's behavior).
