### ISSUE TITLE
ESM(TypeScript) => CJS Doesn't Preserve Import Order

### ISSUE THREAD

**Issue by XiNiHa** [swc-project/swc#1736] opened 2021-05-24 08:12 UTC
**Describe the bug**
While transpiling TypeScript code, TSC preserves the order while SWC doesn't and just puts all the imports to the top.
It can cause errors in some situations. The code below is the minimum reproduction of the problem I've faced.
I'm not sure if it's just an implementation detail of TSC or a spec but the resulting code is different and it can causes errors.

**Input code**
parent.ts
```ts
class ParentClass {}

import { ChildClass } from './child'

const child = new ChildClass()
```

child.ts
```ts
import { ParentClass } from './parent'

class ChildClass extends ParentClass {}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2018"
  },
  "module": {
    "type": "commonjs"
  }
}

```

**Expected behavior**
`require()` statement should be at the same place where `import` statement was at
(at least that's what TSC does)

**Version**
The version of @swc/core: 1.2.58

**Additional context**
Since the problem can be solved by using `require()` instead of import, fixing this issue isn't that needed.

**Comment by kdy1** [comment] 2021-05-24 08:15
Duplicate of https://github.com/swc-project/swc/issues/1686

To follow the specification, import statements should be hoisted and `tsc` is simply doing wrong thing.
Official typescript compiler has a PR to fix the wrong behavior. (See https://github.com/microsoft/TypeScript/pull/39764)

**Closed** 2021-05-24 08:31 UTC
Labels: C-bug
