### ISSUE TITLE
SWC not throwing "SyntaxError: Identifier <x> has already been declared" when expected

### ISSUE THREAD

**Issue by edwincoronado** [swc-project/swc#2991] opened 2021-12-07 22:18 UTC
### Discussed in https://github.com/swc-project/swc/discussions/2989

<div type='discussions-op-text'>

<sup>Originally posted by **edwincoronado** December  7, 2021</sup>
Hello everyone!

I have the following script:
```js
export const superLongNameSoItMinimizes = () => {
  var superLongNameSoItMinimizes1 = "hello";
  console.log(superLongNameSoItMinimizes1);
};

export const superLongNameSoItMinimizes = () => {
  var superLongNameSoItMinimizes1 = "hello";
  console.log(superLongNameSoItMinimizes1);
};

export function superLongNameSoItMinimizes() {
  var superLongNameSoItMinimizes1 = "hello";
  console.log(superLongNameSoItMinimizes1);
}
```

With the following `.swcrc` file:
```json
{
  "jsc": {
    "externalHelpers": true,
    "target": "es5",
    "loose": true,
    "parser": {
      "syntax": "ecmascript"
    }
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": true
  },
  "sourceMaps": false
}
```

When I run SWC on the file I get the following output:
```js
"use strict";
exports.superLongNameSoItMinimizes = superLongNameSoItMinimizes;
exports.superLongNameSoItMinimizes = void 0;
var superLongNameSoItMinimizes = function() {
    var superLongNameSoItMinimizes1 = "hello";
    console.log(superLongNameSoItMinimizes1);
};
exports.superLongNameSoItMinimizes = superLongNameSoItMinimizes;
var superLongNameSoItMinimizes = function() {
    var superLongNameSoItMinimizes1 = "hello";
    console.log(superLongNameSoItMinimizes1);
};
exports.superLongNameSoItMinimizes = superLongNameSoItMinimizes;
function superLongNameSoItMinimizes() {
    var superLongNameSoItMinimizes1 = "hello";
    console.log(superLongNameSoItMinimizes1);
}
```

I would expect a `SyntaxError: Identifier superLongNameSoItMinimizes has already been declared` error just as Babel/Node do. Is there a way to enforce these type of rules through a specific configuration?
</br>
Versions:
@swc/cli: 0.1.52
@swc/core: 1.2.118
</br>
<a href="https://github.com/swc-project/swc/files/7671994/test-script.txt">test-script.txt</a>
<a href="https://github.com/swc-project/swc/files/7672004/swcrc.txt">swcrc.txt</a>
Had to attach them as .txt files cause github didn't allow otherwise. 😛
</br>
<a href="https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlEoLi1ILfLJz0v3S8xNDc73LPHNzMvMzaxKLVawVdDQVLC1U6jm5VJQKEsswqPWEKhYKSM1JydfyRqkGmR2fk6qXk5%2BugYeXZpAxbVAzMuVOnjdlFaal1ySmZ%2BHxyqgm2jsIF4uADpHaZi2AQAA&config=H4sIAAAAAAAAAzWOwQrDMAxD%2F8XnXHfJF%2BzSjzCuN1qSONgOtJT8%2BxLWnoSQ9NAFuxHEC%2Fhw1oLpzamyGkTXxgEc9csOEdheECCJGD9ZRTXWObazOB6zRRmNdKsOvQfIsrbEs%2BFnHQokOUvZbaDMdSN%2FWH%2B3yHrTx9ikKfGCdZz5YDLuPwHT%2By6tAAAA">play.swc.rs link</a>
</br>
Any help would be appreciated. Thanks!
</div>

**Comment by kwonoj** [comment] 2021-12-07 22:21
@edwincoronado mind attach few more details, probabaly version of the swc + config? sharing play.swc.rs would be good.

**Comment by edwincoronado** [comment] 2021-12-07 22:28
Versions:
`@swc/cli`: 0.1.52
`@swc/core`: 1.2.118

[test-script.txt](https://github.com/swc-project/swc/files/7671994/test-script.txt)
[swcrc.txt](https://github.com/swc-project/swc/files/7672004/swcrc.txt)

Had to attach them as `.txt` files cause github didn't allow otherwise. 😛

**Comment by kwonoj** [comment] 2021-12-07 22:29
@edwincoronado you should able to use https://play.swc.rs/ and click `share` btn to paste here.

**Comment by edwincoronado** [comment] 2021-12-07 22:30
Yup, updated my comment above.

**Comment by edwincoronado** [comment] 2021-12-08 20:37
@kwonoj do you guys have a timeline on bugs? Just to get an estimate on when this would be resolved. Additionally, I could perhaps take a look at the code and attempt a fix myself. I don't see any recent changes in the [part of the code I thought could be causing this](https://github.com/swc-project/swc/search?q=DuplicateLabel). Is there perhaps a part of the code you think would be a good start for me to take a look at?

**Comment by kwonoj** [comment] 2021-12-08 20:39
We don't have strict ETA for each bugs unfortunately. If you're up to try to fix you're welcome to send PR.

> I don't see any recent changes

I do not believe this is recent regression, if that's the case we'd know by broken test cases. I just give a quick try on some random old versions and behavior seems same - means PR probably need implement this with test cases to assert new behavior.

**Comment by kdy1** [comment] 2021-12-09 06:18
Closing as a duplicate of #2795

**Closed by kdy1** 2021-12-09 06:18 UTC
Labels: C-bug
