### ISSUE TITLE
Error when using a function expression with explicit return type in React component

### ISSUE THREAD

**Issue by guidokessels** [swc-project/swc#3661] opened 2022-02-21 12:46 UTC
### Describe the bug

When assigning a function expression to a React component prop SWC will fail with an error if the return type is specified.

Changing it to an arrow function, or removing the return type, resolves the issue.

```
error: Unexpected token `button`. Expected jsx identifier
 --> input.tsx:5:6
  |
5 |     <button onClick={function (): void {
  |      ^^^^^^



Caused by:
    0: failed to process js file
    1: failed to process js file
    2: Syntax Error
```

### Input code

```typescript
import React from 'react';

const MyComponent = (): JSX.Element => {
  return (
    <button onClick={function (): void {
        // do something
    }} />
  )
}
```

### Config

```json
{
  "jsc": {
    "transform": {
      "hidden": {
        "jest": true
      }
    },
    "target": "es2022",
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.143&code=H4sIAAAAAAAAAyWLMQ%2BCMBSE9yb9D7cBi%2BwqLMTFxEUXVy1FG%2Bl7pryaGMJ%2Fl9qbvtzd5%2Fybg%2BBsb0YwBPYoQuJip5VWhmkSnL4drzeyJGhQVlscL9fNYbT%2B37SYtQKClRgIZWJgf48iTGDqRmdezTxEMuLWJvkfdn22cuoaPWNib%2BXp6JGHZUHdJqy0Wn7DMbqYqAAAAA%3D%3D&config=H4sIAAAAAAAAAzWLMQrAIBAE%2F3K1RbD0NxIviUKM3G1AEf8eLdLtMLOdku7kOkF81uORe8EVQ%2BC8VmIFOcjLYxiCl5MnE6vdrCVDxYuyrFJbhq%2FToRXWXWLB9ND638cHz112XWwAAAA%3D

### Expected behavior

I expect to be able to use function expressions with an explicit return type as a value for a React prop.

### Actual behavior

SWC throws an error when an explicit return type is specified.

### Version

1.2.143

**Comment by Austaras** [comment] 2022-02-21 18:43
duplicate of #3241

**Comment by kdy1** [comment] 2022-02-22 04:43
Closing as dupliate

**Closed by kdy1** 2022-02-22 04:43 UTC
Labels: C-bug
