### ISSUE TITLE
Implement JavaScript optimizer using ecmascript lexer/parser of swc

### ISSUE THREAD

**Issue by mduclehcm** [swc-project/swc#1162] opened 2020-10-13 04:23 UTC
**Question**
I can see that swc have a very impressive performance.
There is any plan to implement a new js optimizer to replace exist js optimizer like terser, uglifyjs?

**Comment by kitsonk** [comment] 2020-10-13 04:27
Duplicate of #704

**Comment by mduclehcm** [comment] 2020-10-13 04:50
> Duplicate of #704

Minify option are useful. But I don't want to use replace babel with swc right now due to lack of transform plugin. It would be nicer if we have new package to using with webpack, rollup as output optimizer.

**Comment by kdy1** [comment] 2021-05-20 04:53
I'll close this when I add the javascript apis.
Currently the minifier is beta (in rust side) and there's no js apis.

**Closed** 2021-08-13 15:50 UTC
