### ISSUE TITLE
Interfaces and Reflect meta

### ISSUE THREAD

**Issue by Jordan-Hall** [swc-project/swc#3601] opened 2022-02-16 21:12 UTC
### Describe the bug

Using interfaces and reflect-meta leaves a reference to the interface `Reflect.metadata("design:type", typeof MenuItem === "undefined" ? Object : MenuItem)` 

I would also expect if this was imported that the import statement be removed for interfaces.

### Input code

```typescript
import {Component, Input} from '@angular/core';


export interface MenuItem {
  label: string;
  icon: string;
  routerLink?: string[];
  items?: MenuItem[];
  command?: (event?: unknown) => void;
  class?: string;
  url?: string;
  target?: string;
  type?: MenuType;
  permission?: string[];
  disabled?: boolean;
}


@Component({
  selector: 'angular-vite-demo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'vite-demo';
  @Input() item?: MenuItem;
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2016",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "decoratorMetadata": true,
      "legacyDecorator": true
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA2VRy24CMQy8I%2FEPvgUkHncQhaonpPbWnhCHkHVpRGJHiZcWIf692SysClUu1mRsj2esDxwFzi%2BcC0KSEawp1HKBz8ge1ErTvnY6Tg1HVPN%2Br3n4U5osCcZPbRDekOq1oIdzvwfg9A7dDJJES%2Ft5g1jDdAdErnPvq6XD8oZvti01j0kZvI28woa911TljwEes8xc1HQg%2FqYhLJ7gyLZqeU6ntLzbVUd3D4iOe5QH7BTwuvU9lwULGL1NyTI9iqxs0juHjZwds0NNGb605qw6KwfFjYQOjXCcgbp6OT7mI8cVeh5HZlGjIgB9cFrwI2br1GSqQ5iY26TJl3jX8pKcXENKM9j8oyWTktpm3mXYpVQcgecQOl1tSmLFISxAdWpUuW1V8h8MSxJ%2Fgmgv%2FAXMlcLCMAIAAA%3D%3D&config=H4sIAAAAAAAAA0WOvQ6DMAyE38UzQ9uBgbkrD2EFg1KROLKN1Ajx7k0oP5vlu%2B%2FuVviog26FhKIk9dIcDb%2FQgeVE6sQngwZMy2vEWamBgRwLGotCZ7LQVmSUiaxApK%2FHsy3AzKx0IcFHP%2BYa7zgkIdVbwjjNp7NGCUYdWUJ1X1U9GQ5o%2BG8s8TShy%2B9TPoYUPPCw1Lh1378vamG7FxytXvvDuIM%2FRGOWLAgBAAA%3D

### Expected behavior

I would expect the imports of interfaces to be removed and the reference to the Interface be changed to Object inside the reflect meta. This is the same code using Typescript own playground 
https://www.typescriptlang.org/play?target=7#code/JYWwDg9gTgLgBAbwMIXBAdgU3TANHASXTAFcYBfOAMylTgHIABAQ3QHMSAbZqAegGNomegG4AUGMwAPSLDgwAnmExwAsthIAVJSoC8cAEQHxkmdHjAcmKFWb8V69CQIxMIRGLhxuAI0ycALjgAZxgoSzZxL2BBdCDQ8PYouFoyawAZSwBrAH54sIiAbQBdZOBXEGC8tQ0XNxLkwRAQVgATaoAKTAA3bBhqknQs9AgAd3QASjhdAD44bohgVsbuYKr8xMjPOBIoTmqEiOSYHjZMfo2j7cVlasctHWTlKBBgNeAMA4L2Bu3Wt+YPk4mHaQR8EAgwNY4nIEjEjBQaCwOA6CG2wX8mH4MGgQXorA43CgAFpuuVMMTWm4IMTaBAYPRcNc3GBuK4AKp7PEAOl4zDAYG5TUgyJg3IAFjAQJxGejFMDOZxgkFCvRefzBcKMH1ucF+Gt6MUmeQJqZZPB+KtgnAAIICxEivoeLwwcrA6YMMmuSnU0TbRhEUgwDpTckgO61CowsRAA

### Actual behavior

Imports to interfaces are still included in the file. Reflect-meta also tries and do a typeof against the interface

### Version

1.2.133

**Comment by kdy1** [comment] 2022-02-17 08:07
Why did you close this?

**Comment by Jordan-Hall** [comment] 2022-02-17 10:23
@kdy1 applogies must of closed it by mistake

**Comment by Jordan-Hall** [comment] 2022-03-02 21:54
@kdy1  where about is the source code is Reflect meta added?

**Comment by kdy1** [comment] 2022-03-03 04:38
@Jordan-Hall https://github.com/swc-project/swc/blob/5cdf1442ec561bd3358b0a47e52929a96936d061/crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs

This file is relevant one

**Comment by Jordan-Hall** [comment] 2022-03-10 11:19
@kdy1 / @Austaras I believe this is actually linked to this issue https://github.com/swc-project/swc/pull/3893 and not directly with metadata. 

The solution in metadata checking if something is undefiend is correct. However, the issue appears to be related to failed to import interface.

**Comment by Austaras** [comment] 2022-03-11 08:59
What import interface? `MenuItem` is defined locally

**Comment by Austaras** [comment] 2022-03-11 09:15
If you mean [this](https://play.swc.rs/?version=1.2.151&code=H4sIAAAAAAAAA2WQP2vDMBDFd4G%2Bw9uUQOzsLqUunTJ07BQyCPXaGvQP6VwajL97JCf20u1497vHeze4GBJjegtl8OT5gJOPI8%2F4SsFB9dp%2Fj1anowmJ1JMUUgz3E75GwvROfjwxuZVvj64ozVAkVeF%2BM95NUgCZLBkOqYN6ODe%2FBW4%2ByYUmhcDqULFyHq1m%2Bki2q6Y6xtasTu0PO3vnMl9thXKH8z8sm5zVpXDzXgr6W1Ibq3PGa4xbLiy5eGBLeIba0tSyQL98Y7dHbfTSYe1blrMUN013pSI%2BAQAA&config=H4sIAAAAAAAAA0WOvQ6DMAyE38UzQ9uBgbkrD2EFg1KROLKN1Ajx7k0oP5vlu%2B%2FuVviog26FhKIk9dIcDb%2FQgeVE6sQngwZMy2vEWamBgRwLGotCZ7LQVmSUiaxApK%2FHsy3AzKx0IcFHP%2BYa7zgkIdVbwjjNp7NGCUYdWUJ1X1U9GQ5o%2BG8s8TShy%2B9TPoYUPPCw1Lh1378vamG7FxytXvvDuIM%2FRGOWLAgBAAA%3D) then imported interface is striped; and if you don't use import type, ts would generate `typeof MenuItem` too.

**Comment by Jordan-Hall** [comment] 2022-03-11 09:18
@Austaras perfect that works when using import type.

**Comment by Jordan-Hall** [comment] 2022-03-11 18:41
@Austaras so when I just use import, the run time fails because it tries to import the interface and there no export. Is there a way around this?

**Comment by Austaras** [comment] 2022-03-12 06:32
I doubt there's any solutions as [tsc](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMIXBAdgU3TANHASXTAFcYBfOAMylTgHIABAQ3QHMSAbZqAegGNomegG4AUGNCRYiALLYSBGJhCUadegDpeIBQFpgykPQmMUaLDgAUCMXDgBnTJ0z8Y0AFwNWHblD0AboaYegAmKhB6tBAw9Lh2cEZg3MoAqlCcXlq8zGBgmoIW2DCaABYwIJxxCQ4wAJ4u6ZwOXgDa2bn5hZCWJQ78Dg70ALrx5ACUYpgAHtLw-NyDcACCeeY9xYgJMIYucAC8DEHKYRGiCYxEpDBW43DBIAD8XvLoikbi5GJAA) won't strip import either

**Comment by kdy1** [comment] 2022-03-12 07:11
As `tsc` does not strip type, this is not a bug of swc.
@Austaras Thanks for verifying

**Closed by kdy1** 2022-03-12 07:11 UTC
Labels: C-bug
