### ISSUE TITLE
Using `jsc.paths` strips import extensions with two or more dots in file name

### ISSUE THREAD

**Issue by gzzhanghao** [swc-project/swc#5575] opened 2022-08-21 11:12 UTC
### Describe the bug

The behavior is just like #3576, but only occurs when the file name has two or more dots. (like `*.module.less`).

Reproduction repository:
https://github.com/gzzhanghao/swc-paths-extensions

### Expected behavior

Extensions should not be stripped.

### Version

1.2.241

**Comment by kdy1** [comment] 2022-08-21 11:14
Closing as duplicate of https://github.com/swc-project/swc/issues/5214
Please search before filing an issue

**Closed by kdy1** 2022-08-21 11:14 UTC
Labels: C-bug
