### ISSUE TITLE
Module parse failed: Identifier '_templateObject'

### ISSUE THREAD

**Issue by HashemKhalifa** [swc-project/swc#6494] opened 2022-11-21 21:21 UTC
### Describe the bug

using SWC with storybook getting this error

```ERR! => Failed to build the preview
ERR! Module parse failed: Identifier '_templateObject' has already been declared (100:9)
ERR! File was processed with these loaders:
ERR!  * ./node_modules/storybook-addon-swc/node_modules/swc-loader/src/index.js
ERR!  * ./node_modules/swc-loader/src/index.js
ERR! You may need an additional loader to handle the result of these loaders.
ERR! |     return data;
ERR! | }
ERR! > function _templateObject() {
ERR! |     var data = _taggedTemplateLiteral([
ERR! |         "\n  background: ",

### Input code

_No response_

### Config

```json
{
  jsc: {
    parser: {
      syntax: 'typescript',
      jsx: true,
      dynamicImport: true,
      privateMethod: true,
      functionBind: true,
      exportDefaultFrom: true,
      exportNamespaceFrom: true,
      decorators: true,
      decoratorsBeforeExport: true,
      topLevelAwait: true,
      importMeta: true,
      preserveAllComments: false,
    },
    transform: {
      react: {
        runtime: 'automatic',
        development: !isProd,
        pragma: 'React.createElement',
        pragmaFrag: 'React.Fragment',
      },
      legacyDecorator: true,
      decoratorMetadata: true,
    },
    target: 'es2021',
    loose: false,
    externalHelpers: false,
    // Requires v1.2.50 or upper and requires target to be es2016 or upper.
    keepClassNames: false,
    experimental: {
      plugins: [
        [
          '@swc/plugin-styled-components',
          {
            fileName: !isProd,
            minify: isProd,
            ssr: true,
          },
        ],
        ['@swc/plugin-loadable-components', {}],
      ],
    },
  },
}
```

### Expected behavior

the storybook build should pass!

### Version

1.3.18

**Comment by kwonoj** [comment] 2022-11-21 22:31
Please provide reproducible repo, with minimal codes input to isolate root cause.

**Comment by kdy1** [comment] 2022-11-22 08:15
Closing as a duplicate of https://github.com/swc-project/swc/issues/5068

**Closed by kdy1** 2022-11-22 08:15 UTC
Labels: C-bug, Need more info
