### ISSUE TITLE
205 to 206 update breaks jest tests with star imports

### ISSUE THREAD

**Issue by Smrtnyk** [swc-project/swc#5204] opened 2022-07-14 07:36 UTC
### Describe the bug

Ever since I updated swc core from 205 to 206 my jest tests break with message:
```
Cannot redefine property: getCookie
TypeError: Cannot redefine property: getCookie
    at Function.defineProperty (<anonymous>)
    at ModuleMocker.spyOn (C:\workspaces\repositories\cdf\abc\node_modules\jest-mock\build\index.js:820:16)
```
I assume it is because of this commit
https://github.com/swc-project/swc/commit/fa68cbd74ad2b36c0f1aaec563320114d5603cae

I provided a screenshot with a diff of transformed output code
![swc-repro](https://user-images.githubusercontent.com/31451544/178927080-10da04c2-515a-4a85-90f4-036842d40735.PNG)
 between 205 and 206
 
 Seems like 206 now adds the extra
 ```
 Object.defineProperty(exports, "__esModule", {
    value: true
});
```

I have a hunch that it could be related to the failure.
I have tried setting the module to commonjs in swc config but still didn't work

### Input code

```typescript
import type { JSAgent } from "../../types/dt-types";
import * as Cookies from "../jstf-utils/cookies";
import { CoreApiProp } from "../../types/dt-types";
import { getCurrentSessionId } from "./agent-utils";

jest.mock("../jstf-logger");

describe("testframework/api/dtutils/agent-utils.ts", () => {
    describe("getCurrentSessionId()", () => {
        it("detects current session id when v3 cookie format", () => {
            const v3CookieParserSpy = jest.fn().mockReturnValue({ serverId: "35", sessionId: "sessionID" });
            const agentMock = {
                [CoreApiProp.PARSE_V3_SESSION_COOKIE]: v3CookieParserSpy
            } as unknown as JSAgent;
            jest.spyOn(Cookies, "getCookie").mockReturnValue("=3=sn=sessionID");
            expect(getCurrentSessionId(agentMock)).toBe("sessionID");
            expect(v3CookieParserSpy).toHaveBeenCalledWith("=3=sn=sessionID");
        });
        it("returns empty string if no agent is available", () => {
            expect(getCurrentSessionId(null)).toBe("");
        });
    });
});
```

### Config

```json
transform: {
        "^.+\\.(t|j)sx?$": ["@swc/jest", {
            "sourceMaps": "inline",

            "module": {
                "strictMode": false
            },

            "jsc": {
                "target": "es2021",
                "parser": {
                    "syntax": "typescript"
                }
            }
        }]
    },
```

### Expected behavior

I would expect since I changed nothing in swc config that tests still work.
Or was there some change that requires config update?

### Actual behavior

Tests fail.

### Version

1.2.206

**Comment by kdy1** [comment] 2022-07-14 07:37
Closing as duplicate of lots of issues.

**Closed by kdy1** 2022-07-14 07:37 UTC
Labels: C-bug

**Comment by Smrtnyk** [comment] 2022-07-14 07:48
I think you should elaborate a bit why you closed this and which issues this duplicates.
You published a patch version 206 which had a breaking change, and you closed this issue as not planned.
I would at least like to know the reason why this happens and if it will be ever fixed, or if I need to adjust the config?
Otherwise I will need to stay on swc 205 not being able to upgrade.

**Comment by kdy1** [comment] 2022-07-14 07:51
See #5205
