### ISSUE TITLE
cannot install latest swc_cli, previous version creates plugins that don't compile

### ISSUE THREAD

**Issue by joshcartme** [swc-project/swc#5393] opened 2022-08-04 17:39 UTC
### Describe the bug

If you try to install the latest `swc_cli`, `0.86.0` it fails:
```
> cargo install swc_cli
...many crates downloaded...
Compiling swc_ecma_transforms_proposal v0.128.0
error[E0599]: no method named `into_indirect` found for struct `swc_ecma_ast::TaggedTpl` in the current scope
   --> /Users/jcartmell/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_module-0.137.1/src/module_ref_rewriter.rs:112:27
    |
112 |             *n = n.take().into_indirect()
    |                           ^^^^^^^^^^^^^ method not found in `swc_ecma_ast::TaggedTpl`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `swc_ecma_transforms_module` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `swc_cli v0.86.0`
```

The previous version, `0.85.0` installs, but it then produces a plugin that doesn't compile.  Using `0.85.0`:
```
> swc plugin new test-plugin --target-type=wasm32-wasi
> cd test-plugin
> cargo prepublish

error[E0432]: unresolved imports `swc_plugin::ast`, `swc_plugin::plugin_transform`, `swc_plugin::TransformPluginProgramMetadata`
 --> src/lib.rs:1:18
  |
1 | use swc_plugin::{ast::*, plugin_transform, TransformPluginProgramMetadata};
  |                  ^^^     ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `TransformPluginProgramMetadata` in the root
  |                  |       |
  |                  |       no `plugin_transform` in the root
  |                  could not find `ast` in `swc_plugin`

error: cannot determine resolution for the attribute macro `plugin_transform`
  --> src/lib.rs:30:3
   |
30 | #[plugin_transform]
   |   ^^^^^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

error[E0405]: cannot find trait `VisitMut` in this scope
 --> src/lib.rs:5:6
  |
5 | impl VisitMut for TransformVisitor {
  |      ^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Program` in this scope
  --> src/lib.rs:31:35
   |
31 | pub fn process_transform(program: Program, _metadata: TransformPluginProgramMetadata) -> Program {
   |                                   ^^^^^^^ not found in this scope

error[E0412]: cannot find type `Program` in this scope
  --> src/lib.rs:31:90
   |
31 | pub fn process_transform(program: Program, _metadata: TransformPluginProgramMetadata) -> Program {
   |                                                                                          ^^^^^^^ not found in this scope

error[E0425]: cannot find function `as_folder` in this scope
  --> src/lib.rs:32:28
   |
32 |     program.fold_with(&mut as_folder(TransformVisitor))
   |                            ^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0405, E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0405`.
error: could not compile `test-plugin` due to 6 previous errors
```
^ This same error occurs if I:
```
> yarn add @swc/core // install 1.2.223
> npx swcx plugin new test-plugin
> cd test-plugin
> cargo prepublish
```

I'm trying to update `@swc/core` and all my plugins to the latest versions.  What is the best path forwards?  Thanks!

### Expected behavior

The latest `swc_cli` installs and produces plugins that compile.

### Version

0.86.0

**Comment by kwonoj** [comment] 2022-08-04 18:43
There is a massive refactoring in progress (https://github.com/swc-project/swc/discussions/5244) which _hopes to reduce these kind of probem_ but creating some fluxes while doing it 😭 . For now this needs upstream fixes, meanwhile you could use prebuilt one installed via `@swc/core` npm pkg (or download it from cdn).

**Comment by joshcartme** [comment] 2022-08-04 18:47
Got it, thanks @kwonoj!

If I try to use the prebuilt, I can't compile the plugins it makes.  For example:
```
> yarn add @swc/core // install 1.2.223
> npx swcx plugin new test-plugin
> cd test-plugin
> cargo prepublish
```
Results in the same error that I got when I tried to use `swc_cli` `0.85.0` directly.  Do you have thoughts on that?

**Comment by kwonoj** [comment] 2022-08-04 18:52
Oh, 

`plugin new` is separate issue. Root cause is same though (work in progress https://github.com/swc-project/swc/discussions/5244). 

In short, you need to replace import from `swc_plugin` to `swc_core`, cli template need to be updated once swc_core makes additional progress. You can manually do it for now and if there's missing exports can report back though.

**Comment by joshcartme** [comment] 2022-08-04 18:53
Ok got it, I'll do that, is this, https://github.com/swc-project/swc/blob/8b9dd6f026e13fa850a7adcca52e285d874d4390/node-swc/e2e/fixtures/plugin_transform_schema_vtest/src/lib.rs, a correct example of what the imports should look like right now?

**Comment by kwonoj** [comment] 2022-08-04 18:55
Yes, that's the model we're trying to achieve.

**Comment by kdy1** [comment] 2022-08-05 11:54
Fixed by https://github.com/swc-project/swc/commit/e44e8b103c190206f6e79a15d50ee634ae138454

**Closed by kdy1** 2022-08-05 11:54 UTC
Labels: C-bug
