### ISSUE TITLE
ReferenceError: Cannot access 'o' before initialization - Minimizer

### ISSUE THREAD

**Issue by loic294** [swc-project/swc#6254] opened 2022-10-26 01:35 UTC
### Describe the bug

I recently enabled SWC minimizer for Webpack on a large project and got a `ReferenceError: Cannot access 'o' before initialization`. After comparing the Terser and SWC minified code, I was able to find that SWC is missing a "let" statement at the beginning of the function. This is related to the JS strict mode that requires variables to be defined before being used: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#changes_in_strict_mode. 

I edited our actual code to reproduce the minimal code that will produce the error. If I remove any part of this code (except the `useInfoService(infoService);` that is only there to show we use `infoService` later in the function), I get the expected result.

### Input code

```typescript
export async function mount(config: FluidConfig) {
    let infoService: Promise<InfoService> | undefined;

    if (hasFeature('a-feature')) {
        infoService = getInfoPromise({
            locale: 'en_us',
        });
        if (infoService) {
            preCacheInfo(infoService);
        }
    }

    let editor: IEditor | undefined = undefined,
        shouldRefresh: boolean = false;
        
    if (isContainerForConfig(containerConfig)) {
        editor = containerConfig.editor;
        shouldRefresh = !!containerConfig.isComponentRefresh;
    }

    const [targetDiv] = createHandler(
        shouldRefresh,
    );

    useInfoService(infoService);
}

async function useInfoService(infoService) {
    console.log(await infoService())
}
```

### Config

```json
{
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true,
      "decorators": true
    },
    "preserveAllComments": true,
    "transform": null,
    "target": "es2017",
    "loose": false,
    "externalHelpers": false,
    "keepClassNames": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "minify": true,
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA31Sy07DMBC85yu2pzgS9AMS4FKo6A3BESFkknVjybUrPwoI%2Bu%2Bs45CkUVUfIseenRnPLn7tjfXA3beuQQRde2k07EzQntVGC7ktYa2CbFbdTwE%2FGdBS6EFqYV7QHmSNJTxZs5MObzbj4R38QtANCqmxqbKuTgpgLXdr5D5YZDm%2FFmmbF%2F%2FUHWxkgVvYoo%2B0vQQbYZ0TU3NFBnLU78HlV8PlsahGPpKdcE6l4tpbXPG6xahyghsZjln6Dq%2FHRnpjS9g8dJvpW8nysB%2F9uNYE1TyjsOjaEj6MUcg1YQVXDkelISfpKHPPicWujU35x56ko74f06ckS8Q4Ay3TRXXeCuEXi3lF1N7tjUbte1g1DYDgzsOr55Z6cy8Pb1HUUifxketGoWXntVIaRT8MweFkXGbBZxlpzcbyQkEfQzRGuS6V2TL%2ByeXJlLKiINI%2FA%2BE%2F%2FvICAAA%3D&config=H4sIAAAAAAAAA3VUy47bMAz8F51z2O2lRW7FAkV7aH9BUGTK0VYSDZHyxgj876USR46T7U0a8zHkjHxWhCVb%2BG0GUnvOBXbqnazan9VgMkGuJ5oSm5PaK54GIJv9wGqnmE63jG5KJnr7Kw6YuYFgMRvGvBSed2rIICVH%2BB7CG8YIiVtTziaRwxzVPpUQBDC5BymmgL68vH6VhgGRQO2dCSQJcGLIyYSfEAaoPRb8L8DwFgzRHxNhhaNP3k11Goux8qB6lh5lobHEmZzxo7E6IAYQYo93bUj7xNDfd7YYgqwR9Ghyy6jdTPaEaQMVhk4PGYc7NHWePcpItK7QdNpiBw3wGSz7EdYQqSEhiYRYY3IBOziUvq8KXiNhNKEYbrXgdFmDdGx5R%2FTE2pVED9CG6RW6DrlEeaczcMmpeQh92uyhyqJt1SVtdLngTnTYRrpPonxyIiJPDRVDrKwS9DKc9t61CStryOzXbWXoioU6oV2LL%2BBmIPIdaHBOtt2S6cOzPa7F6mtA166yNeNWDa5XffPTFq0WeAJ%2FCCu%2Bl2PBo%2BHjI0ZTPGB4KhGBj9g9wbIIxkcwi3tPwyNaUgeyZujuPhSq12ZTEZ9RB%2BB1z2IIydF9wEOzr7z3aFJfbXlWjEOAEcJW0f%2F64RNMmoxV4MWKN%2BPBt1UzIz7yry8LMM%2Fz%2BuyvRCN2ZeEj2sm%2FRXSImN5JzfM%2F9dmlDAoFAAA%3D

### Expected behavior

```js
"use strict";async function e(e){let o;hasFeature("a-feature")&&(o=getInfoPromise({locale:"en_us"}))&&preCacheInfo(o);let t=!1;isContainerForConfig(containerConfig)&&(containerConfig.editor,t=!!containerConfig.isComponentRefresh);let[r]=createHandler(t);n(o)}async function n(e){console.log(await e())}Object.defineProperty(exports,"__esModule",{value:!0}),Object.defineProperty(exports,"mount",{enumerable:!0,get:()=>e});
```
`let o;` in `function e(e){let o;hasFeature` is set before being called. 

### Actual behavior

```js
"use strict";async function e(e){hasFeature("a-feature")&&(o=getInfoPromise({locale:"en_us"}))&&preCacheInfo(o);let o,t=!1;isContainerForConfig(containerConfig)&&(containerConfig.editor,t=!!containerConfig.isComponentRefresh);let[r]=createHandler(t);n(o)}async function n(e){console.log(await e())}Object.defineProperty(exports,"__esModule",{value:!0}),Object.defineProperty(exports,"mount",{enumerable:!0,get:()=>e});
```

`o` in `&&(o=getInfoPromise` is called before being defined. It should be defined before setting the value. 

### Version

1.3.9

### Additional context

I found the two following solutions:

1. Do not initialize two variables in one let statement:

```ts
let editor: IEditor | undefined = undefined;
let shouldRefresh: boolean = false;
```
[Playground Live Example](https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA31Sy07DMBC85yu2pzgS9ANS4FKo6A3BESFkknVjybUrPwoI%2Bu9s4rR2I1QfLD9mZ3ZnF792xnrg7ls3IIJuvDQatiZozxqjhdzUsFJBtsvhUsFPAbQUepBamBe0e9lgDU%2FWbKXDm3V6vINfCLpFITW2i2KIkwJYx90KuQ8WWcmvRTyW1ZF6gCUWuIUN%2Bp52lGAJNmRiGq4ogRL1e3Dl1enzUC0SH8lmnLlUv3YWl7zpsFc5wyWGQxH3U%2FXYSm9sDeuH4ZDXSilndR8DXGeCap9RWHRdDR%2FGKOSasIIrh0np5JN05LnnxGJXxkb%2F%2B57Ep7EfeSkxJWKcgObxI0mcpUL42Wwa0Wtvd0aj9iNskRtAcOfh1XNLvbmX%2B7de1FIn8ZHrVqFl%2F2vF7lTjMASH2bhMjC8K0pqM5YWA0YY%2BMfJ1rsyG8U8uz6aUVRWR%2FgGCHqfM8gIAAA%3D%3D&config=H4sIAAAAAAAAA3VUy47bMAz8F51z2O2lRW7FAkV7aH9BUGTK0VYSDZHyxgj876USR46T7U0a8zHkjHxWhCVb%2BG0GUnvOBXbqnazan9VgMkGuJ5oSm5PaK54GIJv9wGqnmE63jG5KJnr7Kw6YuYFgMRvGvBSed2rIICVH%2BB7CG8YIiVtTziaRwxzVPpUQBDC5BymmgL68vH6VhgGRQO2dCSQJcGLIyYSfEAaoPRb8L8DwFgzRHxNhhaNP3k11Goux8qB6lh5lobHEmZzxo7E6IAYQYo93bUj7xNDfd7YYgqwR9Ghyy6jdTPaEaQMVhk4PGYc7NHWePcpItK7QdNpiBw3wGSz7EdYQqSEhiYRYY3IBOziUvq8KXiNhNKEYbrXgdFmDdGx5R%2FTE2pVED9CG6RW6DrlEeaczcMmpeQh92uyhyqJt1SVtdLngTnTYRrpPonxyIiJPDRVDrKwS9DKc9t61CStryOzXbWXoioU6oV2LL%2BBmIPIdaHBOtt2S6cOzPa7F6mtA166yNeNWDa5XffPTFq0WeAJ%2FCCu%2Bl2PBo%2BHjI0ZTPGB4KhGBj9g9wbIIxkcwi3tPwyNaUgeyZujuPhSq12ZTEZ9RB%2BB1z2IIydF9wEOzr7z3aFJfbXlWjEOAEcJW0f%2F64RNMmoxV4MWKN%2BPBt1UzIz7yry8LMM%2Fz%2BuyvRCN2ZeEj2sm%2FRXSImN5JzfM%2F9dmlDAoFAAA%3D)

2. Initialize the `ìnfoService` with a value (other than `undefined`)

```ts
let infoService: Promise<InfoService> | undefined | null = null;
```
[Playground Live Example](https://play.swc.rs/?version=1.3.9&code=H4sIAAAAAAAAA31Sy07DMBC85yu2pzgS9AMSyqVQ0RuCI0LIJOvEkmtXfhQQ9N%2FZxKFOowofkrU9O7OeXfzcG%2BuBuy9dgwi69tJo2JmgPauNFrItYaOCbNbDpoDvDGgp9CC1MM9oD7LGEh6t2UmHN9t0eAs%2FEHSDQmpsKNZBKVgNvyobWKQA1nG3Qe6DRZbzaxHDvPgTGmCJk%2FJb9L3IKMgSbKjL1FxROTnqt%2BDyq9PlsagSH8lOOKdS%2FdpbXPO6w17lDJcYjln8nrzARnpjS9jeD8HZy1cpTvW4zgTVPKGw6LoS3o1RyDVhBVcOk9LJJ%2BmoA54Ti90YG7vRdygejd2ZPiWWRIwz0DJeVJdLIfxiMc%2FotXd7o1H7EVZNDSC48%2FDiuaXe3MnDay9qqZP4wHWj0LLLWtGNYhyG4HAyPDPjs4y0ZkP6T8JoQ18Y%2BbpUpmX8g8uzmWVFQaS%2FFGo%2FTAADAAA%3D&config=H4sIAAAAAAAAA3VUy47bMAz8F51z2O2lRW7FAkV7aH9BUGTK0VYSDZHyxgj876USR46T7U0a8zHkjHxWhCVb%2BG0GUnvOBXbqnazan9VgMkGuJ5oSm5PaK54GIJv9wGqnmE63jG5KJnr7Kw6YuYFgMRvGvBSed2rIICVH%2BB7CG8YIiVtTziaRwxzVPpUQBDC5BymmgL68vH6VhgGRQO2dCSQJcGLIyYSfEAaoPRb8L8DwFgzRHxNhhaNP3k11Goux8qB6lh5lobHEmZzxo7E6IAYQYo93bUj7xNDfd7YYgqwR9Ghyy6jdTPaEaQMVhk4PGYc7NHWePcpItK7QdNpiBw3wGSz7EdYQqSEhiYRYY3IBOziUvq8KXiNhNKEYbrXgdFmDdGx5R%2FTE2pVED9CG6RW6DrlEeaczcMmpeQh92uyhyqJt1SVtdLngTnTYRrpPonxyIiJPDRVDrKwS9DKc9t61CStryOzXbWXoioU6oV2LL%2BBmIPIdaHBOtt2S6cOzPa7F6mtA166yNeNWDa5XffPTFq0WeAJ%2FCCu%2Bl2PBo%2BHjI0ZTPGB4KhGBj9g9wbIIxkcwi3tPwyNaUgeyZujuPhSq12ZTEZ9RB%2BB1z2IIydF9wEOzr7z3aFJfbXlWjEOAEcJW0f%2F64RNMmoxV4MWKN%2BPBt1UzIz7yry8LMM%2Fz%2BuyvRCN2ZeEj2sm%2FRXSImN5JzfM%2F9dmlDAoFAAA%3D)

**Comment by kdy1** [comment] 2022-10-26 01:37
Duplicate of https://github.com/swc-project/swc/issues/6217

**Closed by kdy1** 2022-10-26 01:37 UTC
Labels: C-bug
