### ISSUE TITLE
Could not compile `swc_ecma_visit`

### ISSUE THREAD

**Issue by smoelius** [swc-project/swc#5915] opened 2022-09-21 00:40 UTC
### Describe the bug

I have not been able to build any project that relies on `swc_ecma_visit`.

I tried this:
```
cargo new a
echo 'swc_ecma_visit = "0.78.0"' >> a/Cargo.toml
cd a && cargo build
```

I expected a successful build. Instead I saw the following. What am I doing wrong?
```
error: proc macro panicked
    --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:497:1
     |
497  | / define!({
498  | |     use BigIntValue;
499  | |
500  | |     pub struct Class {
...    |
1821 | |     }
1822 | | });
     | |__^
     |
     = help: message: not implemented: proper error reporting for item other than struct / enum: Use(ItemUse { attrs: [], vis: Inherited, use_token: Use, leading_colon: None, tree: Name(UseName { ident: Ident { ident: "BigIntValue", span: #0 bytes(17989..18000) } }), semi_token: Semi })

error[E0405]: cannot find trait `Fold` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:17:12
   |
17 | impl<A, B> Fold for AndThen<A, B>
   |            ^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:19:8
   |
19 |     A: Fold,
   |        ^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:21:8
   |
21 |     B: Fold,
   |        ^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:36:12
   |
36 | impl<A, B> VisitMut for AndThen<A, B>
   |            ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:38:8
   |
38 |     A: VisitMut,
   |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:39:8
   |
39 |     B: VisitMut,
   |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Visit` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:52:12
   |
52 | impl<A, B> Visit for AndThen<A, B>
   |            ^^^^^ not found in this scope
   |
help: consider importing this trait
   |
9  | use tracing::field::Visit;
   |

error[E0405]: cannot find trait `Visit` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:54:8
   |
54 |     A: Visit,
   |        ^^^^^ not found in this scope
   |
help: consider importing this trait
   |
9  | use tracing::field::Visit;
   |

error[E0405]: cannot find trait `Visit` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:55:8
   |
55 |     B: Visit,
   |        ^^^^^ not found in this scope
   |
help: consider importing this trait
   |
9  | use tracing::field::Visit;
   |

error[E0405]: cannot find trait `Fold` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:68:9
   |
68 | impl<V> Fold for Repeat<V>
   |         ^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:70:8
   |
70 |     V: Fold + Repeated,
   |        ^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
  --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:99:9
   |
99 | impl<V> VisitMut for Repeat<V>
   |         ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:101:8
    |
101 |     V: VisitMut + Repeated,
    |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:131:39
    |
131 | pub fn span_remover() -> impl Debug + Fold + Copy + Eq + Default + 'static {
    |                                       ^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:135:6
    |
135 | impl Fold for SpanRemover {
    |      ^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:170:8
    |
170 |     V: VisitMut + InjectVars,
    |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:183:8
    |
183 |     V: VisitMut,
    |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:190:22
    |
190 | pub struct Folder<V: VisitMut>(V);
    |                      ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:194:19
    |
194 |     V: Repeated + VisitMut,
    |                   ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:207:8
    |
207 |     V: VisitMut + CompilerPass,
    |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:223:9
    |
223 | impl<V> VisitMut for Folder<V>
    |         ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:225:8
    |
225 |     V: VisitMut,
    |        ^^^^^^^^ not found in this scope

error[E0405]: cannot find trait `Fold` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:257:9
    |
257 | impl<V> Fold for Folder<V>
    |         ^^^^ not found in this scope

error[E0405]: cannot find trait `VisitMut` in this scope
   --> /home/smoelius/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_visit-0.78.0/src/lib.rs:259:8
    |
259 |     V: VisitMut,
    |        ^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0405`.
error: could not compile `swc_ecma_visit` due to 25 previous errors
```

### Expected behavior

A successful build

### Version

rustc 1.63.0 (4b91a6ea7 2022-08-08)

**Comment by kwonoj** [comment] 2022-09-21 00:50
0.77.8 works, looks like some sort of regressions.

Unrelated side note, (this also still fails build currently) we recommends to use `swc_core` for the swc's apis like 

```
swc_core = { version = "0.25.3", features = ["ecma_visit"] }
```

**Comment by kdy1** [comment] 2022-09-21 01:01
Should be fixed by https://github.com/swc-project/swc/commit/6d1e5c77f1d18765a689bfd5cbf3d03597285093

**Closed** 2022-09-21 01:07 UTC
Labels: C-bug
