### ISSUE TITLE
Make swc compile faster.

### ISSUE THREAD

**Issue by Boshen** [swc-project/swc#7071] opened 2023-03-13 04:54 UTC
### Describe the feature

Some of the crates compile ridiculously slow. It would be really nice if we can speed it up a bit.

From `cargo build --release --timings`:

![ade068e1-fa5e-49c3-b1ec-11e14f4767df](https://user-images.githubusercontent.com/1430279/224917360-295e1ea2-89c6-488f-9178-ea294daac217.jpeg)

### Additional context

Cross link: https://github.com/web-infra-dev/rspack/issues/2202

----

Update: 

`swc_ecma_visit` and `swc_css_visit` is blocking compilation for a whole minute due to heavy usage of macros. See https://github.com/swc-project/swc/blob/main/crates/swc_ecma_visit/src/lib.rs

**Comment by Boshen** [comment] 2023-03-13 04:55
I'll fix the multiple versions on my end.

**Comment by Boshen** [comment] 2023-03-14 06:43
Latest version:

![ade068e1-fa5e-49c3-b1ec-11e14f4767df](https://user-images.githubusercontent.com/1430279/224917360-295e1ea2-89c6-488f-9178-ea294daac217.jpeg)

**Comment by Boshen** [comment] 2023-03-14 07:15
The culprit are these three blocking everything, and they take a minute each to compile:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1430279/224923512-7ce7b5c0-2c2b-4436-bddb-6b2304677d32.png">

I think the macros inside these crates should be done in a script and then copied out.

**Comment by Boshen** [comment] 2023-03-14 07:20
Codegen is performing really badly for the minifiers:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/1430279/224924940-cb470c72-b9d2-406a-9554-5cb6ae36dd30.png">

**Comment by Boshen** [comment] 2023-03-14 07:36
I wonder if this works: https://github.com/dtolnay/watt

**Comment by kdy1** [comment] 2023-03-14 07:43
Are you using codegen-units=1?

**Comment by kdy1** [comment] 2023-03-14 07:59
Ah yeah you are using it.

https://github.com/web-infra-dev/rspack/blob/cdf6a52a39f37a8ce2975692b7c46abc729169b6/Cargo.toml#LL12

I think that's the main problem

**Comment by Boshen** [comment] 2023-03-14 08:43
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/1430279/224944687-173ea941-00d2-4de3-86ab-317a6d947fcf.png">

Changing to default codegen doesn't help (as seen from above), it's the macros ;-)

**Comment by kdy1** [comment] 2023-03-14 08:47
I know. I'm talking about codegen times of those crates.

**Comment by Boshen** [comment] 2023-03-14 08:47
I wonder if the macro implementations are sub-optimal, for example https://users.rust-lang.org/t/5-hours-to-compile-macro-what-can-i-do/36508

**Comment by kdy1** [comment] 2023-03-14 08:56
Yeah, they are not optimal. It's a known issue

**Comment by Boshen** [comment] 2023-03-14 09:48
Assign this to me if you don't have the time, I'll dig deeper.

**Comment by kdy1** [comment] 2023-03-14 12:46
This is not a focus, at least at the moment.

You can create fake types like `Expr(Tokens)` or `Stmt(Tokens)` to store tokens as-is without parsing from proc macros. But it should be conditional using `cfg` , so it can be verified by giving a feature flag.

 Currently `pmutil` stores tokens in a parsed form, but `Tokens` => `Expr` => `Tokens` is a waste

**Comment by nnethercote** [comment] 2023-03-20 04:58
Summoned via https://twitter.com/boshen_c/status/1635842195113787392, I took a look at this.

First, I'll consider the high codegen times for some of the crates.

I have an Intel i9-7940X which has 14 physical cores and 28 virtual cores. My compile times for `swc` were:
- `cargo check`: 1m00s
- `cargo build`: 1m19s
- `cargo build --release`: 2m19s

So, a pretty small jump going from `check` to `build`, but a big jump going from `build` to `build --release`.

`--timings` shows that release builds are spending a huge amount of time in codegen, as mentioned above. Here is some of the `--timings` graph for a debug build:

![debug](https://user-images.githubusercontent.com/1940286/226243499-c1fb62cc-a115-45a2-89b6-ee3f0dcd0e2d.png)

And here is the same part for an opt build:

![release](https://user-images.githubusercontent.com/1940286/226243505-c59e8457-2349-44a6-a619-e3337e7e9d36.png)

Note that the purple (codegen) part is *massively* bigger in the release build. I've never seen so much purple in a `--timings` graph. And it only happens in the `swc*` crates at the bottom of the crate graph. Ones higher up have a much higher blue-to-purple ratio, like I'd expect.

`swc_node_bundler` is a good example, taking 1.25s in a debug build and 43.13s for a release build, which is a gigantic difference. I tried downloading just that crate from crates.io and compiling it using the `rustc-perf` benchmark harness. I got reasonably similar results: 0.8s for debug and 33.0s for release.

I then tried profiling the compiler with `samply` while doing debug and release builds of `swc_node_bundler`. Here is the thread timeline for a debug build:

![debug2](https://user-images.githubusercontent.com/1940286/226246605-ad87b490-a67d-4ec2-9b03-1b083e0f36c2.png)

and for an opt build:

![release2](https://user-images.githubusercontent.com/1940286/226246622-17e04d94-c2a9-4a1e-8396-678f9f37f893.png)

`rustc` is the front-end thread, the other threads are doing codegen. There are multiple codegen threads running in parallel, which suggests that the `codegen-units=1` theory from [above](https://github.com/swc-project/swc/issues/7071#issuecomment-1467585494) is incorrect. (Besides, how does `rspack` even relate to `swc`?)

For the debug build we have four "opt" threads, which are `WorkItem::Optimize` units within the compiler. For the release build we have three "opt" threads and eleven "LTO" threads, which are `WorkItem::LTO` units within the compiler. The "LTO" threads don't start until the "opt" threads finish. The top-most "LTO" thread accounts for 26 seconds of the runtime, running by itself for much of that time, so that seems to be much of the problem.

I don't know much about these "LTO" threads, and why one of them would be so slow. It definitely seems odd. The crate has only 767 lines of Rust code in it, and it looks like very normal, reasonable code. My current theory is that one of the crates that `swc_node_bundler` depends on is doing something unusual that is causing lots of `swc*` crates to be so slow to codegen. `swc_ecma_ast` and `swc_ecma_visit` look like the ones all the slow-to-compile crates have in common. Interestingly, those are two of the three crates with problematic macros that @Boshen mentioned above.

Ok, there ends part 1 of my analysis.

**Comment by Boshen** [comment] 2023-03-20 05:20
@nnethercote Thank you so much for looking into this.

> how does `rspack` even relate to `swc`

The [rspack project](https://github.com/web-infra-dev/rspack) depends on [almost all of swc](https://github.com/web-infra-dev/rspack/blob/main/Cargo.lock#L3450).

> I've never seen so much purple in a --timings graph.

I thought it's normal for codegen to take this much time, apparently it's not 😞 So now we have two problems at hand: macros and codegen.

**Comment by kdy1** [comment] 2023-03-20 05:48
Oh...
Interesting. I took the ratio graph granted because swc is my first big rust project, but it was not common 🤣 

I know the solution for the proc macro part, and AFAIK the long codegen is caused by visitors.
I profiled it a long time ago, although I didn't use rustc perf tester.

**Comment by nnethercote** [comment] 2023-03-20 05:49
Now for the crates using macros.

`swc_ecma_visit-0.86.1`
- Has 10,018 lines of code, but 7,355 of that is generated in `target/debug/build/swc_atoms-fa283f5fd94de3ff/out/js_word.rs`, mostly for a perfect hash function.
- `cargo expand`'s output is 84,893 lines of code. That's a lot! Much of that is lots of very large types with many fold and visit operations defined on them.

`swc_ecma_ast-0.100.1`
- 14,621 lines of code, but again, 7,355 of that is in `target/debug/build/swc_atoms-fa283f5fd94de3ff/out/js_word.rs`
- `cargo expand`'s output is 120,008 lines of code. That's even more! Much of that is serializing/deserializing code generated by serde, which is known to produce verbose code.

I looked at `samply` profiles of `check` builds for both of these. The profiles looked pretty normal, which suggests that the code isn't particularly unusual, but just that there's a lot of it.

I think it will take project-specific understanding to improve things. Looking at the output of `cargo expand` could be helpful. There is so much code there. Is all of it necessary? Could it be made shorter? And maybe reducing the amount of code in those modules might help with the codegen times in later modules.

**Comment by nnethercote** [comment] 2023-03-20 05:52
> Interesting. I took the ratio graph granted because swc is my first big rust project, but it was not common rofl

That's right. If you look at the earlier `swc` crates, and the non-`swc` crates, you can see that the blue and purple lengths are usually fairly similar. Sometimes the purple part might be 4 or 5 times longer, which isn't unusual. But ratios like 10, 20, 30 are unusual.

**Comment by kdy1** [comment] 2023-03-20 06:05
About macros:

 - swc_ecma_ast:

Macros create an enormous amount of code, and I think they can be reduced a bit, but not by a margin. My main trick for reducing the amount of code will be extracting common code to `swc_common` or `swc_visit`.

It includes

 - custom derive for serde
 - many implementation of `From<T>`
 - derive of rkyv::Archive
 - derive of many built-in traits

 - swc_ecma_visit

The proc-macro generates two kinds of visitors. The first one is general visitors used by swc itself, and the second one is a-path-aware visitors used by rspack and turbopack.


Btw, can `#[inline]`/generic generated by proc-macro can cause such issues?

**Comment by kdy1** [comment] 2023-03-23 02:43
I'll work on this

**Comment by mischnic** [comment] 2023-03-24 10:24
> cargo expand's output is 120,008 lines of code. That's even more! Much of that is serializing/deserializing code generated by serde, which is known to produce verbose code.

Parcel (and probably also rspack) never uses serde/rykv for swc ASTs, so maybe compile time could be improved here by putting that behind a cargo feature.

**Comment by kdy1** [comment] 2023-03-27 05:25
Can you try `swc_core@v0.70.0`?
I made `serde` of AST optional, and off by default so the compile time should be improved

**Comment by Boshen** [comment] 2023-03-27 05:38
Rspack is currently stuck on an older version due to #7085, I'll report back the improvements once we upgrade to the latest version when that's fixed on our end.

**Comment by kdy1** [comment] 2023-03-27 13:58
Oh... interesting.

```
I ran cargo build --timings and cargo build --timings --release from the repository root of vercel/turbo.
(Also, I ran cargo clean each time, and I did nothing while compiling to reduce noise)

Debug build:

New: Finished dev [unoptimized + debuginfo] target(s) in 2m 15s
Prev: Finished dev [unoptimized + debuginfo] target(s) in 2m 56s

```

This was the result for turbopack

**Comment by ItsAleph** [comment] 2023-06-02 08:37
When i tried compiling [`flash`](https://github.com/hjfod/flash) (which depends on `swc`), this crate (well, actually `swc_ecma_transforms_compat` but it is brought by this one) just caused the build to crash because linux kernel decided that it eats too much resources, and oh boy, do i agree: btop running in a sibling terminal tab shown near 100% usage of cpu and ram, and that's without any other app being open.
You may think im just complaining here, but i just want to bring more attention to this issue: its not just *slow* builds, its possibly *broken* builds (especially on old hardware (like mine) or resource-constrained environments).

**Comment by kdy1** [comment] 2023-08-17 04:56
I'll tackle this again in the near future. I want to make ES AST/parser extensible and have related idea, but it will make compilation slower

**Comment by kdy1** [comment] 2023-09-03 09:29
I think one of the biggest problems is the lack of parallelism, and wrote https://github.com/swc-project/swc/discussions/7911

It's RFC, and I want to hear opinions about such CLI tool.

**Comment by kdy1** [comment] 2023-10-12 09:22
https://github.com/swc-project/swc/pull/8110 should improve compile time a bit.

Also, this is an experiment for turbopack, but depending directly on crates makes compilation faster. https://github.com/vercel/turbo/pull/5879

I'm going to create a CLI tool to manage just as you were using `swc_core`, while depending directly

**Comment by kdy1** [comment] 2023-10-16 08:11
@Boshen @mischnic  Can you profile it again, but with `swc_core` and only with the features you use?

**Comment by kdy1** [comment] 2023-10-16 08:13
@elenakrittik 

> i just want to bring more attention to this issue

I marked it as spam because of this part.

**Comment by mischnic** [comment] 2023-10-16 09:04
I ran `rm -rf target && RUSTC_WRAPPER= cargo build --timings --release -p parcel-js-swc-core` in the Parcel monorepo root

[Before](https://github.com/parcel-bundler/parcel/commit/b521cfbdaace01674b7919d41201bb523cc14e41): 4m 40s
[After bumping swc](https://github.com/parcel-bundler/parcel/commit/c15537a98ddd0e5ccc835eda23916638f6c259ed) (with that compat split): 5m 42s

Timings reports: [cargo-timings.zip](https://github.com/swc-project/swc/files/12914317/cargo-timings.zip)

**Comment by kdy1** [comment] 2023-10-16 09:20
<img width="1728" alt="image" src="https://github.com/swc-project/swc/assets/29931815/b487a122-d76d-4202-999c-9c2cd45b0846">
<img width="1728" alt="image" src="https://github.com/swc-project/swc/assets/29931815/a92640e0-1254-4e2f-92b5-ba9520c87ea8">


Hmm... The result is closer to a noisy neighbor issue IMO, because non-swc crates show too much difference.

**Closed** 2024-02-22 02:54 UTC
Labels: enhancement
