### ISSUE TITLE
Compile Fails When Called Method Has Deep Destructed inputs. 

### ISSUE THREAD

**Issue by hkd987** [swc-project/swc#2232] opened 2021-09-10 21:53 UTC
**Describe the bug**
When calling a method that has multiple object inputs as separate inputs. SWC fails to compile when the objects are deconstructed deeply. To give context this is a graphql resolver that is being called. 
**Input code**

```
async sendSomeMessage(
			_parent: unknown,
			{ input: { toNumber, messageBody, ...all  } }: SendSomeMessageInput,
			{ dataSources }: Context,
		): Promise<boolean> 
```

When changing the called method below the code compiles

```
async sendSomeMessage(
			_parent: unknown,
			{ input }: SendSomeMessageInput,
			{ dataSources }: Context,
		): Promise<boolean> 
```

**Error Message**

```
sendSomeMessage (_parent, _param, _param) {

SyntaxError: Duplicate parameter name not allowed in this context
```

**Config**

```json
{
	"test": ".*.ts$",
	"sourceMaps": true,
	"jsc": {
		"target": "es2017",
		"externalHelpers": true,
		"loose": true,
		"parser": {
			"syntax": "typescript",
			"tsx": false,
			"decorators": true,
			"dynamicImport": false
		}
	},
	"module": {
		"type": "commonjs",
		"strict": false,
		"strictMode": true,
		"lazy": false,
		"noInterop": false
	}
}
```

**Expected behavior**
Expect that when calling a method with multiple object inputs deep object destructing will work. 

**Version**
The version of @swc/core: ^1.2.85

**Comment by kdy1** [comment] 2021-09-15 06:19
Are you using wasm?
I can't reproduce this using `@swc/core`

**Comment by hkd987** [comment] 2021-09-15 13:36
@kdy1, I am not using WASM but using typescript however looks like you were able to find and resolve the issue. Thanks.

**Comment by kdy1** [comment] 2021-09-15 13:38
I think I closed it after testing your input, not fixing bug.

**Comment by hkd987** [comment] 2021-09-15 13:58
Wonder if it makes any difference that the method that was having the this issue was on an object similar to below....

```
const resolver = {
  async sendSomeMessage(
			_parent: unknown,
			{ input: { toNumber, messageBody, ...all  } }: SendSomeMessageInput,
			{ dataSources }: Context,
		): Promise<boolean> 
}

```

**Comment by kdy1** [comment] 2021-09-16 06:06
@hkd987 The input you provided is wrong, because there's no body.

**Comment by kdy1** [comment] 2021-09-16 06:13
And I verified that swc works well with your input

**Closed by kdy1** 2021-09-16 06:13 UTC
Labels: C-bug

**Comment by hkd987** [comment] 2021-09-16 15:05
I did not provide the method body for brevity sake so that we could focus on the issue at hand only.

**Comment by hkd987** [comment] 2021-09-16 16:04
Something around this is blocking compile, I just cant put my finger on the exact issue. This is when using https://www.npmjs.com/package/@swc/jest
