### ISSUE TITLE
sourceMap config won't be respected when set to true in the config file

### ISSUE THREAD

**Issue by ozanmuyes** [swc-project/swc#2120] opened 2021-08-21 00:43 UTC
**Describe the bug**
`sourceMaps` config entry when set to `true` in `.swcrc` has no effect. Whereas `-s true` flag emits sourcemap files.

**Input code**
Irrelevant

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    },
    "target": "es2020",
    "keepClassNames": true,
    "loose": true
  },
  "module": {
    "type": "commonjs",
    "strict": true,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  },
  "sourceMaps": true
}
```

**Expected behavior**
I'm expecting corresponding sourcemap files to be emitted in the build directory.

**Version**
@swc/cli: 0.1.49
@swc/core: 1.2.80

**Additional context**
Currently in my pet project the target is Node.js (v14.17.3), I'm type checking with `tsc` and transcompiling with `swc`. Here's the build script I've been using;
```jsonc
// package.json
{
  // ...snip
  "scripts": {
    "build": "rimraf build && tsc --noEmit && copyfiles -u 2 \"src/schema/**/*.graphql\" build/schema && swc src --out-dir build -s true"
  }
}
```

**Comment by giovannibenussi** [comment] 2021-09-27 10:32
I can confirm this is happening. I'll start working to fix it!

**Comment by kdy1** [comment] 2021-09-27 10:37
I think it will be fixed by https://github.com/swc-project/cli/pull/68

**Comment by giovannibenussi** [comment] 2021-09-27 10:39
Ok, thanks for letting me know!

**Comment by giovannibenussi** [comment] 2021-09-28 10:59
The issue is still present @kdy1. I investigated more about it and I think I found the issue.

The third argument to `outputFile` expects a boolean indicating if a source map file should be generated or not:
https://github.com/swc-project/cli/blob/c0f78ad545a5f99c96971078ab93957d57ddf352/src/swc/util.ts#L71

However, we're proving that flag from `swcOptions.sourceMaps` that is provided solely on the command parameters (that's why the -s flag works), so it doesn't take into account contents from the `.swcrc` file.
https://github.com/swc-project/cli/blob/c0f78ad545a5f99c96971078ab93957d57ddf352/src/swc/file.ts#L73

Configuration inside `.swcrc` is still used to transform the file because we're passing the compiler the `.swcrc` file path but we never read that file in the CLI program.

Let me know if this makes sense or not because it may be happening with other parameters as well.

**Comment by kdy1** [comment] 2021-09-28 12:42
@giovannibenussi
Ah, I see. Then I know the fix. Thank you for investigating!

**Comment by giovannibenussi** [comment] 2021-09-28 12:47
You're welcome! If you want, you can let me know when you have a PR so I can take a look at it and get more used to the codebase.

**Comment by kdy1** [comment] 2021-09-28 12:49
Thanks!
For cli, I verified that it's working by doing `yarn build && node ./bin/swc.js src -d lib`

**Closed** 2021-09-28 13:04 UTC
Labels: C-bug
