### ISSUE TITLE
.module.css import incorrectly transformed to .module

### ISSUE THREAD

**Issue by padorang684** [swc-project/swc#6280] opened 2022-10-28 00:14 UTC
### Describe the bug

when importing a file with `.module.css` extension when `baseUrl` and `paths` config options are set, swc incorrectly transforms the import to `.module`

### Input code

```typescript
import "./test.module.css"
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "typescript"
        },
        "target": "es2016",
        "baseUrl": "./src",
        "paths": {
            "test/*": [
                "./test/*"
            ]
        }
    }
}
```

### Expected behavior

import "./test.module.css";

### Actual behavior

import "./test.module";

### Version

1.3.11

### Additional context

the imported css file has to exist

**Comment by alexander-akait** [comment] 2022-10-28 00:16
Duplicate of https://github.com/swc-project/swc/issues/6209

**Closed by alexander-akait** 2022-10-28 00:16 UTC
Labels: C-bug
