### ISSUE TITLE
swc_cli installation fails on windows

### ISSUE THREAD

**Issue by LukasGerm** [swc-project/swc#9028] opened 2024-06-07 12:01 UTC
### Describe the bug

hello, while installing swc_cli on windows I get this error 

```
   Compiling swc_ecma_ext_transforms v0.114.2
   Compiling swc_ecma_lints v0.93.1
error[E0599]: no method named `atom` found for reference `&swc_ecma_ast::ModuleExportName` in the current scope
   --> C:\Users\lukas\.cargo\registry\src\index.crates.io-6f17d22bba15001f\swc_ecma_ext_transforms-0.114.2\src\jest.rs:110:68
    |
110 | ...                   if HOIST_METHODS.contains(exported.atom()) {
    |                                                          ^^^^ method not found in `&ModuleExportName`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `swc_ecma_ext_transforms` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `swc_cli v0.91.270`, intermediate artifacts can be found at `C:\Users\lukas\AppData\Local\Temp\cargo-installvPUYRz`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```` 

# Versions

```
rustc --version
rustc 1.78.0 (9b00956e5 2024-04-29)
```

```
rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`
```

OS: Windows 11

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.5.24&code=H4sIAAAAAAAAA1WNMQ7CMAxFd5%2FCY3OFdqlgYmPgAk7qSiATR7ErFVW9eyMEQvzxf73%2Fxkt%2BcHKKwl0AXotWxyRkhjc2P%2BuzaObsyKtzngxPZPxrNwBsGa9VS7fhxDMt4j3OJMa4h%2Fdalij3hN7%2BeoyqwpQHgB2%2Bvg%2FWqORaX92fOQxwAFAhVQmlAAAA&config=H4sIAAAAAAAAA2WPSw7CMAxE9z1F5TULYIEEd%2BAQUepWQc1HtisRVb17kzYNIHbxvHjGMzdtCy%2FW8Gjn9ExDUMRIdU4KRyfqnRSQGJA1mSBwOqhwRr0aGavWofakxBMnJDThBpadgygaULIf8vV8uRcvGL1n%2FPUCa5zp4%2Fc12ttAyPwXapUbxrq%2FJzYlFazvpg2WlrnJfsENPp%2BOsGoMhp%2FH5tZjWQEa0ouIMQEAAA%3D%3D

### Expected behavior

swc_cli will install

### Actual behavior

Errors

### Version

newest

**Comment by kdy1** [comment] 2024-06-07 12:03
Duplicate of https://github.com/swc-project/swc/issues/9018

**Closed by kdy1** 2024-06-07 12:03 UTC
Labels: C-bug
