### ISSUE TITLE
Chained-Array Index Assignment does not minify correctly

### ISSUE THREAD

**Issue by exoRift** [swc-project/swc#7512] opened 2023-06-09 18:49 UTC
### Describe the bug

[Plotly.JS](https://github.com/plotly/plotly.js) has a function that performs chained array index assignment seen [here](https://raw.githubusercontent.com/plotly/plotly.js/master/dist/plotly-gl2d.js) at line 66282
![image](https://github.com/swc-project/swc/assets/20345400/8e0f9ba5-d292-48eb-a88b-8b523b02c360)

When building Next.JS with the [Plotly React component](https://github.com/plotly/react-plotly.js/) (which uses Plot.JS (this has been narrowed down)) locally (minimization, but no minification), the output is a proper result (chained assignment)
![image](https://github.com/swc-project/swc/assets/20345400/49c92ba5-5800-434d-bd4b-0a20f0c1a13e)

However, when building the same Next.JS code in a production environment (we're using [Render](https://render.com/)) which minimizes AND minifies (removing whitespace), SWC skips a variable declaration, causing a syntax error in assignment
![image](https://github.com/swc-project/swc/assets/20345400/06dba5cc-9c93-4539-83de-47cf7725bd1f)

### Expected behavior

The code should minify properly, going to shortvariable `j` for the array instead of skipping and omitting it and using `j` for the next one.

### Actual behavior

In the eyes of the compiler, the array variable doesn't exist and all references to it get replaced with void, leaving the `j` shortvariable to be used for the next variable

### Version

13.4.4

### Additional context

This project is a Next.JS project and was generated using [T3 Stack](https://create.t3.gg/) and utilizes the [React Plotly.JS component](https://github.com/plotly/react-plotly.js/)

This issue has been narrowed down to SWC as when in the [Next.JS config](https://nextjs.org/docs/pages/api-reference/next-config-js/webpack), Webpack's [optimization: minimize](https://webpack.js.org/configuration/optimization/#optimizationminimize) config option is set to `false`, this does not occur.

This issue also does not occur when built on a local machine (I'm not 100% sure why, but it seems to minimize without minifying while in the Render environment, it minimizes AND minifies)

**Comment by kdy1** [comment] 2023-06-12 13:32
Closing as duplicate of https://github.com/swc-project/swc/issues/7500, which is already fixed.

**Closed by kdy1** 2023-06-12 13:32 UTC
Labels: C-bug
