### ISSUE TITLE
"Unterminated string constant" error occurs when using @swc/jest in jest

### ISSUE THREAD

**Issue by rhkdgns95** [swc-project/swc#1345] opened 2021-01-21 02:41 UTC
**Describe the bug**

I tried to use swc to improve the speed of the existing jest, but an error occurred as above, so I ask for confirmation.

When expressing a string in the source code, it was confirmed that `` is changed to "".

So, it seems that an error occurred when a line break was made.

How to solve it?

```bash
$ yarn test
```
![image](https://user-images.githubusercontent.com/46029124/105271921-b6eec980-5bdb-11eb-8832-094caf40d50c.png)
![image](https://user-images.githubusercontent.com/46029124/105271963-cc63f380-5bdb-11eb-93ef-1d89d81cda6b.png)
```
 SyntaxError: C:\Users\BANKDA-KIM\Desktop\project\bankda-m-cafe24-backend\src\shared\model\account.entity.ts: Unterminated string constant (121:16)
```
**Input code**
> account.entity.ts
```ts

/** 등록된 계좌+회원의 정보  */
@ViewEntity({
    name: "AccountMemberView",
    expression:
    `
    SELECT
        m.tmcode, m.mid, m.accea, m.qaccea, m.endday, m.quick_endday,
        (SELECT COUNT(*) FROM TBLACCOUNT a WHERE m.mid = a.mid AND a.use_quick="F") as accountCnt,
        (SELECT COUNT(*) FROM TBLACCOUNT a WHERE m.mid = a.mid AND a.use_quick="T") as accountQuickCnt
    FROM TBLMEMBER m
    `,
    //     expression: `
    //     SELECT
    //         m.tmcode, m.mid, m.accea, m.qaccea, m.endday, m.quick_endday,
    //         IFNULL(SUM(IF (use_quick= "F", 1, 0)), 0) as accountCnt,
    //         IFNULL(SUM(IF (use_quick= "T", 1, 0)), 0) as accountQuickCnt
    //     FROM TBLMEMBER m
    //     OUTER JOIN TBLACCOUNT a ON m.mid = a.mid
    // `,
})
export class AccountMemberView {
    /** 회원의 순번 */
    @ViewColumn({ name: "tmcode" })
    memberId: number;

    /** 회원의 mall 아이디 */
    @ViewColumn({ name: "mid" })
    mallId: string;

    /** 이용가능한 (일반)계좌수 */
    @ViewColumn({ name: "accea" })
    allowAccountCnt: number;

    /** 이용가능한 퀵 계좌수 */
    @ViewColumn({ name: "qaccea" })
    allowQuickAccountCnt: number;

    /** 이용가능한 (일반)계좌의 기간 */
    @ViewColumn({ name: "endday" })
    accountEnddedAt: Date;

    /** 이용가능한 퀵 계좌의 기간 */
    @ViewColumn({ name: "quick_endday" })
    accountQuickEnddedAt: Date;

    /** 현재등록한 (일반)계좌의 수 (타입: 문자열의 숫자로 출력됨) */
    @ViewColumn()
    accountCnt: number;

    /** 현재등록한 퀵 계좌의 수 (타입: 문자열의 숫자로 출력됨) */
    @ViewColumn()
    accountQuickCnt: number;
}

```
**Config**
> .swcrc

```json
{
    "minify": true,
    "jsc": {
        "parser": {
            "syntax": "typescript",
            "tsx": false,
            "decorators": true,
            "dynamicImport": true
        },
        "transform": {
            "legacyDecorator": true,
            "decoratorMetadata": true,
            "optimizer": {
                "globals": {
                    "vars": {
                        "__DEBUG__": "true"
                    }
                }
            }
        }
    }
}
```

> jest.config.js

```js
module.exports = {
    roots: ["<rootDir>/test"],
    testMatch: ["**/test/index.spec.ts"],
    transform: {
        // "^.+\\.tsx?$": "ts-jest",
        "^.+\\.(t|j)sx?$": ["@swc/jest"],
        // "^.+\\.tsx?$": [
        //     "@swc-node/jest",
        //     {
        //         experimentalDecorators: true,
        //         dynamicImport: true,
        //         emitDecoratorMetadata: true,
        //     },
        // ],
    },
    coverageThreshold: {
        global: {
            statements: 5,
            branches: 5,
            lines: 5,
            functions: 5,
        },
    },
};
```

**Expected behavior**
`ts-node` → `@swc/jest` is work.

**Version**
```
$ C:\Users\BANKDA-KIM\Desktop\project\bankda-m-cafe24-backend\node_modules\.bin\swc --version

@swc/cli: 0.1.32
@swc/core: 1.2.45
Done in 0.79s.
```

**Comment by kdy1** [comment] 2021-01-21 03:00
I tried reproducing it, but I failed.
Can you run swc directly on it and post the result?

**Comment by rhkdgns95** [comment] 2021-01-21 04:16
Likewise, an error occurs when writing tests.

What information can I provide?

**Comment by kdy1** [comment] 2021-01-21 08:10
I need the output of swc invoked on the original input file.
In mac os x (and very likely on linux too), swc prints the expected result.

**Comment by rhkdgns95** [comment] 2021-01-21 23:30
Can you explain in detail what it means?

To explain my current situation, I use jest when writing tests in nodejs.

However, it takes too long to use `ts-jest → @swc/jest`, but if it encounters a string of `` instead of'', an error occurs.

How to fix it?

**Comment by kdy1** [comment] 2022-03-08 04:11
Closing as I couldn't reproduce it.

**Closed by kdy1** 2022-03-08 04:11 UTC
Labels: C-bug
