### ISSUE TITLE
swcx (pure rust CLI) doesn't accept --config

### ISSUE THREAD

**Issue by alexeagle** [swc-project/swc#5172] opened 2022-07-11 00:09 UTC
### Describe the bug

It seems the `--config` flag doesn't work under the rust CLI like it does for the Node.js CLI.

### Input code

```typescript
export const a = "a";
```

### Config

```json
{}
```

### Expected behavior

The --config flag works with the Node.js CLI, so it should work with the rust CLI as well

### Actual behavior

--config seems to be ignored

### Version

1.2.211

### Additional context

repro:

```
$ wget https://registry.npmjs.org/@swc/core-linux-x64-gnu/-/core-linux-x64-gnu-1.2.211.tgz
$ tar -xzvf core-linux-x64-gnu-1.2.211.tgz
$ chmod u+x package/swc
$ echo 'export const a = "a";' > in.ts
$ echo '{}' > .swcrc
$ ./package/swc compile in.ts --config 'module.type=commonjs'
in.ts
export var a = "a";
```

however if the `.swcrc` file has the config, then you get the correct result:

```
$ jq --null-input '.module.type="commonjs"' > .swcrc
$ ./package/swc compile --config-file .swcrc in.ts
in.ts
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "a", {
    enumerable: true,
    get: function() {
        return a;
    }
});
var a = "a"; 
```

**Comment by kwonoj** [comment] 2022-07-11 02:22
This one's dupe of https://github.com/swc-project/swc/issues/4017 , you can see 'config' is not makred as implemented. For missing features, we are using those single tracking issue.

**Closed by kwonoj** 2022-07-11 02:22 UTC
Labels: C-bug
