### ISSUE TITLE
Dynamic imports don't work even with jsc.parser.dynamicImport set to true

### ISSUE THREAD

**Issue by mgol** [swc-project/swc#1271] opened 2020-12-12 23:07 UTC
**Describe the bug**

Dynamic imports don't work even with `jsc.parser.dynamicImport` set to true. Meanwhile, the script below prints:
```
$ node ../../_swc-run.js 
error: import(...) expressions requires `jsc.parser.dynamicImport` to be true
 --> /Users/myuser/test.ts:1:38
  |
1 | export const importSomething = () => import('lodash');
  |                                      ^^^^^^

/Users/myuser/project/node_modules/@swc/core/index.js:116
        return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(options));
                        ^

Error: GenericFailure: failed to process js file
```

**Input code**

Save the following contents as `/Users/myuser/test.ts` (or any other path as long as you update it in the script as well):
```ts
export const importSomething = () => import('lodash');
```
and run the following code:
```js
'use strict';

const fs = require('fs');
const swc = require('@swc/core');

const filePath = '/Users/myuser/test.ts';

const programmaticOptions = {
  jsc: {
    parser: {
      syntax: 'typescript',
      tsx: true,
      jsx: true,
      dynamicImport: true,
    },
    target: 'es2015',
  },
  sourceMaps: false,
  filename: filePath,
  sourceFileName: filePath,
};

const source = fs.readFileSync(filePath, 'utf-8');
const output = swc.transformSync(source, programmaticOptions);

console.log('output', output);
```

**Config**
Config is embedded in the script above.

**Expected behavior**
The code should compile.

**Version**
The version of @swc/core: 1.2.40

**Additional context**

**Comment by kdy1** [comment] 2020-12-21 10:16
You should remove `jsx: true`.

Anyway, this should be error... But it will be fixed by #1244.

**Closed by kdy1** 2020-12-21 10:16 UTC
Labels: C-bug

**Comment by traverse** [comment] 2021-01-08 09:46
Am still running into this using the `swc-loader` with `@swc/core@1.2.43` not sure if I should've made an issue there or just here since this seems related. Tried different parser options but didn't find a working combination.

**Comment by kdy1** [comment] 2021-01-13 15:49
@traverse Can you show me your config?

**Comment by traverse** [comment] 2021-01-13 16:22
@kdy1 The config I was using is as follow
```ts
{
  loader: 'swc-loader',
  options: {
    jsc: {
      target: 'es2015',
      parser: {
        syntax: 'typescript',
        tsx: true,
        dynamicImport: true,
        classProperty: true,
        exportNamespaceFrom: true,
        exportDefaultFrom: true
      }
    }
  }
}
```
Like I said it's using Webpack with the `swc-loader` but I'd expect the config to be the same.

**Comment by kdy1** [comment] 2021-01-13 16:25
@traverse I guess you should remove 
```
        classProperty: true,
        exportNamespaceFrom: true,
        exportDefaultFrom: true
```


Seems like a bug of napi-rs.

**Comment by traverse** [comment] 2021-01-13 16:27
I've tried several configurations also without those properties but it still kept showing the same error, I'll see if I can reproduce it again tomorrow.

**Comment by eliseumds** [comment] 2021-02-12 15:52
> I've tried several configurations also without those properties but it still kept showing the same error, I'll see if I can reproduce it again tomorrow.

Same here.
