### ISSUE TITLE
`jsc.paths` make `require("***.ts")` extension in some output file

### ISSUE THREAD

**Issue by kyoungduck** [swc-project/swc#4601] opened 2022-05-10 06:48 UTC
### Describe the bug

`js.paths` option generate `.ts` extension in some `require()`. If I remove `js.paths` option, this doesn't occurred.

### Input code

```typescript
main.ts

//...
import { AppModule } from "./app.module";
//...
```
```


### Config

```json
{
  "sourceMaps": true,
  "module": {
    "type": "commonjs",
    "strict": true
  },
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "keepClassNames": true,
    "baseUrl": "./",
    "paths": {
      "~/*": ["./src/*"],
      "@company/*": ["./src/company/*"]
    }
  }
}
```
```


### Playground link

_No response_

### Expected behavior

transfile like this
```
//...
var _appModule = require("./app.module");
//...
```

### Actual behavior

result
```
//...
var _appModule = require("./app.module.ts");
//...
```

So I can see this error.

```
/Users/peter/Documents/project/playground/nestjs-swc/.pnp.cjs:18265
      Error.captureStackTrace(firstError);
            ^

Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: /Users/peter/Documents/project/playground/nestjs-swc/dist/app.module.ts
Not found: /Users/peter/Documents/project/playground/nestjs-swc/dist/app.module.ts
Not found: /Users/peter/Documents/project/playground/nestjs-swc/dist/app.module.ts.js
Not found: /Users/peter/Documents/project/playground/nestjs-swc/dist/app.module.ts.json
Not found: /Users/peter/Documents/project/playground/nestjs-swc/dist/app.module.ts.node

Require stack:
- /Users/peter/Documents/project/playground/nestjs-swc/dist/main.js
    at Function.require$$0.Module._resolveFilename (/Users/peter/Documents/project/playground/nestjs-swc/.pnp.cjs:18265:13)
    at Function.require$$0.Module._load (/Users/peter/Documents/project/playground/nestjs-swc/.pnp.cjs:18119:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/peter/Documents/project/playground/nestjs-swc/dist/main.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require$$0.Module._extensions..js (/Users/peter/Documents/project/playground/nestjs-swc/.pnp.cjs:18309:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.require$$0.Module._load (/Users/peter/Documents/project/playground/nestjs-swc/.pnp.cjs:18132:22)
```

### Version

@swc/cli: 0.1.57, @swc/core: 1.2.181

### Additional context

I upload example code in here https://github.com/kyoungduck/nests-swc-jsc-path

Clone this, and run `yarn build:swc`. Then you can see same issue.

**Comment by kdy1** [comment] 2022-05-10 06:49
Closing as duplicate of https://github.com/swc-project/swc/issues/4601

**Closed by kdy1** 2022-05-10 06:49 UTC
Labels: C-bug

**Comment by kyoungduck** [comment] 2022-05-10 06:54
@kdy1 I think you linked https://github.com/swc-project/swc/issues/4601 (same issue)

**Comment by kdy1** [comment] 2022-05-10 06:58
Oh my bad
https://github.com/swc-project/swc/issues/4585 is the one
