### ISSUE TITLE
Bug in _setPrototypeOf/_getPrototypeOf helper, possibly others

### ISSUE THREAD

**Issue by sabberworm** [swc-project/swc#1555] opened 2021-01-14 07:18 UTC
The _setPrototypeOf helper

```javascript
export default function _setPrototypeOf(o, p) {
  _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return _setPrototypeOf(o, p);
}
```

gets transpiled to

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _setPrototypeOf(o, p) {
    _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf1(o1, p1) {
        o1.__proto__ = p1;
        return o1;
    };
    return _setPrototypeOf1(o, p);
}
exports.default = _setPrototypeOf;
```

(copied directly from my `node_modules/@swc/helpers/lib/_set_prototype_of.js`).

This seems to be caused by name mingling `_setPrototypeOf` vs. `_setPrototypeOf1`. Ultimately, it may be a bug in swc, I don’t know; but I’m filing it here because it affects the transpiled helpers as present in the published `@swc/helpers` npm package.

At least the `_getPrototypeOf` helper is also affected,  I have not checked others.

I guess the problem can be resolved by using an explicit local variable:

```javascript
export default function _setPrototypeOf(o, p) {
  const fn = Object.setPrototypeOf || function setPrototypeOf(o, p) {
    o.__proto__ = p;
    return o;
  };

  return fn(o, p);
}
```

**Comment by grimly** [comment] 2021-04-08 12:06
Hello,

I am tracking down a similar bug (I caught it on `wrapNativeSuper`) but **it did not come from `@swc/core`**.
@kdy1 , can you remove the closing keyword from #1550 ? There is effectively something wrong around these helper functions and I would need more time to investigate it.

And so far, the solution I would have in mind so far is to refactor this way:

```javascript
export default Object.setPrototypeOf || function _setPrototypeOf(o, p) {
  o.__proto__ = p;
  return o;
};
```

**Comment by kdy1** [comment] 2021-04-08 12:16
@grimly I removed it.

**Comment by grimly** [comment] 2021-04-08 13:41
Hello again,

I now got my hand on it.

**Describe the bug**

This happen when the code from `@swc/helpers` gets though `swc` itself. Any code that exports a function that edits itself has the same issue

I've annotated the code below with numbers on all occurrence of the `test` name.

`swc` groups 1 and 2 as the first instance of `test` and 3 and 4 as the other. But in fact, the 4th occurrence should be grouped with 1 and 2 while the 3rd is just a function name that might even be discarded.

**Input code**

```javascript
export default function _test/*1*/() {
  _test/*2*/ = function _test/*3*/() {
    console.log("Hello");
  };

  return _test/*4*/();
}
```

**Config**

(This is not a bad input but the default configuration)
```json
{}
```

**Observed code**

```javascript
export default function _test() {
    _test = function _test1() {
        console.log("Hello");
    };
    return _test1();
};
```

**Expected code**

```javascript
export default function _test() {
    _test = function _test1() { // _test1 carry actually no meaning, it could be discarded
        console.log("Hello");
    };
    return _test();
};
```

**Version**
The version of @swc/core: `1.2.51`

**Additional context**
I first thought it was not from `@swc/core` because it **MUST** be a default export statement with function declaration.

The code below, while it has the same behavior, does NOT reproduce this issue:


```javascript
function _test() {
  _test = function _test() {
    console.log("Hello");
  };

  return _test();
}
export default _test;
```

**Comment by kdy1** [comment] 2021-04-08 13:42
Thank you for investigation!

**Comment by grimly** [comment] 2021-04-08 14:07
Given the commit `1841168`, I think #1550 fixes (or at least verify) this issue.

**Comment by kdy1** [comment] 2021-04-08 14:38
@grimly Thanks! Closing as verified by https://github.com/swc-project/swc/pull/1550

(This is actually fixed by recent resolver bugfix)

**Closed by kdy1** 2021-04-08 14:38 UTC

**Comment by sabberworm** [comment] 2021-04-08 16:19
Thanks @kdy1 for verifying this as fixed in swc/core. But I originally opened this issue on swc/helpers precisely because I wanted it fixed there. Will there a follow-up story to publish a new swc/helpers package on NPM built with a recent swc/core that has the correct output?

**Comment by kdy1** [comment] 2021-04-09 07:00
@sabberworm Of course. I'll publish a new version once v1.2.52 is released.
