### ISSUE TITLE
Plugin fails on arm processor

### ISSUE THREAD

**Issue by DiFuks** [swc-project/swc#7255] opened 2023-04-11 17:18 UTC
Versions:
```
"@swc/plugin-styled-components": "1.5.59",
"@swc/core": "1.3.49"
```
Error:
```
Caused by:
    0: failed to invoke `/Users/difuks/WebstormProjects/kiosk/src/frontend/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/difuks/WebstormProjects/kiosk/src/frontend/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob
```

With versions:
```
"@swc/plugin-styled-components": "1.5.36",
"@swc/core": "1.3.37"
```
Works fine

**Comment by kwonoj** [comment] 2023-04-13 03:09
Potentially dupe of https://github.com/swc-project/swc/issues/7238

**Comment by pofey** [comment] 2023-04-13 05:03
I encountered the same error on the M2 Max processor.

**Comment by khanakia** [comment] 2023-04-17 14:30
I am having the same issue 
```
node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
[dev:storybook]     1: RuntimeError: out of bounds memory access
```

**Comment by kwonoj** [comment] 2023-04-17 15:18
Please refrain duplicated comments to the main issue unless there isn't specific details need to be included. It makes hard to manage issues.

**Comment by Codex-** [comment] 2023-04-19 05:34
Reproduction steps, when compiling the material-ui repository: https://github.com/swc-project/plugins/issues/176

**Comment by kdy1** [comment] 2023-04-19 05:45
Filed https://github.com/wasmerio/wasmer/issues/3783

**Comment by kwonoj** [comment] 2023-04-19 05:58
@kdy1 https://github.com/wasmerio/wasmer/issues/3764 😅

**Comment by kdy1** [comment] 2023-04-19 05:59
Oops my bad. I'll close it.

**Comment by kdy1** [comment] 2023-04-20 00:58
Can you try `v1.3.52`? We updated wasmer

**Comment by Codex-** [comment] 2023-04-20 02:02
Tried the test with `1.3.52`, same OOM error

**Comment by klemenoslaj** [comment] 2023-04-20 12:17
The same is happening with `@swc/plugin-emotion`.

**Closed** 2023-04-25 04:33 UTC

**Comment by khanakia** [comment] 2023-05-14 11:45
@DiFuks were you able to fix the issue with `styled-components` as i am getting the same error 

```
VITE v4.3.5  ready in 108 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.41/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/khanakia/D1/www/projects/sea/sea_lexical/src/App.tsx")'

Caused by:
    0: failed to invoke `/Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.46/src/plugin.rs:219:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/khanakia/D1/www/projects/sea/sea_lexical/src/App.tsx")'

Caused by:
    0: failed to invoke `/Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: RuntimeError: unreachable
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.41/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/khanakia/D1/www/projects/sea/sea_lexical/src/App.tsx")'

Caused by:
    0: failed to invoke `/Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: RuntimeError: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.46/src/plugin.rs:219:14
5:13:15 PM [vite] Internal server error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/khanakia/D1/www/projects/sea/sea_lexical/src/App.tsx")'

Caused by:
    0: failed to invoke `/Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm` as js transform plugin at /Users/khanakia/D1/www/projects/sea/sea_lexical/node_modules/@swc/plugin-styled-components/swc_plugin_styled_components.wasm
    1: RuntimeError: unreachable
```

**Comment by Codex-** [comment] 2023-05-14 21:35
@khanakia  If you control the package versions directly then bump those, if they're dependencies of your dependencies then you can add them as dev deps then remove them to have your lock updated that way. Should resolve your issue

**Comment by khanakia** [comment] 2023-05-15 04:44
@Codex- I do not understand why I have to bump versions and how it will solve the issue? 

I am using the latest version of all the packages

```
"vite": "^4.3.5",
"@swc/plugin-styled-components": "^1.5.62",
"styled-components": "^6.0.0-rc.1",
"@vitejs/plugin-react-swc": "^3.3.1",
"react": "^18.2.0",
```

**Comment by Codex-** [comment] 2023-05-15 07:15
Because a release was made to resolve the issue, thus the new version. You are currently using an old version of `@swc/plugin-styled-components` too.

You need to refresh your package lock for the swc packages from the sounds of it.

The relevant packages in your post are these:
```
"@swc/plugin-styled-components": "^1.5.62",
"@vitejs/plugin-react-swc": "^3.3.1",
```

The path of least resistance is to update to the newer versions which resolved the errors described in this issue. Or don't, and live with the error 😅

**Comment by khanakia** [comment] 2023-05-15 13:10
@Codex- Thanks. I did use `ncu -u`  already before posting the message on GitHub but somehow it missed the latest version
