### ISSUE TITLE
Decorator metadata and interfaces. 

### ISSUE THREAD

**Issue by smialy** [swc-project/swc#1839] opened 2021-06-21 20:37 UTC
**Describe the bug**

**Input code**
`interfaces.ts`
```typescript
export interface IContext {
    update(): void;
}
```

`main.ts`
```typescript
import { IContext } from './interfaces';

function Activator() {
    // return (target: any, name: string | symbol): void => {
    //     // ....
    // };
}

class Foo {
    @Activator()
    run(ctx: IContext) {}
}
```

**Config**
`.swcrc`
```json
{
    "jsc": {
      "loose": true,
      "target": "es2020",
      "parser": {
        "syntax": "typescript",
        "decorators": true
      },
      "transform": {
        "legacyDecorator": true,
        "decoratorMetadata": true
      }
    }
  }
```

Command:
```bash
swc src/main.ts -o main.js
```
generate js code:
```javascript
function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) {
   // ...
}
var _class, _dec, _dec1, _dec2;
import { IContext } from './interfaces';
function Activator() {
// return (target: any, name: string | symbol): void => {
//     // ....
// };
}
let Foo = ((_class = class Foo1 {
    run(ctx) {
    }
}) || _class, _dec = Activator(), _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", Function), _dec2 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:paramtypes", [
    typeof IContext === "undefined" ? Object : IContext
]), _applyDecoratedDescriptor(_class.prototype, "run", [
    _dec,
    _dec1,
    _dec2
], Object.getOwnPropertyDescriptor(_class.prototype, "run"), _class.prototype), _class);
```

**Current behavior**
SWC generate code with interface: `IContext`. It should skip import:
```javascript
import { IContext } from './interfaces';
``` 
and remove all `IContext` appearance.  
```typescript
typeof IContext === "undefined" ? Object : IContext
```

**Version**
The version of: 
@swc/cli: 0.1.46
@swc/core: 1.2.61

**Comment by kdy1** [comment] 2021-06-22 02:03
Duplicate of https://github.com/swc-project/swc/issues/1160

**Closed by kdy1** 2021-06-22 02:03 UTC
Labels: C-bug
