### ISSUE TITLE
Double Nullish coalescing assignment outputs an error

### ISSUE THREAD

**Issue by EvilaMany** [swc-project/swc#7290] opened 2023-04-18 22:26 UTC
### Describe the bug

When I do two nullish coalescing assignments on object second one been marked as incorrect with strange error
If I swap calls, the error will remain on exactly second call, doesn't matter which one of them it's now. 
When I remove second call, or rewrite it by handy check and assign (using if) - error gets away. 
With babel there are no such an error

Interesting fact. The error appears only on first page load. After HMR error goes away

### Input code

```typescript
filter = clone(initialFilter)

  filter.start_point ??= {
    location: null,
    radius: null
  }
  
  filter.end_point ??= {
    location: null,
    radius: null
  }
```

### Config

```json
{
  "env": {
    "targets": "> 0.25%, not dead"
  },
   "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": false,
        "dynamicImport": false,
        "privateMethod": false,
        "functionBind": false,
        "exportDefaultFrom": false,
        "exportNamespaceFrom": false,
        "decorators": false,
        "decoratorsBeforeExport": false,
        "topLevelAwait": false,
        "importMeta": false
      },
      "transform": null,
      "target": "es5",
      "loose": false,
      "externalHelpers": true,
      // Requires v1.2.50 or upper and requires target to be es2016 or upper.
      "keepClassNames": false
    },
}
```

### Expected behavior

Double use of the operator is possible

### Actual behavior

<img width="944" alt="image" src="https://user-images.githubusercontent.com/43150567/232916673-e155c6f7-1d07-4f9a-af78-54642432c951.png">
<img width="949" alt="image" src="https://user-images.githubusercontent.com/43150567/232918238-f9bed766-4eb7-4daa-9d17-bedc4049cc8b.png">

### Version

0.4.14

### Additional context

The code is placed in package of monorepo. Package been loaded and transpiled by nextjs 13.3 (using built in transpilePackages option).

**Comment by kdy1** [comment] 2023-04-19 06:13
Closing as I can't reproduce.

https://play.swc.rs/?version=1.3.51&code=H4sIAAAAAAAAA0vLzClJLVKwVUjOyc9L1cjMyyzJTMxxA4tqcnEpKKSBmXrFJYlFJfEF%2BZl5JQr29rYK1UApBYWc%2FOTEksz8PCuFvNKcHB2wWFFiSmZpMUQEKFALxAhjUvNSyDIEAPF4Ap%2BnAAAA&config=H4sIAAAAAAAAA2WQPQ6DMAyF954CZe6AGHuCLj2EFQwKyp9sI4EQd29CQ6jEFn%2FPec%2F29mgaNbFWr2ZLz1REIEaqdSK8eoElESVrRNZkoqjnqfaoA4EE4tQhNOMh7D9dOePNsP676eAiIefuASxjNXLgR4t3HPr5wDdvXATJg32jjVjjiyhAI0oeGrlru1Y9ysdrpJqjDH%2FOlAvW4HKYvHz2Swu44CcujvsX2Fj7WUMBAAA%3D

I'll reopen once you provide a reproduction

**Comment by kdy1** [comment] 2023-04-19 06:14
Nevermind. I misread the output

**Comment by kdy1** [comment] 2023-04-20 02:08
I concluded that this is not a bug of swc.

**Comment by kdy1** [comment] 2023-04-20 02:10
Please provide a correct repro case

**Closed** 2023-04-20 02:10 UTC
Labels: C-bug
