### ISSUE TITLE
Building plugin with `swc_core` 0.88.* leads to segfault / bus error (0.87.* working)

### ISSUE THREAD

**Issue by Codex-** [swc-project/swc#8540] opened 2024-01-23 01:20 UTC
### Describe the bug

I author [`swc-plugin-import-meta-env`](https://github.com/Codex-/swc-plugin-import-meta-env) and have found when bumping the `swc_core` crates to `0.88.*` the built wasm causes a segfault when used with `@swc/jest`

[This issue](https://github.com/Codex-/swc-plugin-import-meta-env/issues/33) was raised which provided this minimal reproduction: https://github.com/HermanBilous/test-swc-jest

The plugin contains this for `swc_core`:
```toml
[dependencies]
swc_core = { version = "0.88.*", features = [
    "ecma_plugin_transform",
    "trace_macro",
] }
```

When reverting `swc_core` to `0.87.*` the plugin works as expected again.

### Playground link (or link to the minimal reproduction)

https://github.com/Codex-/swc-plugin-error

### Expected behavior

No bus error or segfault

### Actual behavior

After reverting, renovate tried to bump this again which was blocked by the integration tests I added:
https://github.com/Codex-/swc-plugin-import-meta-env/actions/runs/7619428112/job/20752472293?pr=36

With `SWC_LOG=info RUST_BACKTRACE=1`
```
➜  test-swc-jest git:(main) ✗ SWC_LOG=info RUST_BACKTRACE=1 npx jest

 RUNS  src/add.test.ts
   INFO  Done in 13.565917ms, kind: "perf"
    at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_timer-0.21.14/src/lib.rs:32
    in Compiler.parse
    in parse_js_as_input
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(/Users/alexmiller/dev/issue/test-swc-jest/src/add.test.ts)

[1]    66485 bus error
```

Running multiple times gives different errors

```
> SWC_LOG=info RUST_BACKTRACE=1 npx jest --config ./tests/integration/jest.config.cjs --no-cache --runInBand


 RUNS  tests/integration/src/typescript.test.ts
   INFO  Done in 248.700042ms, kind: "perf"
    at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_timer-0.21.14/src/lib.rs:32
    in Compiler.parse
    in parse_js_as_input
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(/Users/alexmiller/dev/issue/swc-plugin-error/tests/integration/src/typescript.test.ts)

sh: line 1: 74251 Segmentation fault: 11  pnpm run test:integration
```

```
memory allocation of 3117855127680 bytes failed
```

```
75266 Bus error: 10
```

### Version

1.3.105

**Comment by kwonoj** [comment] 2024-01-23 01:21
I think this is dupe of https://github.com/swc-project/swc/issues/7479

**Comment by kdy1** [comment] 2024-01-23 01:22
AST layout of 0.88.x is different.
Please see https://swc.rs/docs/plugin/selecting-swc-core

**Closed by kdy1** 2024-01-23 01:22 UTC
Labels: C-bug

**Comment by Codex-** [comment] 2024-01-23 03:18
Excellent, thanks @kdy1

**Comment by kireevmp** [comment] 2024-01-26 23:45
While it's understandable the breaking changes in AST will appear, is there an existing/planned way for `swc` or plugin authors to notify users that the AST version does not match and the plugin will fail?

A `SEGFAULT` and `BUS ERROR` isn't the best error message we can provide to the user

**Comment by kwonoj** [comment] 2024-01-26 23:50
Refer pinned issue.

**Comment by Codex-** [comment] 2024-01-27 03:35
@kireevmp to be fair, plugins are still experimental

**Comment by kireevmp** [comment] 2024-01-27 18:22
True, @Codex-, and I appreciate all the team's work to get even to this point. Making plugins backward-compatible would be a great feat, but that's not what I'm talking about here

Is allowing the plugin to fail gracefully when the AST version mismatches possible? It would go a long way if we could show a meaningful message, like
> `plugin-name@old-version` is incompatible with your `@swc/core`, please install `plugin-name@new-version`
