### ISSUE TITLE
const variables redeclared in try-catches

### ISSUE THREAD

**Issue by jdalton** [swc-project/swc#4294] opened 2022-04-09 15:07 UTC
### Describe the bug

In 1.2.164 I'm seeing const variables redeclared in try-catches.
This is a reduced example to explain what I'm seeing:

Input:
```js
const a = b;
try {
  foo(a);
} catch {}
```
Output:
```js
const a = b;
try {
  var a;
  a = a;
  foo(a);
} catch {}
```
Config is:
```js
{
  compress: {
      keep_infinity: true,
      typeofs: false,
  },
  format: {
      // The terser options are eval'ed by rollup-plugin-terser
      // so we cannot reference outer scope variables.
      // https://github.com/TrySound/rollup-plugin-terser/blob/v7.0.2/transform.js#L4
      comments: Function('_outputStream, comment', `
          return comment.type === 'comment2' &&
              /^\\s*${regexpEscapedIdentifierMarker}\\s*$/.test(comment.value);
      `),
      wrap_func_args: false,
  },
  mangle: {
      keep_classnames: true,
      keep_fnames: true,
      reserved: [UNMINIFIED_FLAG_NAME],
  },
  module: true,
}
```

### Expected behavior

No rename of the const vars

### Version

1.2.164

**Comment by jdalton** [comment] 2022-04-09 15:26
This repro was referencing a `foo` that was defined several scopes up. By inlining the `foo` call into the try-catch the var rename stopped.

**Comment by jdalton** [comment] 2022-04-12 02:11
It looks like it's also redeclaring `let` vars:
```js
export default function func(value) {
  let o = value;
  if (o) {
    return o;
  }
  let other;
  o = foo();
  ```
  is becoming
  ```js
  export default function func(value) {
  let o = value;
  if (o) {
    return o;
  }
  let other, o,o;
  o = foo();
  ```

**Comment by kdy1** [comment] 2022-04-12 02:59
I can't reproduce this.
Please post valid config. `Function` is not supported

**Comment by kdy1** [comment] 2022-08-15 14:24
Closing as not enough information provided.
Please open a new issue with enough information

**Closed by kdy1** 2022-08-15 14:24 UTC
Labels: C-bug, A-minifier
