### ISSUE TITLE
[minifier] closing tags should be escaped

### ISSUE THREAD

**Issue by layershifter** [swc-project/swc#9723] opened 2024-11-08 08:37 UTC
### Describe the bug

We use Webpack + `html-webpack-plugin` + `terser-webpack-plugin` with SWC as a minifier.

We inline some JS into a `.ejs` template, basically:

```html
<body>
  <script><%= someVar =></script>
</body>
```

It works fine with Terser & esbuild as minifiers, but breaks on SWC.

I traced the problem and it looks that SWC does not escape tags and this breaks the template as `someVar` contains `+ </script>`, so we get:

```html
<body>
  <script>"" + "</script>";</script>
  <!--          ⬆️ a closing tag 💣 -->
</body>
```

### Input code

```typescript
export const foo = "</script>"
```

### Config

```json
N/A
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.9.1&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIy89XsFVQstEvTi7KLCixUwIAa3ctVB4AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAxE9zkF8rqLKIsueoceAlEnIuIn7EhFUe5eIJC2O%2FuNRzPeByFgJQUPsecxL0FGwnjtmVByLN%2BZAKeApKIODLeuMhWJ44aVHKcALOOCXExI0ziNzQDGe8KMZ2kIG7Pa6Tn9RipvQ0Si%2F8NyKt1iLv%2BZOLRUsP61VbG9UuqeDe7wPephpXIlmp7dWN84Pk9GmjkVAQAA

### SWC Info output

@swc/core@1.9.1

### Expected behavior

SWC should escape closing tags like Terser and esbuild:

```
export const foo = "<\/script>"
```

## Terser

<img width="761" alt="image" src="https://github.com/user-attachments/assets/e102b3c9-180a-46e6-b878-f1a5d1ff4901">

## esbuild

[REPL](https://esbuild.github.io/try/#dAAwLjI0LjAAAGV4cG9ydCBjb25zdCBmb28gPSAiPC9zY3JpcHQ+Ig)

<img width="757" alt="image" src="https://github.com/user-attachments/assets/ac37ef2d-162b-4fcc-b716-a462378709c4">

### Actual behavior

SWC produces:

```
export const foo = "</script>"
```

[REPL](https://play.swc.rs/?version=1.9.1&code=H4sIAAAAAAAAA0utKMgvKlFIzs8rLlFIy89XsFVQstEvTi7KLCixUwIAa3ctVB4AAAA%3D&config=H4sIAAAAAAAAA1WPSw7DIAxE9zkF8rqLKIsueoceAlEnIuIn7EhFUe5eIJC2O%2FuNRzPeByFgJQUPsecxL0FGwnjtmVByLN%2BZAKeApKIODLeuMhWJ44aVHKcALOOCXExI0ziNzQDGe8KMZ2kIG7Pa6Tn9RipvQ0Si%2F8NyKt1iLv%2BZOLRUsP61VbG9UuqeDe7wPephpXIlmp7dWN84Pk9GmjkVAQAA)

### Version

@swc/core@1.9.1

**Comment by kdy1** [comment] 2024-11-08 08:52
Duplicate of https://github.com/swc-project/swc/issues/7602

**Closed by kdy1** 2024-11-08 08:52 UTC
Labels: C-bug

**Comment by kdy1** [comment] 2024-11-11 01:36
https://github.com/swc-project/swc/pull/9729 will implement this
