### ISSUE TITLE
Setting `jsc.minify: {}` removes comments regardless of `minify: false` and `jsc.parser.preserveAllComments: true`

### ISSUE THREAD

**Issue by xnuk** [swc-project/swc#4387] opened 2022-04-20 23:54 UTC
### Describe the bug

There's a case that comment should be preserved like [GreaseMonkey user scripts](https://wiki.greasespot.net/Metadata_Block#Syntax). And, um, yes its metadata block wrapped in between `// ==UserScript==` and `// ==/UserScript==`, not block comments. swc did remove this anyway. After digging some hours, I found `jsc.minify: { ... }` (not `minify: false`) removes comments inside of my code.

### Input code

```typescript
// This code will make my senpai notice me
document.write([
  'uwu',
  'senpai',
  'notice',
  'me',
].join(' '))
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "preserveAllComments": true
    },
    "minify": {},
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.168&code=H4sIAAAAAAAAAyXLwQqAIBAE0HtfMTcTIn%2BmW3QQW2irdSMV6e8rPM1jmHEO08YJQVdC5fOE%2BIMgDxLFyzOiZg5fQd2qoQjFPNabM%2FVzB5hSixl%2BtHVzuzTLn8u4K8fewFj7AijUiKdxAAAA&config=H4sIAAAAAAAAA02MMQ7DIBAE%2F7I1RUThgi7KSxA5R1gHRndHFGT57zGp0q00O3Ng04RwoEVRkrl0VIsfBFAqUZPkZnBoQhd%2F0535sZdC1RRhjax0OpRc8zoQamd2sCgvshlQf%2FMe87A%2FO9Os22j0Qwv%2BRJNO5xfwYBTvjAAAAA%3D%3D

### Expected behavior

```javascript
// This code will make my senpai notice me
document.write([
    'uwu',
    'senpai',
    'notice',
    'me', 
].join(' '));
```

### Actual behavior

```javascript
document.write([
    'uwu',
    'senpai',
    'notice',
    'me', 
].join(' '));
```

### Version

`@swc/core`: 1.2.170

### Additional context

- Removing `jsc.minify` property or setting as `null` fixes the problem.
- Same thing occurs on `jsc.parser.syntax === 'typescript'`.
- [`jsc.parser.preserveAllComments` is documented](https://swc.rs/docs/configuration/compilation#jscpreserveallcomments) but toggling this value does not help removing/keeping comments afaik.

**Comment by kdy1** [comment] 2022-04-21 01:30
There's option in `format` and `jsc` is not related to minify at all

2022년 4월 21일 (목) 오전 8:54, 즈눅 ***@***.***>님이 작성:

**Comment by kdy1** [comment] 2022-04-21 01:35
Closed as this is a duplicate of a closed issue

**Closed** 2022-04-21 01:35 UTC
Labels: C-bug

**Comment by xnuk** [comment] 2022-04-21 01:38
> There's option in `format` and `jsc` is not related to minify at all

1. What is `format` option?
2. if `jsc` is not related to minify, then why `{jsc: {minify: {}}` removes comment while `{jsc: {}}` preserves?

**Comment by xnuk** [comment] 2022-04-21 01:54
\* I put wrong playground link, so I edited

**Comment by xnuk** [comment] 2022-04-21 01:57
> There's option in `format` and `jsc` is not related to minify at all

1. What is `format` option?
2. `{minify: false, jsc: {minify: {}}}` does remove comments, while `{minify: false, jsc: {}}` preserves.

**Comment by xnuk** [comment] 2022-04-21 02:03
![image](https://user-images.githubusercontent.com/3071003/164356697-a6724cff-2590-4a1f-bd76-c8dac05ee2b0.png)

This is a test case, which can apply with `git apply ./path/to/file.diff`:

```diff
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/.swcrc b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/.swcrc
new file mode 100644
index 000000000..785c8fe0f
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/.swcrc
@@ -0,0 +1,14 @@
+{
+  "jsc": {
+    "parser": {
+      "syntax": "ecmascript",
+      "preserveAllComments": true
+    },
+    "minify": {},
+    "target": "es2022"
+  },
+  "module": {
+    "type": "es6"
+  },
+  "minify": false
+}
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/index.js b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/index.js
new file mode 100644
index 000000000..03c7d65d7
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/input/index.js
@@ -0,0 +1,2 @@
+// This is a comment
+console.log("");
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/output/index.js b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/output/index.js
new file mode 100644
index 000000000..03c7d65d7
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/1-with-minify-object/output/index.js
@@ -0,0 +1,2 @@
+// This is a comment
+console.log("");
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/.swcrc b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/.swcrc
new file mode 100644
index 000000000..5a59364b7
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/.swcrc
@@ -0,0 +1,13 @@
+{
+  "jsc": {
+    "parser": {
+      "syntax": "ecmascript",
+      "preserveAllComments": true
+    },
+    "target": "es2022"
+  },
+  "module": {
+    "type": "es6"
+  },
+  "minify": false
+}
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/index.js b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/index.js
new file mode 100644
index 000000000..03c7d65d7
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/input/index.js
@@ -0,0 +1,2 @@
+// This is a comment
+console.log("");
diff --git a/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/output/index.js b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/output/index.js
new file mode 100644
index 000000000..03c7d65d7
--- /dev/null
+++ b/crates/swc/tests/fixture/issues-4xxx/issue-4387/2-without-minify-object/output/index.js
@@ -0,0 +1,2 @@
+// This is a comment
+console.log("");
```

**Comment by xnuk** [comment] 2022-04-21 02:51
> > There's option in `format` and `jsc` is not related to minify at all
> 
> 1. What is `format` option?

oh I found... there is `jsc.minify.format` option... which is terser's format option... which is undocumented and [`types.ts` is not updated](https://github.com/swc-project/swc/blob/a4c708858e37186f85aec325838766e7c6db8c05/node-swc/src/types.ts#L17-L38)...

But still I cannot found why swc references `config.jsc.minify` even if `config.minify: false` yet

**Comment by kdy1** [comment] 2022-04-21 03:24
I thought you were talking about minify(), it's my bad

2022년 4월 21일 (목) 오전 11:51, 즈눅 ***@***.***>님이 작성:

**Comment by kdy1** [comment] 2022-04-21 03:57
It's jsc minify.format and it defaults to removing comments

2022년 4월 21일 (목) 오후 12:24, 강동윤 ***@***.***>님이 작성:

**Comment by xnuk** [comment] 2022-04-22 10:35
> It's jsc minify.format and it defaults to removing comments

even if `config.minify: false`? (not`config.jsc.minify`)

**Comment by kdy1** [comment] 2022-04-22 10:39
Yes if `jsc.minify` is `{}`, which is an alias of `true` in general.

**Comment by kdy1** [comment] 2022-04-22 10:39
I think it's better to have a document for it, though

**Comment by kdy1** [comment] 2022-04-30 12:26
I documented it
https://github.com/swc-project/website/commit/7b643838779db47c9329c0efba3b2435eef92584
