### ISSUE TITLE
@swc/jest Cannot find module 'regenerator-runtime'

### ISSUE THREAD

**Issue by doums** [swc-project/swc#2685] opened 2021-11-08 15:33 UTC
### Describe the bug

Hi,

I'm not sure if this is related to `@swc/jest`. But I transpile my TS code base using swc, and it works great, except when I try to run my test using `jest`. I get the same error for all my test files:

```shell
 FAIL  src/graphql/queries/images/images.test.ts
  ● Test suite failed to run

    Cannot find module 'regenerator-runtime' from 'graphql/queries/images/images.test.ts'

      1 | import { ApolloServer } from 'apollo-server-express';
    > 2 | import prisma from 'image-service-prisma';
        |                                                  ^
      3 | import gql from 'graphql-tag';
      4 | import log from '@go-aos/logger';
      5 | import schema from '../../../nexus';

      at Resolver.resolveModule (../../../node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (graphql/queries/images/images.test.ts:2:50)
```

Jest config:

```javascript
module.exports = {
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'core', 'node'],
  modulePathIgnorePatterns: ['dist'],
  testEnvironment: 'node',
  testRegex: '(/__tests__/.*|(\\.|/)test)\\.tsx?$',
  transform: {
    '^.+\\.(t|j)s$': '@swc/jest',
  },
  setupFiles: ['dotenv/config']
};
```

The versions I use (uptodate)
```
    "@swc/cli": "^0.1.51",
    "@swc/core": "^1.2.106",
    "@swc/helpers": "^0.2.13",
    "@swc/jest": "^0.2.5",
    "@types/jest": "^27.0.1",
    "jest": "^27.1.0",
    "typescript": "^4.4.2"
```

NOTE: Before I switch from tsc to swc, the tests were working as expected.

EDIT: Installing `regenerator-runtime` fix the problem. But I don't know if this is normal that my setup with @swc/jest needs `regenerator-runtime` to work properly ?

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true
    },
    "target": "es2020",
    "externalHelpers": true
  },
  "module": {
    "type": "commonjs"
  },
  "minify": true,
  "sourceMaps": true
}
```

### Expected behavior

The test suits should run.

### Version

    "@swc/cli": "^0.1.51",     "@swc/core": "^1.2.106",     "@swc/helpers": "^0.2.13",     "@swc/jest": "^0.2.5",

**Comment by doums** [comment] 2021-11-08 17:45
Installing regenerator-runtime fix the problem. But I don't know if this is normal that my setup with @swc/jest needs regenerator-runtime to work properly ?

**Comment by kdy1** [comment] 2022-05-30 06:47
Closing this as it's not a bug.
You need `regenerator-runtime` if you are targetting old version

**Closed by kdy1** 2022-05-30 06:47 UTC
Labels: C-bug
