### ISSUE TITLE
Line from website example does not compile

### ISSUE THREAD

**Issue by maor-benami** [swc-project/swc#4858] opened 2022-05-31 19:38 UTC
```plugin: (m) => new JSXPlugin().visitProgram(m)```

Does not compile using `swc` and `syntax: 'typescript'`.
Could not find out why, anyone can help?

```
Error: Method visitTsType not implemented.
```

**Comment by kwonoj** [comment] 2022-05-31 20:31
Dupe of https://github.com/swc-project/swc/issues/4648.

Please note JS plugin is not complete, as well as not actively maintained at this moment. We recommend to use new experimental wasm plugin instead.

**Closed by kwonoj** 2022-05-31 20:31 UTC
