### ISSUE TITLE
Behavior changed when using swc-experimental transpiler with ts-node

### ISSUE THREAD

**Issue by huan** [swc-project/swc#3755] opened 2022-02-26 16:19 UTC
### Describe the bug

We found that the Nestjs with the swc transpiler have some compatible problems.

## The Problem

When we are using the swc as the transpiler settings in the `tsconfig.json`

```json
{
  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental",
  },
}
```

We will get the below error:

```sh
$ ./statuspage.saga.spec.ts 
file:///home/huan/git/wechaty/friday/src/wechaty-repository/wechaty.repository.ts:2
import { Injectable, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
                     ^^^^^^^^^^^^^^^
SyntaxError: Named export 'OnModuleDestroy' not found. The requested module '@nestjs/common' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@nestjs/common';
const { Injectable, OnModuleDestroy, OnModuleInit } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

## The Workaround

Because we are extending the `tsconfig.json` from `@chatie/tsconfig`, we add a `ts-node.transpiler = ''` to remove the swc transpiler, and then the system work as expected:

```diff
{
  "ts-node": {
    // It is faster to skip typechecking.
    // Remove if you want ts-node to do typechecking.
    "transpileOnly": true,
-     "transpiler": "ts-node/transpilers/swc-experimental",
+     "transpiler": "",  // <- set it to empty, or make sure it does not set in the tsconfig.json
  },
}
```

### Input code

```typescript
This branch can reproduce this problem: (sorry I have no minimum reproducible code because I'm not familiar with those codes)

- https://github.com/wechaty/friday/tree/836197fff86ac6dc18affb1303eeb2f89b0defa5
```

### Config

```json
n/a
```

### Expected behavior

The code should be able to run with `ts-node` with `transpiler: "ts-node/transpilers/swc-experimental"`,

### Actual behavior

SyntaxError: Named export 'OnModuleDestroy' not found. The requested module '@nestjs/common' is a CommonJS module, which may not support all module.exports as named exports.

### Version

1.2.112

### Additional context

```json
    "@swc/core": "^1.2.112",
    "@swc/helpers": "^0.2.14",
```

I have also created an issue on my own project:

- https://github.com/wechaty/friday/issues/114

**Comment by kdy1** [comment] 2022-02-27 07:10
Closing as I think it's duplicate of another issue

**Closed by kdy1** 2022-02-27 07:10 UTC
Labels: C-bug

**Comment by huan** [comment] 2022-02-28 10:28
Appreciate for linking them together, have a great day!
