### ISSUE TITLE
react-redux used by decorators

### ISSUE THREAD

**Issue by wangcongyi** [swc-project/swc#4621] opened 2022-05-11 11:30 UTC
### Describe the bug

```js
import React from 'react'
import { connect } from 'react-redux'

@connect(
  state => {
   return xxxx
  }
)
class App extends React.Component {}

export default App

```

if I used react-redux/connect decorators syntax.  
![image](https://user-images.githubusercontent.com/13843979/167838553-7e1442a9-d2bb-4ab3-9666-354ba81633e8.png)
or
![image](https://user-images.githubusercontent.com/13843979/167838732-cbc1188b-f9a0-4930-a882-a1ba1a9d3f46.png)

but if I don't use decorators syntax.

```js
import React from 'react'
import { connect } from 'react-redux'

class App extends React.Component {}

export default connect()(App)

it's worked

```

### Config

```json
"jsc": {
    "target":"es5",
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "classPrivateProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "importMeta": true,
      "transform": {
        "legacyDecorator": true,
        "react": {
          "pragma": "React.createElement",
          "pragmaFrag": "React.Fragment",
          "throwIfNamespace": true,
          "development": false,
          "useBuiltins": false,
          "refresh": true
        }
      }
    }
  }
```

### Expected behavior

fix decorators syntax 

### Version

"@swc/cli": "^0.1.57"   "@swc/core": "^1.2.182",  "swc-loader": "^0.2.0",   "react-redux": "^7.2.2",

**Comment by kdy1** [comment] 2022-05-12 03:05
Can you provide more info?
Did it work previously?
Or, does it work with `tsc`?

**Comment by wangcongyi** [comment] 2022-05-18 08:43
@kdy1 We can use decorators syntax with `react-redux`, like the below code
```js

import React from 'react'
import { connect } from 'react-redux'

@connect(
  state =>{xxxx},
  dispatch => {xxxx}
)
class App extends React.Component {
  render() {
   <div>xxxx</div>
  }
}

export default App

```

swc-loader didn't work though at `.swcrc` set up decorators config.

when I don't use decorators syntax.
```js

import React from 'react'
import { connect } from 'react-redux'

class App extends React.Component {
  render() {
   <div>xxxx</div>
  }
}

export default connect(fn,fn)(App)

```

swc-loader worked.

**Comment by kdy1** [comment] 2022-05-18 08:56
Oh I think I found the cause.

**Comment by kdy1** [comment] 2022-05-18 08:59
It's actually https://github.com/swc-project/swc-loader/issues/50

**Comment by wangcongyi** [comment] 2022-05-19 03:44
fixed the issue? I update the latest version, try rebuilding, and still error.

**Comment by wangcongyi** [comment] 2022-05-20 09:00
@kdy1 
I update v1.2.187, unfortunately, it still didn't work. 
How can I provide you with more information?

**Comment by kdy1** [comment] 2022-05-20 09:03
Can you provide a repro?

**Comment by kdy1** [comment] 2022-05-21 15:00
Can you try the new verison once it's published?

`v1.2.189`: https://github.com/swc-project/swc/actions/runs/2363309064

decorator config issue: https://github.com/swc-project/swc/issues/4734 (fixed with `v1.2.189`)

**Comment by wangcongyi** [comment] 2022-05-23 11:23
@kdy1 https://github.com/wangcongyi/swc-test

**Comment by wangcongyi** [comment] 2022-07-08 03:30
@kdy1 hello, Have you have a feasible plan?

**Comment by wangcongyi** [comment] 2022-08-04 08:58
@kdy1 
![49FB048C](https://user-images.githubusercontent.com/13843979/182807326-c78095bc-e344-43a4-8eb3-a9ba55d7970b.png)

**Comment by Austaras** [comment] 2022-10-30 08:24
Seems like this has already been fixed.

**Comment by kdy1** [comment] 2022-10-30 09:12
Thanks!

**Closed by kdy1** 2022-10-30 09:12 UTC
Labels: C-bug

**Comment by wangcongyi** [comment] 2022-10-31 02:08
@Austaras I still get an error when I run my own project, 
@swc/cli": "^0.1.57,
@swc/core": "^1.3.11,
"swc-loader": "^0.2.3",

```

{
  "test": ".jsx?$",
  "jsc": {
    "target":"es5",
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "classPrivateProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "importMeta": true,
      "transform": {
        "legacyDecorator": true,
        "react": {
          "pragma": "React.createElement",
          "pragmaFrag": "React.Fragment",
          "throwIfNamespace": true,
          "development": false,
          "useBuiltins": false,
          "refresh": true
        }
      }
    }
  }
}


```

**Comment by Austaras** [comment] 2022-10-31 03:51
You're passing wrong config, it should be
```json
"jsc": {
    "target":"es5",
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "classPrivateProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "importMeta": true
    },
    "transform": {
      "legacyDecorator": true,
      "react": {
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "throwIfNamespace": true,
        "development": false,
        "useBuiltins": false,
        "refresh": true
      }
    }
  }
```

**Comment by wangcongyi** [comment] 2022-10-31 04:29
oh yes!!  thank you so much  @Austaras
