### ISSUE TITLE
Env configuration and compile target doesn't lead to polyfilled .at()

### ISSUE THREAD

**Issue by gu-stav** [swc-project/swc#6460] opened 2022-11-16 13:58 UTC
### Describe the bug

When using `env: "usage"` and `[].at()` swc does not automatically include the core-js polyfill for `.at()`, but does for other methods such as `.replaceAll()`. Changing the version of core-js or the compile target doesn't change anything.

### Input code

```typescript
'1.2.3'.split('.').at(-1);
[123,456].at(1);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2015",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true,
  "env": {
    "mode": "usage"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.17&code=H4sIAAAAAAAAA1MvSS0uUdcrSi3ISUxOdczJ0VBX11FQV9e05lI31DPSM1bXKy7IySzRUNdT19RLLNHQNQRKRRsaGceCeCAOAG324sZDAAAA&config=H4sIAAAAAAAAA0WMTQ4CIQyF79I1CzXRxdzBQzTYIRj%2BQsFICHefYjCza9%2F73tfhzRq2DgkzU54Xt1DwCxuQ9sg621RACSbRjo5pKCiYDZWJ8O1yvUvtYmRagAJvg93blOnoUybms8Jg3J8c4vLxVWfQobREP%2BcDxulYO8vPBZZc5afwmRtZz01lNARjHHmxrfrPAAAA

### Expected behavior

I'd expect that the core-js `.at()` (`/array/at`) polyfill is included if the `target` attribute requires it to be polyfilled. In this case `node@14` does not support the method.

### Actual behavior

The core-js polyfill is not included.

### Version

1.3.17

**Comment by Austaras** [comment] 2022-11-17 22:44
You need to mannaly specify core-js minor version -- `at` polyfill is included at a much later version of core-js 3

**Comment by Austaras** [comment] 2022-11-30 12:34
This should be closed.

**Comment by gu-stav** [comment] 2022-11-30 12:52
@Austaras 

> You need to mannaly specify core-js minor version -- at polyfill is included at a much later version of core-js 3

That's interesting, thanks! I didn't try that because the TS definitions don't reflect that in the repl at least, but it seems to work: https://play.swc.rs/?version=1.3.17&code=H4sIAAAAAAAAA1MvSS0uUdcrSi3ISUxOdczJ0VBX11FQV9e05lI31DPSM1bXKy7IySzRUNdT19RLLNHQNQRKRRsaGceCeCAOAG324sZDAAAA&config=H4sIAAAAAAAAA0WMTQ4CIQyF79I1CzXRxdzBQzTYIRj%2BQsFICHefYjCza9%2F73tfhzRq2DgkzU54Xt1DwCxuQ9sg621RACSbRjo5pKCiYDZWJ8O1yvUvtYmRagAJvg93blOnoUybms8Jg3J8c4vLxVWfQobREP%2BcDxulYO8vPBZZc5afwmRtZz01lNARjHHmxrfrPAAAA

<img width="723" alt="Screenshot 2022-11-30 at 13 51 30" src="https://user-images.githubusercontent.com/2244375/204801136-8525a14b-264e-43ac-9ffb-20f3c338372a.png">

Thanks!

**Comment by gu-stav** [comment] 2022-11-30 13:04
The problem does still exists locally though: Given the following setup:

```js
transform: {
    '^.+\\.js$': [
      '@swc/jest',
      {
        env: {
          mode: 'usage',
          coreJs: '3.26.1',
        },

        jsc: {
          parser: {
            jsx: true,
            dynamicImport: true,
          },
        },
      },
    ],
```

fails on node@14:

```
    TypeError: data.replaceAll is not a function

      14 |
      15 | const PreviewWysiwyg = ({ data }) => {
    > 16 |   const html = useMemo(() => sanitizeHtml(md.render(data.replaceAll('\\n', '\n') || '')), [data]);
         |                                                          ^
      17 |
      18 |   return (
      19 |     <Wrapper>

      at replaceAll (packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16:58)
      at mountMemo (node_modules/react-dom/cjs/react-dom.development.js:15846:19)
      at Object.useMemo (node_modules/react-dom/cjs/react-dom.development.js:16219:16)
      at useMemo (node_modules/react/cjs/react.development.js:1532:21)
      at PreviewWysiwyg (packages/core/admin/admin/src/content-manager/components/PreviewWysiwyg/index.js:16:23)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
```

It doesn't sem to inject the proper core-js methods. Am I holding it wrong?

**Comment by kdy1** [comment] 2023-01-12 06:50
This was not a bug of SWC, and the problem was your config. I'll close this with [a PR adding a test case](https://github.com/swc-project/swc/pull/6794) to ensure that this is not a bug.

**Closed** 2023-01-12 11:01 UTC
Labels: C-bug
