### ISSUE TITLE
Both gnu and musl core distributions installed for Ubuntu Linux

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [swc-project/swc#3652] opened 2022-02-20 22:43 UTC
### Describe the bug

After `npm i @swc/jest` in a project, there are two core distributions available in `node_modules`:

```
$ du -sh node_modules/@swc/*
444K    node_modules/@swc/core
74M     node_modules/@swc/core-linux-x64-gnu
78M     node_modules/@swc/core-linux-x64-musl
24K     node_modules/@swc/jest
```

### Input code

```typescript
npm i @swc/jest
```

### Config

```json
n/a
```

### Expected behavior

Both of these are >70M in size. Ideally only one would be installed at a time.

### Actual behavior

Both packages have the same system dependencies listed in their `package.json` files:

```jsonc
{
  // ...
  "os": [
    "linux"
  ],
  "cpu": [
    "x64"
  ],
  // ...
}
```

...and so both get installed on Linux x64 systems.

### Version

1.2.143

### Additional context

I'm not familiar enough with npm/node OS & CPU identifiers to know whether a more granular description could be used. If there is, I would _love_ to send a PR to fix this. 😄 

If not, it might be the case that https://github.com/npm/rfcs/pull/519 blocks a real resolution?

Context: https://github.com/typescript-eslint/tslint-to-eslint-config/pull/1367. WSL 2.0 in an Ubuntu drive.

**Comment by kdy1** [comment] 2022-02-21 07:01
cc @Brooooooklyn Is there a way to fix this?

**Comment by Brooooooklyn** [comment] 2022-02-21 08:13
As mentioned above, we need to wait https://github.com/npm/rfcs/pull/519 landed to fix this issue.
There is a workaround that may reduce the install size: https://github.com/vercel/next.js/pull/32850

**Comment by erawk** [comment] 2022-11-10 15:33
Hey @kdy1 @Brooooooklyn - this is causing some NexJS deployment issues on Vercel, as [reported in this issue](https://github.com/vercel/next.js/issues/42641)

1. Vercel uses Linux x64, so both `@swc/core-linux-x64-(gnu|musl)` folders are added
2. In `13.0.2`+ of NextJS, `Prisma` is added as an external and thus included in builds
3. The combined weight of Prisma + 2x @swc/core exceeds the 50MB limit

Here's a screenshot from Vercel build log:

![image](https://user-images.githubusercontent.com/33198/201137082-e579f046-6877-497a-8f4b-028989da918c.png)

My current super hacky fix with gnarly consequences:

Add a `postbuild.sh` script that runs to zero-out the unnecessary `musl` version:

```
# Make the large files zero btytes for the `musl` SWC
echo "Nuking unnecessary @swc/core files in node_modules/@swc/core-linux-x64-musl"
DISK_USAGE_MUSL_BEFORE=`du -h node_modules/@swc/core-linux-x64-musl/*`
echo "${DISK_USAGE_MUSL_BEFORE}"
echo '' > node_modules/@swc/core-linux-x64-musl/swc
echo '' > node_modules/@swc/core-linux-x64-musl/swc.linux-x64-musl.node
DISK_USAGE_MUSL_AFTER=`du -h node_modules/@swc/core-linux-x64-musl/*`
echo "${DISK_USAGE_MUSL_AFTER}"
```

This gets us under the threshold but opens us up to failure if indeed `musl` is needed.

Are there any alternatives you suggest? Anything else downstream we can do to avoid this double inclusion?

**Comment by kdy1** [comment] 2022-12-07 01:01
This is not a bug of swc

**Comment by kwonoj** [comment] 2023-07-24 18:38
https://github.com/npm/rfcs/issues/438#issuecomment-1648118990

Latest npm claims this issue is fixed, so closing. In any case this is techinically pkg mgr issue.

**Closed by kwonoj** 2023-07-24 18:38 UTC
Labels: C-bug
