### ISSUE TITLE
Problem with code that depends on hoisting

### ISSUE THREAD

**Issue by ashrafsabrym** [swc-project/swc#271] opened 2019-02-22 20:39 UTC
Please view my [test-swc](https://github.com/ashrafsabrym/test-swc) repository as it has the code to easily reproduce the bug.

The file directive2.ts has this pattern:
```typescript
link: function (scope: ICustomScope)
        {

            scope.startOperation = startOperation;

            function startOperation(operation: string)
            {
                scope.agentOperation = operation;
            }
        }
```
running `npx swc ./directives/directive2.ts -d ./` and examining the output, it's:
```javascript
link: function(scope) {
            var startOperation1 = function startOperation1(operation) {
                scope.agentOperation = operation;
            };
            scope.startOperation = startOperation;
        }
```
Clearly this code won't work because function name was modified.
In swc 1.0.21 it wouldn't work too, because the output JavaScript was like:
```javascript
link: function(scope) {
            scope.startOperation = startOperation;

            var startOperation = function startOperation(operation) {
                scope.agentOperation = operation;
            };
        }
```
JavaScript hoisting will set `scope.startOperation` to `undefined` because it's the value of the var by the time of execution.
Babel will leave the Typescript code as it's with the same order.

**Comment by duncanbeevers** [comment] 2019-02-23 05:07
Dupe of https://github.com/swc-project/swc/issues/245
Fixed as of 1.0.22 or 1.0.23

**Comment by ashrafsabrym** [comment] 2019-02-23 07:08
@duncanbeevers I'm using 1.0.25

**Comment by kdy1** [comment] 2019-02-23 11:19
I'm investigating on this. It seems like a hygiene bug...

**Closed** 2019-02-23 12:56 UTC
