### ISSUE TITLE
`#__PURE__` on member expressions should be handled

### ISSUE THREAD

**Issue by dgreensp** [swc-project/swc#4893] opened 2022-06-06 18:07 UTC
### Describe the feature

If I have an export like `export const foo = ...`, this export will only be removed if the RHS can be determined to be side-effect-free, understandably.  Member accesses in general are considered to potentially have side effects (with the exception of Math.PI; see implementation of `is_pure_callee`), which is very conservative.  I have exports like `export const HTMLElement = window.HTMLElement` in a module, and it's inconvenient that SWC is worried about the side effects of an expression like `window.HTMLElement`.

There is a quite ugly workaround, involving temporarily reassigning the global `Math`.  It would be great if there were some other way to mark an expression (or export) as side-effect-free, such as with a comment, a wrapper function with a magic name, or even some identifier besides Math that you can access properties on and have it considered to be pure, like if you name your local variable `__pure` you are ok.

**Comment by Austaras** [comment] 2022-06-07 06:58
terser/terser#513

**Comment by Austaras** [comment] 2022-06-20 03:18
Reread the terser thread, seems like the only objection is maintenance cost.

**Comment by kdy1** [comment] 2022-06-20 08:52
Honestly, I think the problem is that you have 

`export const HTMLElement = window.HTMLElement` in a module.


I'm fine with the maintenance cost, but not sure about adding it to `getter` instead of a member expression

**Comment by Austaras** [comment] 2022-06-20 10:01
~~The maintenance cost of swc is sky high anyway~~

`const href = location.href` seems like a fairly common pattern

**Comment by kdy1** [comment] 2022-06-20 10:06
I think access to global `location` can be marked as pure.

**Comment by kdy1** [comment] 2022-06-20 13:55
I think we can add the pure comment support for member expressions, and I think we should.

Currently, this can be done via

```js
export const MyExport = /*#__PURE__*/ (function () { return window.MyExport; })()
```

but this does not look like a good idea.

**Comment by dgreensp** [comment] 2022-06-20 14:21
I didn't know about `/*#__PURE__*/`.  I will try that out.

**Comment by dgreensp** [comment] 2022-06-21 05:25
For what I'm doing (Deno bundling), the comment here doesn't seem to have any effect:

```ts
export const MyExport = /*#__PURE__*/ (function () { return window.MyExport; })()
```

I was grepping the SWC code for `__PURE__`, and it looks like it is checked for in the minifier, not the optimizer?  I'm not sure if that's right.

**Comment by kdy1** [comment] 2022-06-21 05:51
Yeah, it's only handled by the minifier

**Closed** 2022-06-28 06:56 UTC
Labels: enhancement
